### ISSUE TITLE
Application-authentification not available

### ISSUE THREAD

**Issue by etiennekintzler** [ropensci/rtweet#153]
The **application authentification is not available**.

The benefits of this authentification would be increased limit rate ([https://developer.twitter.com/en/docs/basics/rate-limits](https://developer.twitter.com/en/docs/basics/rate-limits))

The process to use application-only auth is explained here ([https://developer.twitter.com/en/docs/basics/authentication/overview/application-only](https://developer.twitter.com/en/docs/basics/authentication/overview/application-only) ).

I have already written code to use this kind of authentification (but it is not integrated with the other rtweet functions), which I can share it with you.

Thank you very much

**Comment by skjainmiah** [comment]
When i executed below code to create a token it showing me an error
```
create_token(app = "mytwitterapp", consumer_key, consumer_secret,
set_renv = TRUE)
```
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).

can you please help me to get out it. plz

**Comment by rajaramana** [comment]
@skjainmiah You need to set your call back URL in twitter to http://127.0.0.1:1410. This will get rid of your error.

**Comment by rajaramana** [comment]
@etiennekintzler Could you please share the approach how you were able to authenticate with the application?

**Comment by dbuijs** [comment]
Will that work with hosted RStudio? I can't seem to get the callback to work.

**Comment by AnalyticJeremy** [comment]
Since June, 2018, the package has supported bearer tokens with the `bearer_token` function.  This provides application-only authentication to Twitter (and thus higher API rate limits).

Example:
`
twitter_token <- create_token(
                    app = "my_twitter_app",
                    consumer_key = "<redacted>",
                    consumer_secret = "<redacted>",
                    access_token = "<redacted>",
                    access_secret = "<redacted>")


b_token <- bearer_token(twitter_token)

search_tweets("#rstats", n = 10, token = b_token)
`
