### ISSUE TITLE
Authorize on AWS Ubuntu Server

### ISSUE THREAD

**Issue by oli666** [ropensci/rtweet#156]
Hi,

I have issues getting my app authorized. I am running an Ubuntu server on AWS doing the development either via a SSH connected Shell or via Rstudio in the browser. I tried both ways (shell, rstudio in the browser) to run through your authentication process (something I have completed successfully on two windows machines without problems before). However, now I have the following issues: 

- Running on the Shell I get the error "Error in httpuv::startServer(use$host, use$port, list(call = listen))   Failed to create server"

- Running Rstudio in the browser at the Ubuntu server URL: I get to the page "Authorize package_rtweet to use your account?" upon first usage of a rtweet function. I can then authorize the app but do fail at the re-direction process. 

Any suggestions would be highly appreciated.

Thanks,

Oli

**Comment by dbuijs** [comment]
I have this problem as well with hosted RStudio. The callback to  127.0.0.1:1401 doesn't seem to be working. I have the user tokens directly from the Twitter Developer platform, but I can't seem to create a valid token object out of them.

**Comment by mkearney** [comment]
I've been dealing with this issue the last few weeks. My only good solution is to create a token locally and upload it so it's accessible on the server. If you run a function like `search_tweets()` on your local machine (using the newest version of rtweet), it'll create and store a token for you. You can extract that and save it someone easier to find–and then upload it to a server.

``` r
token <- rtweet::get_tokens()
saveRDS(token, "~/Desktop/twitter_token.rds")
```

On the server you can create a `.Renviron` file in your home directory (or in your working directory) with the location of where you uploaded the token to. OR, you can read in the token in your script file and specify the token explicitly on calls.

**Comment by mkearney** [comment]
I'm going to leave this issue open for the time being because I bet there's a better solution...and I would love to know it!

**Comment by DataStrategist** [comment]
I'm trying the same... set it up on a Digital Ocean droplet runing ubuntu 16.04. The hack of saving the creds and then loading into the server did work, but yeah not ideal. 

I did try changing the callback url to the server ip address, and also to my server ip`:1401`, both to no avail.... but I'm guessing those are wrong because the error page complained about the localhost...

Anyway, in case it helps, I WAS able to authenticate with both streamR and twitteR and in both cases no URL callback was required... not sure if the API has changed since though.

**Comment by 19wolf** [comment]
> On the server you can create a .Renviron file in your home directory (or in your working directory) with the location of where you uploaded the token to. OR, you can read in the token in your script file and specify the token explicitly on calls.

How can I do this?

**Comment by Arf9999** [comment]
I have RStudio-Server running on an AWS EC2 instance. But the callback from browser based OAuth fails.

I'm pulling my hair out on this. I have created a token locally, uploaded it, and ensured that it is loaded in to the environment but still no luck.

I get this: 
`` target_acc <- "arfness"
target_fol_data <- lookup_users(target_acc)
Error: API user token required. see http://rtweet.info/articles/auth.html for instructions``

Is it possible to generate a token in other way? I'd really like to offload some of my R scripts into the cloud and free up some processing on my own PC.

Alternatively, is there no way to build a oauth2.0 token that doesn't require browser authorisation?

**Comment by mkearney** [comment]
@Arf9999 I've got good news: you can know create a token in non-interactive sessions (I'm aiming for CRAN release in next few days but for now you'll need most recent GH version):

``` r
## install most recent version from github
devtools::install_github("mkearney/rtweet")

## create token using app keys AND oauth keys (these are fake keys)
token <- create_token("twitter", 
  consumer_key = "8bogRvwToBKlasdfa6asf8af",
  consumer_secret = "9Jc4kOCsu6tN1UGgvlnpoGSIas8d7fa0dsfafdsasdfa0897",
  oauth_key = "2973406683-H6Vjqvp8nVHLKgyq5jZSDSFDSD87SDSDF",
  oauth_secret = "BQtruaSAT1eBkecurDtfRuyyUBaiuasytdf765sfd")
```

**But don't stop reading yet.** The method you used should still work, I believe **you just need to explicitly specify the token in each rtweet call**. This can be accomplished by supplying the name of your token object via the `token` argument for any functions that send requests to Twitter's APIs `search_tweets()`, `get_timelines()`, `lookup_users()`, etc.

``` r
## read locally created token into AWS R session
token <- readRDS("twitter_token.rds")

## lookup data for arfness
target_fol_data <- lookup_users("arfness", token = token)
```

I'm also working on a [bearer token](../blob/master/R/bearer_token.R) workflow, which would make it possible to access application-only rate limits by converting an oauth token (the default) into a bearer token. In the case of `search_tweets()`, for example, this would increase the maximum number of tweets returned every 15 minutes from 18,000 to 45,000. I wouldn't recommend using it for any time-sensitive or super important data collection yet, but it should be functional in most recent GH version.

``` r
## search for 45000 tweets w/o waiting on normal rate limit reset
rt <- search_tweets("lang:en", n = 45000, token = bearer_token())
```

Or to use this method in an AWS instance, you should be able to read/create a token object and supply it to the `bearer_token()` function, i.e.,

``` r
## read locally created token into AWS R session
token <- readRDS("twitter_token.rds")

## search for 45000 tweets w/o waiting on normal rate limit reset
rt <- search_tweets("lang:en", n = 45000, token = bearer_token(token))
```

If you try any of these things listed in this post, btw, I'd love to know how they work (good and bad news welcome)!

**Comment by mkearney** [comment]
One more thing @Arf9999: even if you use the non-interactive/browser-based authentication method, I would still recommend explicitly defining the `token =` argument for each rtweet function that sends a request to Twitter's APIs. A lot of the behind the scenes magic that happens when rtweet searches for your token assumes the session is interactive, so it's best to always include the `token =` argument when sourcing scripts, sending jobs to servers, etc..

**Comment by Arf9999** [comment]
That is some speedy feedback.  I'll try all and report back!

**Comment by suprematis** [comment]
@mkearney I have tried the token creation method that includes the consumer and oauth key and secret but I get an error:
`Error in create_token("twitter", consumer_key = "xxxXXxxXXxxxXX0000xxxx",  : 
  unused arguments (oauth_key = "111111111-xxxXXXxxXXxXXXXXXXXXXXXXXX", oauth_secret = "XXXXxXXXXXxxxxxXXXXXXxXXXXXX1000xx001xxx")`

Could you shine some light on why this is happening?

**Comment by Arf9999** [comment]
@suprematis Are you using the latest github version of rtweet or the CRAN version?

If the latter, try reinstalling the rtweet package like so:

```
library(devtools)
## install dev version of rtweet from github
devtools::install_github("mkearney/rtweet")
```
