### ISSUE TITLE
instructions for development/test setup / tokens

### ISSUE THREAD

**Issue by tbuckl** [ropensci/rtweet#161]
For those looking to set this package up for local development (and run tests) I did the following 

1) Authenticate as instructed in the vignette [here](http://rtweet.info/articles/auth.html)  

2) Save the tokens to the `/tests/testthat` directory. For example:  
```
library(rtweet)
twitter_tokens <- get_tokens()
library(readr)
write_rds(twitter_tokens,
          path="rtweet/tests/testthat/twitter_tokens")
```
3) run rests...ahhh  

thanks @mkearney!

**Comment by hrbrmstr** [comment]
and MAKE SURE these are in `.gitignore`!!! :-)

**Comment by mkearney** [comment]
Thanks, @tombuckley!

And I'd like to echo @hrbrmstr! Setting up tests was a bit of a nightmare as it required encrypting the test token, etc. (tbh, I saved some explanatory notes/code on the subject but currently don't fully remember what I even did), but without being mindful of security [we'd look like a bunch of unstable geniuses](https://www.theguardian.com/technology/2018/jan/04/meltdown-spectre-worst-cpu-bugs-ever-found-affect-computers-intel-processors-security-flaw).
