### ISSUE TITLE
`get_thread()` useful?

### ISSUE THREAD

**Issue by hrbrmstr** [ropensci/rtweet#164]
I had a TODO to read a friend's recent tweet thread and did so easily in twitter app-proper.

Later on I saw some thread with a stable genius popup book and at the end the author @'d a bot that did a thread capture (which did not work, but meh).

We don't need apps or bots. We have `rtweet`!

Quick and dirty `get_thread()` with a `print()` method:

```r
#' Retrieve an authors tweet thread/rant from a starting status id
#'
#' @param first_status the first status id in the tweet thread
#' @param .timeline_history how much timeline history of the tweet author
#'        to pull to use when searching for the thread?
#' @return `list` with a data frame of the tweets and a text representation of the
#'         thread.
get_thread <- function(first_status, .timeline_history=3000) {

  require(rtweet, quietly=TRUE, warn.conflicts=FALSE)
  require(igraph, quietly=TRUE, warn.conflicts=FALSE)
  require(tidyverse, quietly=TRUE, warn.conflicts=FALSE)

  # get first status
  orig <- lookup_tweets(first_status)

  # grab the author's timeline to search
  author_timeline <- get_timeline(orig$screen_name, n=.timeline_history)

  # build a data frame containing from/to pairs (anything the author
  # replied to) that also includes the `first_status` id.
  filter(author_timeline,
         (status_id == first_status) |
           (reply_to_screen_name == orig$screen_name)) %>%
    select(status_id, reply_to_status_id) %>%
    graph_from_data_frame() -> g # build a graph from this

  # decompose the graph into unique subgraphs and return them to data frames
  decompose(g) %>% 
    map(as_data_frame) -> threads_dfs

  # find the thread with our `first_status` ids
  thread_df <- keep(threads_dfs, ~any(which(unique(unlist(.x, use.names=FALSE)) == first_status)))

  # BONUS: we get them in the order we need!
  thread_order <- discard(rev(unique(unlist(thread_df))), str_detect, "NA")

  # filter out the thread from the timeline corpus & sort it
  filter(author_timeline, status_id %in% pull(thread_df[[1]], from)) %>%
    mutate(status_id = factor(status_id, levels=thread_order)) %>%
    arrange(status_id) -> tweet_thread

  # extract the text and make it something readable
  pull(tweet_thread, text) %>%
    paste0(collapse="\n\n") -> thread_text

  # TODO: HTML version of ^^
  
  # make a small data structure to hold both of ^^ since I dislike attributes
  list(
    tweet_thread = tweet_thread,
    thread_text = thread_text
  ) -> out

  class(out) <- c("tweet_thread") # class it so we can print it nicely

  out

}

#' Print method for ^^
print.tweet_thread <- function(x, ...) {
  cat(x$thread_text)
  invisible(x)
}

# Example (i.e. the reason why I wrote this)

# https://twitter.com/_odddie_/status/949142225740427270
xdf <- get_thread("949142225740427270")

xdf
# lots of text

str(xdf, 1)
## List of 2
##  $ tweet_thread:Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	19 obs. of  68 variables:
##  $ thread_text : chr "This article has been weighing heavy on my heart since a friend sent it to me two days ago. It details one of t"| __truncated__
##  - attr(*, "class")= chr "tweet_thread"
```

If desired, I can add some of the necessary error checking & validation and do a PR.

**Comment by hrbrmstr** [comment]
it likely needs a better name since it's really designed to capture an authors self-tweet sequence/rant.

**Comment by mkearney** [comment]
Love the idea! I would prefer to keep dependencies to minimum if possible, so I starting writing non-dplyr/tidyverse version:

``` r
  # get first status
  orig <- lookup_tweets(first_status)

  # grab the author's timeline to search
  author_timeline <- get_timeline(orig$screen_name, n=.timeline_history)

  # build a data frame containing from/to pairs (anything the author
  # replied to) that also includes the `first_status` id.
  g <- author_timeline[
    !is.na(author_timeline$reply_to_screen_name) &
      (author_timeline$status_id == first_status |
         author_timeline$reply_to_screen_name == orig$screen_name),
    c("status_id", "reply_to_status_id")
  ]
  g <- igraph::graph_from_data_frame(g) # build a graph from this

  # decompose the graph into unique subgraphs and return them to data frames
  g <- igraph::decompose(g)
```

But I'm not sure what `threads` is in the next line of code. When I try to run your code I get:

``` r
>   decompose(g) %>% 
    map(threads, as_data_frame) -> threads_df
 Error in as_mapper(.f, ...) : object 'threads' not found
```

**Comment by mkearney** [comment]
> it likely needs a better name since it's really designed to capture an authors self-tweet sequence/rant.

Ahh, yes. This threw me off, but I think you actually have the correct phrasing, i.e., `thread` == series of tweets posted by the same author, `replies` == all tweets replying to a status, and `chain`? == all tweets (replies + replies to replies) originating from a single status.

**Comment by hrbrmstr** [comment]
`threads` was a "me not cleaning up the pipe". fixed.

**Comment by hrbrmstr** [comment]
POSIT: to make `rtweet` easier to maintain and not incur dependency penalties, I _cld_ toss this `get_thread()` into a `rtweethelpers` or `rtweethelpers` or `rtweetaddons` (or something more cleverly named) package since I also have a bunch of code I want to add to make it easier to do things like the following and it will likely have an in-year accelerated set of releases. Thoughts?

<img width="1121" alt="screen shot 2018-01-09 at 4 17 24 pm" src="https://user-images.githubusercontent.com/509878/34744142-37d352b4-f55a-11e7-8249-bac3ef47cad8.png">

<img width="1121" alt="screen shot 2018-01-09 at 4 17 53 pm" src="https://user-images.githubusercontent.com/509878/34744143-37f834b2-f55a-11e7-9290-66ee8e681b64.png">

<img width="1121" alt="screen shot 2018-01-09 at 4 22 12 pm" src="https://user-images.githubusercontent.com/509878/34744144-381d919e-f55a-11e7-86d8-27ae22ca32fb.png">

<img width="1121" alt="screen shot 2018-01-09 at 4 22 34 pm" src="https://user-images.githubusercontent.com/509878/34744145-3840a882-f55a-11e7-9401-198ae6d54bf5.png">

**Comment by mkearney** [comment]
I have no idea how I missed that last post of yours. Sorry, @hrbrmstr! Any update on this? I think it's a great idea!

**Comment by llrs** [comment]
Closing as something similar was added on #305 (not sure about embedding a whole thread). If there is something missing please comment on this issue @hrbrmstr
