### ISSUE TITLE
Feature request: global retryonratelimit

### ISSUE THREAD

**Issue by Enchufa2** [ropensci/rtweet#173]
`python-twitter` has this very neat feature: when you instantiate the `Api` object, there's a `sleep_on_rate_limit` parameter, so that all the methods have this either enabled or disabled (see [here](http://python-twitter.readthedocs.io/en/latest/rate_limits.html)). I think that it would be a nice addition for `rtweet` too.

**Comment by mkearney** [comment]
Agreed. I'll have to check the source code on how they implemented it. In my experience, Twitter doesn't always return rate limit information, which is why, to date, I've tackled this one endpoint at a time.

**Comment by Enchufa2** [comment]
Great, thanks. For the record, the implementation is [here](https://github.com/bear/python-twitter/blob/d28e21ca8b47098395f476bd41366f42d00dd131/twitter/api.py#L4871) and [here](https://github.com/bear/python-twitter/blob/1414e129f340a3de55d5106001c8bba148d3b48f/twitter/ratelimit.py#L37), which works quite reliably according to my experience.

**Comment by alexpghayes** [comment]
I think this is underway in #510
