### ISSUE TITLE
FeatureRequest: Full Archive Search Accesibility

### ISSUE THREAD

**Issue by JPMOS** [ropensci/rtweet#176]
Twitter is just now opening their full archive up to developers and academic researchers, me being one of the latter granted said access I'd like to be able to pull from the historical twitter data without resorting to python's comparatively unfriendly interface with the twitter api. Thank you. Great package.

**Comment by mkearney** [comment]
Thanks for bringing this to my attention. I'm now on the wait list.
![screenshot 2018-02-09 at 10 29 21 am](https://user-images.githubusercontent.com/13401460/36039224-7b352024-0d87-11e8-86e0-6ee531547037.png)

It seems like it may only require minimal changes. I'll try to look into this more soon, but if I get off that wait list I'm sure I'll figure it out faster :)

**Comment by lyons7** [comment]
Yesss!!! This!!! I was just looking for this. I got approved ages ago but couldn't figure out how to access the new premium options. Can't wait until this gets hooked up to R that would be amazing!

**Comment by JasonAizkalns** [comment]
Status check on this? Still waiting? PS - This would be fantastic!

**Comment by raketenjon** [comment]
friendly push of the topic, as it would be very helpful for me :)

**Comment by franciscorodriguez92** [comment]
Hi! Is there any update on this?

**Comment by fuhler** [comment]
following!

**Comment by johnfrombluff** [comment]
Me too!

**Comment by JasonAizkalns** [comment]
@mkearney still on the waitlist or can we close this?

**Comment by igorbrigadir** [comment]
@mkearney It's worth reapplying now that the https://developer.twitter.com/ thing is not in beta anymore

**Comment by Pedelamu** [comment]
It would be awesome if you could enter this feature in the package when you have some time. It would enable to do longitudinal researches on Twitter.

Thank you very much for the package.

**Comment by igorbrigadir** [comment]
In the mean time, here is a good example from @FilipeamTeixeira of searching the Premium API in R: https://github.com/FilipeamTeixeira/TweetAPI-premium/blob/master/TweetAPI_premium.R

**Comment by JPMOS** [comment]
Any word on ways to do a full archive search?

**Comment by igorbrigadir** [comment]
Yeah it looks like `search_fullarchive()` implements the Premium API - but i'd make tests using `search_30day()` endpoint instead (same API), as this one has more free "sandbox" calls - you want to make sure your code and queries are working correctly as these `fullarchive` calls are expensive and much more limited than `30day`.

**Comment by dmrodz** [comment]
Is there no access to full_archive under the full archive/sandbox?

**Comment by llrs** [comment]
search_fullarchive seems to close the issue. For the upcoming API v2 see #468?
