### ISSUE TITLE
Allow stream parsing of non-rtweet, historical json tweet objects?

### ISSUE THREAD

**Issue by thomas-keller** [ropensci/rtweet#184]
Hi,

Thanks so much for this great package! I regrettably was a bit slow on picking up on this resource, so I have quite a few streamed json datasets from other resources (tweepy, streamR, etc). 

I tried running your parse_stream but it silently "failed" to parse the json; reading in a json created from rtweet of course works fines.

Here is the beginning of 3 lines of json, note that it doesn't begin with "created" so it automatically fails the grep in good_lines:

{"quote_count": 0, "contributors": null, "truncated": true, "text": "News Alert:  President Trump's day-old immigration plan is already taking heavy fire from both the $
{"quote_count": 0, "contributors": null, "truncated": false, "text": "Kickstarter bans Swedish woman for raising money to publish book about link between immigration an$
{"quote_count": 0, "contributors": null, "truncated": false, "text": "RT CharlieDaniels: I wish the democrats were as anxious to d

Digging in further to the code, it seems like the json I have is not formatted like the rtweet json, so the good_lines() internal function is cutting out all the otherwise valid lines.

For my purposes, I've just monkey-patched data_stream() so it doesn't use good_lines() and it reads in these foreign jsons fine now. Well, unless there's a line with bad json and then I lose that json.  It seems like good_lines is needed so stream_in doesn't die on half-completed json lines, right?

Anyway, don't know how esoteric my use case is, but I thought I'd mention it. If I can figure out a more general error-handling of bad lines along the lines of the good_lines function it might be worth a patch, but right now the tradeoff is probably not worth it (right now, if a json has an unparsable line the whole thing breaks with this error):

Error: lexical error: invalid char in json text.
           "in_reply_to_status_id_str{"quote_count": 0, "contributors"
                     (right here) ------^ 

Thanks again!

**Comment by hadley** [comment]
I think this is out of scope for rtweet, and since it's been 3 years and no one else has commented, I think this is probably a rare use case (especially since that rtweet is much more popular than it was 3 years ago).
