### ISSUE TITLE
image captions

### ISSUE THREAD

**Issue by aurielfournier** [ropensci/rtweet#186]
Hi, thanks for this fantastic package, its going to save me so much time!

I do a lot of tweeting on behalf of a professional organization, and we try to include image captions when we tweet images so that those with vision impairment can use screen readers to understand what is in the image. 

It would be great if `post_tweet()` allowed for image captions. 

Thanks!

**Comment by hrbrmstr** [comment]
I'd like to pile on this w/a request for `include_ext_alt_text` parameters and the `statuses/show` endpoint (I hacked something together for a work project and may have time to clean it up enough for a PR). Twitter claims it can be part of the lookup endpoint as well but it never gave me things back.

(as a side note, we're seeing malicious groups using Twitter image captions as a means of doing encoded org data exfil, which is one reason I headed over here :-)

**Comment by llrs** [comment]
Closed by #145 when it gets merged, and I also think it is duplicated later on.
