### ISSUE TITLE
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  :    Forbidden (HTTP 403). In addition: Warning message: In strptime(x, fmt, tz = "GMT") :   unknown timezone 'default/America/New_York'

### ISSUE THREAD

**Issue by Jennerz** [ropensci/rtweet#258]
I've been having issues with R for awhile with the rtweet package. The callback url is correct, I have "enable callback locking" unchecked, I tried the CRAN package as well as the other one to load them. I use safari, I've updated my OS system. I make sure there are no spaces in quotes, etc. 

 BUT after I put in,
># install from CRAN
> install.packages("rtweet")
> # load rtweet
> library(rtweet)
> ## whatever name you assigned to your created app
> appname <- "example"
> 
> ## api key (example below is not a real key)
> key <- "example"
> 
> ## api secret (example below is not a real key)
> secret <- "example"
> 
> ## create token named "twitter_token"
> twitter_token <- create_token(
     app = appname,
     consumer_key = key,
     consumer_secret = secret)

I get the following error: 
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Forbidden (HTTP 403).
In addition: Warning message:
In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'default/America/New_York'

And when I use this:
## install devtools package if it's not already
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools")
}

## install dev version of rtweet from github
devtools::install_github("mkearney/rtweet")

## load rtweet package
library(rtweet)
> ## whatever name you assigned to your created app
> appname <- "example"
> 
> ## api key (example below is not a real key)
> key <- "example"
> 
> ## api secret (example below is not a real key)
> secret <- "example"
> 
> ## create token named "twitter_token"
> twitter_token <- create_token(
     app = appname,
     consumer_key = key,
     consumer_secret = secret)

I get THIS error:
Error in httr::oauth_listener(authorize_url, is_interactive) : 
  httpuv package required to capture OAuth credentials.

I'm not entirely sure what the issue is, so if someone could PLEASE help.

**Comment by lulalilalul** [comment]
Looks like you are missing the "httpuv" package! Try installing it.
