### ISSUE TITLE
rtweet 0.6.4

### ISSUE THREAD

**Issue by pwsmfia** [ropensci/rtweet#262]
I need rtweet 0.6.4  github version. How can I find or load ?

**Comment by JBGruber** [comment]
Basically you go back in the commit history and look for the last commit with version 0.6.4. You copy the commit reference and use it with devtools. I didn't check if this was the last with that version but picked one at random (and coincidentally found one with 0.6.4):

`devtools::install_github(repo = "mkearney/rtweet", ref = "9569cd9f7505cc1551e3f6027252778ef0ab570b")
`
