### ISSUE TITLE
Forbidden (HTTP 403) Error

### ISSUE THREAD

**Issue by OGladfelter** [ropensci/rtweet#265]
### Problem

Can't authorize, keep getting HTTP 403 error

### Reproduce the problem

``` r
## install rtweet from CRAN
install.packages("rtweet")
install.packages("httpuv")

## load rtweet package
library(rtweet)

consumerKey <- "omitted"
consumerSecret <- "omitted"

create_token(
  app = "politicalTweetsOG",
  consumer_key = consumerKey,
  consumer_secret = consumerSecret)
```

Results in....

``` r
Error in twitter_init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Forbidden (HTTP 403).
```

Any idea why? I have the correct callback URL and I know the consumer key and secret are correct, so that's not the issue. I can't think of anything else that could be causing the error.

**Comment by IWeavey** [comment]
There was a change by Twitter on June 12th. To fix this problem you need to use 4 arguments.

create_token(
  app = appname,
  consumer_key = key,
  consumer_secret = secret,
  access_token = access_token,
  access_secret = access_secret
  )

**Comment by frankieeder** [comment]
I did this but upon actually attempting to retrieve some data from rtweet, I get an error from what seems to be the Twitter API directly. 
> twitter_app = "bw7"
> consumer_key = ""
> consumer_secret = ""
> access_token_key = ""
> access_token_secret = ""
> 
> create_token(
>   app = twitter_app,
>   consumer_key = consumer_key,
>   consumer_secret = consumer_secret,
>   access_token = access_token_key,
>   access_secret = access_token_secret,
>   set_renv = TRUE
> ) -> twitter_token
> 
> rstats <- search_tweets("groupon", n=1500)

yields:

> Searching for tweets...
Warning: 215 - Bad Authentication data.
Finished collecting tweets!
Warning message:
Bad Authentication data. 
> 

I have added the callback URL, and triple checked that I copied and pasted my keys correctly. I cannot find the "lock callback" checkbox that people have been referring to though.

**Comment by jennykathambi90** [comment]
> There was a change by Twitter on June 12th. To fix this problem you need to use 4 keys/secrets/tokens.
> 
> create_token(
> app = appname,
> consumer_key = key,
> consumer_secret = secret,
> access_token = access_token,
> access_secret = access_secret
> )

This is absolutely the life saving solution!!!!!! Thank you so much it worked like charm, of course with the httpuv library loaded.
