### ISSUE TITLE
Stream  tweet directly into database

### ISSUE THREAD

**Issue by simoncht** [ropensci/rtweet#270]
Hi all, 

this is not an issue with the problem but more of how to solve a specific issue that I have. 
Instead of steaming it into a file, has anyone saved these tweets into a database? 

thank you in advance.

**Comment by marcosci** [comment]
Hi there,

it has been two years ... is there anything out there describing this yet? :)
Could the file_name in stream_tweets be in theory a DB connection? Would that be possible?

Cheers
Marco

**Comment by llrs** [comment]
I'm sure this is possible but this is not the best place to document it. I am closing the issue as it is out of scope of the package. However, if anyone has does this, please post it back for other users to find it.
