### ISSUE TITLE
lookup_users() returns NULL when user has no tweets despite other information being available

### ISSUE THREAD

**Issue by IWeavey** [ropensci/rtweet#271]
The problem is lookup_users() returns NULL when the account has no tweets even though other information is still available.  For example consider the following Twitter account (https://twitter.com/AbbaWykethorne). They have no tweets but when I do lookup_users() on them I get NULL returned.

However, if I include them with another user who does have tweets (https://twitter.com/MFAamri2006) in using lookup_users() then I get a full data frame returned with the information from not only this user but the other user as well. 

The user_ids I used are listed below.
user_id "1009489019015651328" - https://twitter.com/AbbaWykethorne
user_id "1009488868532543488" - https://twitter.com/IvorLeviston
user_id "924055885546213376" - https://twitter.com/MFAamri2006

Code to replicate
``` r
library(rtweet)
user_ids <- c("1009489019015651328", "1009488868532543488", "924055885546213376")
lookup_users(user_ids[1]) #returns NULL
lookup_users(user_ids[1:2]) #returns NULL
lookup_users(user_ids[1:3]) #returns data frame with entries for all 3 users
```

**Comment by llrs** [comment]
There seems to be a proposed fix for this on #325.
