### ISSUE TITLE
Same function - two outputs! #lookup_users act differently - Why?

### ISSUE THREAD

**Issue by Waqasejaz** [ropensci/rtweet#273]
### Query - Unexpected Behavior

Thanks for the fantastic package and making life a lot easier. I have been using the package for some time, and suddenly I felt the same function behaves differently, and because I could not find the solution or any clue so decided to ask. 

The screenshot below indicates the output of "lookup_users" that I used a month ago, it was a bunch of users from my sample and as you can see the output looks visibly different from the same command today. Initially, I could get info like "location", Name" etc, now I don't get such an info.

<img width="674" alt="screen shot 2018-07-14 at 7 28 56 pm" src="https://user-images.githubusercontent.com/23726962/42726903-bc68bf6c-879c-11e8-8057-32fa1d862ff1.png"> 

Using the same command gives me this input now which primarily less informative with tons of NAs and no location, name follower's count etc. The new output gives me this:

<img width="1007" alt="screen shot 2018-07-14 at 7 29 23 pm" src="https://user-images.githubusercontent.com/23726962/42726904-bca017be-879c-11e8-8bbd-b5c1dbf741b6.png">

So, the question is have you with your new upgrade changed it? I need to know this as I will have to cite the reason for the alteration in the paper. Or is this something I am not doing right?

**Comment by llrs** [comment]
Probably this was a breaking change on an upgrade... closing this as it is unlikely to receive ever an answer.
