### ISSUE TITLE
get_timelines for tweet keywords or hashtags

### ISSUE THREAD

**Issue by AnneParth** [ropensci/rtweet#274]
Hi there,

I want to get Twitter timelines of certain persons AND certain hashtags/ keywords. Is it possible to filter the function "get_timelines" in this way? I want to search all tweets about basic income by Finnish members of parliament. I have already looked for their IDs.
I tried to combine search_tweets and get_timelines but it was not possible. Do you have any idea to solve this problem? Thank you very much!

**Comment by marvinmilatz** [comment]
Hi Anne, 

not sure if this is exactly what you are asking for, but two approaches come to mind:

1. Use get_timeline to get the tweets from people you're interested in, then filter by the "hashtags" column in the dataframe returned.
2. Search for the specific hashtags with search_tweets, maybe set the language parameter to Finnish, then filter by the account ids for tweets. 

Perhaps, test trial both approaches. 

Best, 

Marvin

**Comment by Arf9999** [comment]
Hi Anne,

For your specific request, it is likely that the best approach would be to pull the timelines of all the MPs, and then to filter that resulting dataframe by the hashtags concerned.

It may be possible to do it using the search_tweets function, but the results from this are limited in volume and period by the twitter API. So you'd likely not get all the tweets you wanted.

**Comment by egonw** [comment]
Yes, a timeline for a hashtag would be nice. I used to use twitteR to archive tweets for academic conferences, but just ran into the problem that the search interface doesn't go back and only has a windows of about a week. But since I do not know who has been tweeting about the conference, the solution sketched ("get_timeline to get the tweets from people you're interested in") does not really work.

**Comment by Arf9999** [comment]
The limitation here isn't rtweet but rather the endpoints of the twitter API.

Marvin's solutions are the two options that are feasible with the standard API.

**Comment by egonw** [comment]
I was afraid of that :( I'll see next week if I can make some recursive code...
