### ISSUE TITLE
Feature suggestion: include a dataset with some tweet IDs

### ISSUE THREAD

**Issue by perrystephenson** [ropensci/rtweet#279]
I recently scraped about 400,000 tweets about R (including all tweets about #rstats) and it turned out to be a really cool dataset - lots of interesting things to find. https://perrystephenson.me/2018/08/11/analysing-the-r-twitterverse/

Lots of people have asked me to share the data - I'm almost certainly not allowed to, but I understand that Twitter allows people to share Tweet IDs, which you can then use to grab all the details through the API.

So, the suggestion is that you could include the following in the package:

1. A dataset of about 400,000 tweet IDs (under 4MB so it should be fine with CRAN)
2. A modifications to the `lookup_statuses()` function so that it automatically backs off and waits when it hits the API limit, so that users can retrieve the entire dataset in a single call

I'd be happy to do all the work and raise a PR, I just wanted to check whether this fits in with your vision for the package before I spend time doing it :)

**Comment by hadley** [comment]
I think this would be a better fit for a separate package. That way rtweet can stay lean and mean and focussed on wrapping the twitter API.
