### ISSUE TITLE
Issue with selection of tweets 

### ISSUE THREAD

**Issue by DavidSchieferd** [ropensci/rtweet#281]
### Problem

I try to scrape tweets for the first time and am a newby to R as well. The debate I try to scrape has been going on for 25 days. I didn't have a computer that is permently connected to the internet, so I couldn't stream, and instead ran search_tweets2 from time to time in order to grasp the whole discussion. 

As I understood, rtweet should scape tweets in a linear/chronological manner, starting with the latest tweets. However, I ran into some irregularity.

(a) Some days ago, I ran a search, asking for 500.000 tweets. It produced a data set with 363.477 tweets and stopped after that. The lowest status_id in that data set is 1024755941928001544 and the tweet dates back to the 1st of August.
(b) The following morning, I ran another search, same query, asking again for 500.000 tweets, storing results in a different object (and not using max_id). It produced 120.950 tweets. The lowest status_id is 1024219213270003712 and dates back to the 31st of July. 

This behavior does not make sense to me. How can the search that is started later reach further into the past? And still produce less tweets? (It surely would make sense the other way around - if I could not access the tweets from 31st anymore and if the discussion was very heated on that day.) 

What I noted in the data frame is that there are tons of duplicates - often posts appear 5 times but only (seem to) differ in regard to "statuses_count" and "favourites_count". This does not seem to be the explanation for the issue (since the limit of 500 000 has not been reached), however, I thought it could be important. Finally, I have to note that I did not use the most recent R version (but R 3.5). 

Please excuse me if I missed an important point in the working of rtweet. I am just alarmed because if I do not exactly understand which tweets find their way into my data set, my interpretation might be heavily biased.

``` r

metwo0908 <- search_tweets2("#metwo OR #germandream OR #mygermandream", n=500000, retryonratelimit=TRUE)
metwo1008 <- search_tweets2("#metwo OR #germandream OR #mygermandream", n=500000, retryonratelimit=TRUE)
```

### rtweet version
``` r
## copy/paste output
[1] ‘0.6.7’
```

### Session info

``` r
## copy/paste output
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] installr_0.20.0 stringr_1.3.1   tibble_1.4.2    dplyr_0.7.5     rtweet_0.6.7   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     rstudioapi_0.7   bindr_0.1.1      magrittr_1.5     tidyselect_0.2.4 R6_2.2.2         rlang_0.2.1      httr_1.3.1       tools_3.5.0     
[10] utf8_1.1.4       cli_1.0.0        openssl_1.0.2    yaml_2.1.19      assertthat_0.2.0 crayon_1.3.4     bindrcpp_0.2.2   purrr_0.2.5      curl_3.2        
[19] glue_1.2.0       stringi_1.1.7    compiler_3.5.0   pillar_1.2.3     jsonlite_1.5     pkgconfig_2.0.1 
```

### Token

``` r
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> mytwitterappformetwo
  key:    SfA8nV4J8vSeuMdkmki0VJxOP
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret
```

**Comment by Arf9999** [comment]
The difference in the number of tweets surfaced by the search is likely a Twitter search API artefact, not an rtweet issue. The standard search API only returns a selection of results, not every single result. For search terms that have a large number of potential results, typically we only see less than 10% of tweets returned. For terms with fewer results, the percentage of search results is much larger. Unfortunately, how twitter's algorithm decides on which tweets to return is not publicly available info.   In addition it typically will only return results from of previous 7-9 days. More info here: https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html
(The reason that twitter does this, is to create a difference between the free Standard Search API, and the premium and enterprise alternatives that it offers. If you require the full search result, not limited by time, you'll need to find a subscriber to one of the premium plans to help you.)

The duplicated tweets may require an answer from @mkearney, but I **suspect** that it has to do with `retryonratelimit`. The function likely does a new search for each ratelimit pause, checks each result to see if it is unique and then discards it if it isn't. Because in these cases the result is different (favourites count, retweets count etc.) it doesn't discard the duplication. (NB. I haven't checked this - it's just my guess).

**Comment by DavidSchieferd** [comment]
Many thanks for your explanation! Your explanation is illuminating - and I should have read the Twitter-page on the Standard API more thoroughly: 

> Not all Tweets will be indexed or made available via the search interface.

If `retryonratelimit` works as you assume, this could explain why I got seemingly arbitrary numbers of tweets when I ran searches immediately after each other, with the same number of requested tweets and search terms.

The overall implication is a bit sobering - as I don't know the sample mechanism, I will need to be very cautious about making inferences from the scraped tweets. Probably, I should use the data set as a base, see whether I find something that looks like what I expect, and if so, try to get some funding/access to the enterprise version. (Though, I needed to validate that access then would be to the full list of tweets with the hashtags.)

Thanks again!

**Comment by Arf9999** [comment]
If you are going to scrape a number of hashtags, to use the standard search API, it is best to try to do it in real time.  It is possible to create a faux-streaming script that searches a narrow window - this tends to surface almost all if not all of the tweets. If you don't have a machine on 24/7 to do this, it is simple enough to set up a cloud instance of RStudio (Amazon or similar) at a relatively low cost (probably less than $20 per month).

**Comment by sefabey** [comment]
> If you are going to scrape a number of hashtags, to use the standard search API, it is best to try to do it in real time. It is possible to create a faux-streaming script that searches a narrow window - this tends to surface almost all if not all of the tweets. If you don't have a machine on 24/7 to do this, it is simple enough to set up a cloud instance of RStudio (Amazon or similar) at a relatively low cost (probably less than $20 per month).

@Arf9999 Correct me if I am wrong but are you suggesting frequently repeated search API calls to get around the 1% streaming API limit? If so, this might work. However, it would be clearer if you could provide a sample  script using a common keyword that might actually hit the limit (such as `trump`). Also needs to account for duplicates I assume.  I'd be willing to try that.

**Comment by Arf9999** [comment]
I have some code that I used to search all FIFA world cup related tweets in a geographic area over a month, I haven't tried it on a keyword that'll deliver millions of results in a very short space of time, though. The OP's example wasn't likely to deliver the volume of results as, say "Trump" would.  

Give me a couple of hours to find it, comment it, and make it more generic.
