### ISSUE TITLE
Error in create_token() due unused argument (acess_token)

### ISSUE THREAD

**Issue by rgaiacs** [ropensci/rtweet#283]
### Problem

I try to follow the instructions on the `README`, [Authenticate via access token](https://github.com/mkearney/rtweet#2b-authenticate-via-access-token) but

```
Error in create_token(app = "...", consumer_key = "...",  : 
  unused argument (acess_token = "...)
```

was raised

### Expected behavior

Token is created and saved it as an environment variable sucessfully.

### Reproduce the problem

Copy the code snippet from the [README file](https://github.com/mkearney/rtweet#2b-authenticate-via-access-token).

``` r
library(rtweet)
create_token(
  app = "...",
  consumer_key = "...",
  consumer_secret = "...",
  acess_token = "...",
  access_secret = "..."
)
```

And run it.

### Solution to the problem

As mentioned by @Arf9999,

```
  acess_token = "...",
```

should be

```
  access_token = "...",
```

The `README.Rmd` has the line correct but `README.md` still has the misspelled one.

### rtweet version

``` r
[1] ‘0.6.7.9000’
```

### Session info

``` r
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.6.7.9000   formattable_0.2.0.1
```

**Comment by Arf9999** [comment]
"acess_token" is mis-spelled.

**Comment by rgaiacs** [comment]
@Arf9999 Thanks.

The [README.Rmd](https://github.com/mkearney/rtweet/blob/master/README.Rmd) file has the correct spelling but README.md has the wrong one. I was going to send a pull request but I think will be more effective for someone with more experience on the project to fix this.

**Comment by Arf9999** [comment]
Maybe edit your issue report to highlight the error in the README.md

**Comment by Zahra-Shakeri** [comment]
The typo still exists in README.me, which took me 1 hour to figure it out!
