### ISSUE TITLE
Using get_friends for a large number of users

### ISSUE THREAD

**Issue by dataunit1** [ropensci/rtweet#288]
Is it possible to use get_friends for a large number of users?

I've used get_followers to get a list of everyone who follows an account I'm interested in. 
It's returned around 250,000 users.
What I now want to do though is find out how many of these users follow another specific account. 
The way I was thinking I could do this would be to run get_friends on each of the users returned by the previous function. 
However, I can't seem to get that to work:

get_flw <- get_followers(
  "Account", n = Account$followers_count, retryonratelimit = TRUE
)
get_followers <- get_friends(get_flw, n = 5000, retryonratelimit = FALSE, page = "-1",
            parse = TRUE, verbose = TRUE, token = NULL)

Is there any way around this please?

**Comment by NataliaUC** [comment]
Hi! Could you solve this problem? 
get_friends is not working at all for me.

**Comment by llrs** [comment]
Probably the best way would be to list followers of the first account, list the followers of the second account and then see how many of them match.  If you still have the issue, please post back.
