### ISSUE TITLE
search_users with parse=TRUE fails if all found users haven't tweeted anything

### ISSUE THREAD

**Issue by luke-a** [ropensci/rtweet#292]
When calling `rtweet::search_users("John Doe", parse = TRUE)`, one might encounter the error message 

`Error: Columns `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA`, `NA` must have unique names`

I believe this happens when all of the returned users haven't tweeted anything, yet. Because then, [`status_object(x)`](https://github.com/mkearney/rtweet/blob/d5c3233bba3b077ba02872b32b89fa41f87ca8a2/R/tweets_and_users.R#L29) returns a list with all elements being `NULL`.  That is because [`if (`&&`(is.data.frame(x), c("favorite_count", "source") %in% names(x)))`](https://github.com/mkearney/rtweet/blob/d5c3233bba3b077ba02872b32b89fa41f87ca8a2/R/tweets_and_users.R#L119 ) does not return `TRUE`; without any tweets there aren't any column named `favorite_count` and `source`.

**Comment by llrs** [comment]
This specific user now has tweeted, I think there was a more recent report of this issue. Closing it
