### ISSUE TITLE
could not find function "clean_tweets"

### ISSUE THREAD

**Issue by rmoor** [ropensci/rtweet#295]
**### Problem**

I managed to extract tweets from twitter. But the clean_tweets function seems not existing. 

> rt <- search_tweets ("#Monday", n = 100, include_rts = FALSE)

Searching for tweets...
Finished collecting tweets!

> rt = clean_tweets(rt)
Error in clean_tweets(rt) : could not find function "clean_tweets"

**### rtweet version**

> packageVersion("rtweet")
[1] ‘0.6.8’

**Comment by llrs** [comment]
I can't reproduce the problem. Perhaps it is a function that was exported at some point and it is no longer exported?
