### ISSUE TITLE
Stream tweets by long-lat seems inaccurate

### ISSUE THREAD

**Issue by DarioBoh** [ropensci/rtweet#296]
I collected a stream of tweets during Hurrican Michael using the following (ggmap_2.7.903):

`stream_tweets(q = c(-86.6874, 29.6644,-85.1626, 30.5846),  file_name = 'infStreamLocation_gzipF', timeout = 14400, include_rts = F, parse = F) `

However, the function seems to retrieve tweets far off the area I meant to select. I am not sure if the issue is due to the Twitter API, but here is a picture of tweets locations (in red) I got using your package versus the polygon (in yellow) from where I assumed I would have received tweets from:

![hurricanemichael](https://user-images.githubusercontent.com/8321557/46987219-e5a29f00-d0b8-11e8-9907-67b14223191f.png)

**Comment by hadley** [comment]
This is an API limitation:

> The streaming API uses the following heuristic to determine whether a given Tweet falls within a bounding box:
> 
> * If the coordinates field is populated, the values there will be tested against the bounding box. Note that this field uses geoJSON order > (longitude, latitude).
> * If coordinates is empty but place is populated, the region defined in place is checked for intersection against the locations bounding box. > Any overlap will match.
> * If none of the rules listed above match, the Tweet does not match the location query. Note that the geo field is deprecated, and ignored by > the streaming API.
> 
> If you would like to exclude place matches or only include places which fall completely within the bounding box, your code will have to perform > an additional filtering step after reading the filtered stream.

— https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/guides/basic-stream-parameters
