### ISSUE TITLE
get_followers() returns empty

### ISSUE THREAD

**Issue by Xopher00** [ropensci/rtweet#297]
### Problem

I am trying to use the built in get_followers() function, where I get a matrix of all the twitter accounts that are following a specific user. However, this is always returning an empty matrix. Specifying the number of followers to retrieve does not seem to make a difference

**Comment by Real-Edgy** [comment]
I'm having the same issue - the get_followers command returns nothing.

**Comment by llrs** [comment]
On the current version it seems to work well
