### ISSUE TITLE
Request: Scheduled Tweets?

### ISSUE THREAD

**Issue by pbulsink** [ropensci/rtweet#298]
### Request

Twitter has a scheduled tweet API hook, this might be an interesting option instead of scheduling R run to post a tweet with taskscheduleR.

### Expected behavior

This could use API hooks discussed in the official API guide [https://developer.twitter.com/en/docs/ads/creatives/guides/scheduled-tweets-guide](https://developer.twitter.com/en/docs/ads/creatives/guides/scheduled-tweets-guide).

This would look like: 
`schedule_post_tweet(status = "my first rtweet #rstats", media = NULL, 
time = Sys.Time()+3600, token = NULL, 
in_reply_to_status_id = NULL, retweet_id = NULL)`

This could have a logical time default of 1h (for example).

**Comment by hadley** [comment]
This requires a separate twitter ads [developer account](https://developer.twitter.com/en/docs/twitter-ads-api/apply), which requires agreeing to a number of extra terms of service and policies, so I suspect it is out of scope for rtweet.

**Comment by llrs** [comment]
Not necessarily out of scope, I think it might be useful to support it. Certainly it is not about  collect and organize Twitter data but it is about Twitter API. However this will need to wait, and not for next release.
