### ISSUE TITLE
Problems with UTF8 on Mac OS X Mojave

### ISSUE THREAD

**Issue by fussballlinguist** [ropensci/rtweet#303]
### Problem

Hi, after upgrading my system to OS X Mojave rtweet seems to have problems with utf8: When collecting tweets, utf8 chars like German umlauts or emojis are decoded:

@kallenje @fohlen11 GR<U+00D6>LL <U+0001F602> ich traf mich Samstag mit meinem Sohn, er sprach von der Schule, <U+00FC>ber eine Mathearbeit. Er sagte mir, sein Mathelehrer meinte bei einer Aufgabe, die er nicht konnte "lieber auslassen als es versuchen und es falsch zu machen"

But the original tweet looks like this (see https://twitter.com/SotiriosDimadis/status/932599875329458176):

GRÖLL 😂 ich traf mich Samstag mit meinem Sohn, er sprach von der Schule, über eine Mathearbeit. Er sagte mir, sein Mathelehrer meinte bei einer Aufgabe, die er nicht konnte "lieber auslassen als es versuchen und es falsch zu machen"

Note that I have this problem with the function search_tweets() but _also_ with reopening dataframes from previous sessions that used to be ok when I created them a few months ago.

### Reproduce the problem

``` r
## insert code here

```

### rtweet version
0.6.0

### Session info

R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14

### Token

``` r
## copy/paste output
rtweet::get_token()
```

**Comment by Arf9999** [comment]
This sounds like a MacOS LOCALE issue with R, not an rtweet issue.  

You can try forcing R to use UTF8 as below (you may need to change the default language to German, not "en_US.UTF-8" , but I'm not not sure what it would be though (maybe "de.UTF-8"?)

> Open Terminal
> Write or paste in: defaults write org.R-project.R force.LANG en_US.UTF-8
> Close Terminal
> Start R
>
