### ISSUE TITLE
Dowload more than 18,000 tweets per request 

### ISSUE THREAD

**Issue by orlandoandradeb** [ropensci/rtweet#326]
Hello 
I have been using the package rtweet for a few days. One of the main limitation I have found is the amount of tweets you can get in one request and the time that I have to wait (this can be automatically using "retryonratelimit = TRUE" ) . 
This make me worder : Is there a way to get more tweets in a single request? 

Thank you.

**Comment by Arf9999** [comment]
Those limitations are the limitations of Twitter's standard API, so no, it is not possible within the T&Cs of the standard API.

Should you require more, Twitter has premium offerings, but then you'd use another tool as I don't think rtweet supports those API endpoints.
https://developer.twitter.com/en/docs/basics/rate-limits.html
