### ISSUE TITLE
Using rtweet on rstudio.cloud

### ISSUE THREAD

**Issue by AmeliaMN** [ropensci/rtweet#327]
`rtweet` is such a great package! When I work with it on my local computer, I can authorize with twitter using the [usage instructions](https://rtweet.info/#usage). But, working on RStudio Cloud, it doesn't quite work. If I run a function (like `search_tweets()`) I get a popup in another browser tab asking me to authorize Twitter. 
<img width="514" alt="Capture" src="https://user-images.githubusercontent.com/2576787/57729672-5f553800-765c-11e9-95ee-2aadbb8c14c6.PNG">
I click Authorize and it says it's redirecting me back to my application, but then I get an error (presumably) because the IP address isn't available on RStudio Cloud. 
<img width="595" alt="Capture2" src="https://user-images.githubusercontent.com/2576787/57729710-77c55280-765c-11e9-8191-3b68e1f928e1.PNG">
Is there a workaround for this, or is Cloud not an "interactive session"?

**Comment by jeroenclaes** [comment]
I have the same issue on RStudio Server

**Comment by Arf9999** [comment]
The simplest workaround is to create a token on a local machine to your own application like so: https://rtweet.info/articles/auth.html , save it as an rds file, then upload it to the remote server.

setting `token <- readRDS("yourfilename.rds") will upload the token into the envionment.
