### ISSUE TITLE
Short Tweet statuses blocked by error 'cannot exceed 280 characters'

### ISSUE THREAD

**Issue by pbulsink** [ropensci/rtweet#329]
### Problem

New tweet length check code doesn't let short tweets through in post_tweet(), even with default options in clean session. Returns:
```
Error: cannot exceed 280 characters.
```
I've got a pull request ready to come out soon, there needs to be a boolean negation in the tweet length check in post_tweet().

### Expected behavior
This should post a tweet (default: 'my first rtweet #rstats')

### Reproduce the problem
Fails with reported error no matter the tweet status, except for when tweet status is > 280 characters. Then, fails with returned error from Twitter API
``` r
rtweet::post_tweet()
```

### rtweet version
0.6.9

### Session info
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252 
[2] LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] httr_1.4.0     compiler_3.6.0 magrittr_1.5   R6_2.4.0      
 [5] tools_3.6.0    curl_3.3       Rcpp_1.0.1     rtweet_0.6.9  
 [9] jsonlite_1.6   openssl_1.3    askpass_1.1 

### Token
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> BulsinkBot
  key:    39r...
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret
---

**Comment by ellietuttle** [comment]
Also having this issue.

**Comment by zecaclasher** [comment]
> Also having this issue.

Me too. For now, I made my first fork, changed the file myself and loaded my github directly into my R code.

Waiting for the official fix.

**Comment by pasipasi123** [comment]
Same here. In the meantime, I've been using `twitteR::updateStatus()` to post bot tweets but that's no good either really (expects tweet length of 140 chars or less by default, has been deprecated).

**Comment by danielredondo** [comment]
As a temporary solution, you can try to install version 0.6.8. with devtools::install_version()

[https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages](https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages)

**Comment by jdslm** [comment]
I am experiencing the same issue. What are the prospects that that this will be addressed? The server I am using to run Rstudio seemingly won't let me revert to 0.6.8 so fixing this issue in 0.6.9 would be very helpful. Thank you.

**Comment by DavidHemmerle** [comment]
Unfortunately I am experiencing this error as well. I switched back to 0.6.8. but there the post_message does not work. So I am switching back and forth now. 

I love your work. Thanks for fixing it!

**Comment by eliocamp** [comment]
While this issue is not fixed in the package itself, one can programmatically fix it after loading {rtweet} with this lines:

```r
library(rtweet)

is_tweet_length <- function(.x, n = 280) {
   .x <- gsub("https?://[[:graph:]]+\\s?", "", .x)
   while (grepl("^@\\S+\\s+", .x)) {
      .x <- sub("^@\\S+\\s+", "", .x)
   }
   !(nchar(.x) <= n)
}


assignInNamespace("is_tweet_length", is_tweet_length, ns = "rtweet")
```

Now `post_tweet()` should work as expected.

**Comment by DavidHemmerle** [comment]
It works perfectly, thank you very much! Now my favorite twitter package can tweet again :-)
