### ISSUE TITLE
Error in attr(rt, "users") <- users : attempt to set an attribute on NULL

### ISSUE THREAD

**Issue by AlexHiscock56** [ropensci/rtweet#333]
# Searching the below results in an error message that I don't understand, and I can't seem to find out what is causing it. I have tried searching for below 18000, but the same problem persists.

> Roman_Empire_Tweets<- search_tweets("Roman Empire OR Reign of Blood OR Master of Rome OR The Mad Emperor", n=450000, "lang:en", include_rts = TRUE, retryonratelimit = TRUE, token=token)
#Error Message
Error in attr(rt, "users") <- users : attempt to set an attribute on NULL

**Comment by nicktieman** [comment]
Alex,

Having this same issue. Were you able to find a fix?

**Comment by llrs** [comment]
I'm getting a different error: `Error: invalid search type - must be mixed, recent, or popular.`

**Comment by hadley** [comment]
Looks like the original syntax was incorrect — I'm not sure what `lang:en` was supposed to do. I think the best bet is to wait for a reprex — if you see this problem again, please file a new issue with a minimal reproducible example.
