### ISSUE TITLE
search_tweets() provides a warning if the token is invalid or expired but lookup_statuses() does not

### ISSUE THREAD

**Issue by jrosen48** [ropensci/rtweet#334]
Hi @mkearney, and thanks for a research life-changing piece of software.

`search_tweets()` seems to provide a warning if the token is invalid or expired, but `lookup_statuses()` does not. Is this intended--or, should both show a warning?

``` r
library(rtweet)

rt <- search_tweets(
  "#rstats", n = 100, include_rts = FALSE
)
#> Warning: 89 - Invalid or expired token.
#> Warning: Invalid or expired token.

rt
#> data frame with 0 columns and 0 rows

statuses <- c(
  "567053242429734913",
  "266031293945503744",
  "440322224407314432"
)

tw <- lookup_statuses(statuses)
tw
#> data frame with 0 columns and 0 rows
```

<sup>Created on 2019-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Now tracking in #483
