### ISSUE TITLE
Export `home_user()`

### ISSUE THREAD

**Issue by eliocamp** [ropensci/rtweet#338]
I'm writting a package that uses rtweet and one of the functionalities depends on getting home user. Currently I'm using `rwteet:::home_user()` but this won't work if I need to submit to CRAN. 

Would it be possible to export that function?

Thanks!

**Comment by llrs** [comment]
The function is not documented and might be split in the future. Also it seems that it is used in some examples, imho this shouldn't happen as this raises to questions as this one, as well as about what does the function. 
What is the functionality you are looking for? Did you submit your package to CRAN or not?

**Comment by eliocamp** [comment]
[The package](https://github.com/eliocamp/spindler) creates twitter threads. It uses `home_user()` to fetch the last tweet in the user's timeline and send a new tweet as a reply so that all tweets are joined in a thread. 

It is not on CRAN currently.

**Comment by llrs** [comment]
Mmh, If you are making threads it makes more sense to use the last tweet id and reply to it, see #452. It avoids an API call so you won't hit the rate limit and you make sure that you are replying on the thread (if there is another app or you tweet between running each function you could split the thread).
