### ISSUE TITLE
CSV export and open in Excel

### ISSUE THREAD

**Issue by Wombat2018** [ropensci/rtweet#343]
Sorry, I'm a beginner in rtweet. If I save data as csv and open it in Excel, the data is not displayed as in R. There are free rows and some rows do not have information about all columns. I've attached an example.

If I then import the csv back into R, everything is displayed correctly. However, I would like to analyze some things in Excel and therefore I need the right presentation in Excel.

[collecteddogtweets.zip](https://github.com/mkearney/rtweet/files/3401885/collecteddogtweets.zip)

**Comment by Arf9999** [comment]
Opening rtweet CSVs in excel is always a challenge.  The simplest workaround I've found is to open the csv in google sheets, and then download it as an .xlsx file.
https://docs.google.com/spreadsheets/d/19bT4PPLRtaOs-Qor97-fhYGwsDS_3zMM0xnqXG4dwXc/edit?usp=sharing

**Comment by llrs** [comment]
Sot sure which are the "free rows" you mention, but certainly the row number isn't useful here. 
About the missing information it would be useful to know what did you use to collect this data (or a similar query). Also agree that the number automatic conversion to numbers with exponents doesn't seem appropriate.

**Comment by llrs** [comment]
Closing as really exporting data isn't really on the goal of rtweet. You might need to set `options(scipen = 16)` in order to accurately store the numbers. To remove the rownames you have an option in write.csv.
