### ISSUE TITLE
stream_tweets does not filter by language

### ISSUE THREAD

**Issue by DonBunk** [ropensci/rtweet#348]
### Problem

stream_tweets does not filter by language. 

### Expected behavior

For example, I would expect that 
```r
test_stream <- stream_tweets(q = "", timeout = 2, language = "en") 
```
would yield 
```r
test_stream_no_parse$lang

"en"  "en"  "en".... 
```
but instead I get a bunch of other languages.

### rtweet version

``` r
‘0.6.9’
```

### Session info

``` r
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] jsonlite_1.6  stringr_1.4.0 dplyr_0.8.1   rtweet_0.6.9 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       rstudioapi_0.10  knitr_1.23      
 [4] magrittr_1.5     hms_0.4.2        tidyselect_0.2.5
 [7] R6_2.4.0         rlang_0.3.4      httr_1.4.0      
[10] tools_3.6.0      xfun_0.7         htmltools_0.3.6 
[13] askpass_1.1      yaml_2.2.0       digest_0.6.19   
[16] openssl_1.3      assertthat_0.2.1 tibble_2.1.1    
[19] crayon_1.3.4     purrr_0.3.2      readr_1.3.1     
[22] base64enc_0.1-3  curl_3.3         evaluate_0.13   
[25] glue_1.3.1       rmarkdown_1.12   stringi_1.4.3   
[28] compiler_3.6.0   pillar_1.4.0     pkgconfig_2.0.2 
```

**Comment by norcalbiostat** [comment]
I'm noticing the same thing with `search_fullarchive`

**Comment by chris18254** [comment]
Hi guys,

try placing the language premium search operator (e.g. lang:en) directly after each keyword, e.g.
`x <- search_fullarchive("searchterm lang:en",...)`

Check [this thread in Twitter's developer forum](https://twittercommunity.com/t/search-fullarchive-premium-search-operators-lang-de-and-n-not-returning-desired-tweets/134195) for background info.

Also, make sure to check out the [rtweet documentation](https://cran.r-project.org/web/packages/rtweet/rtweet.pdf) and the [Twitter API documentation](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators) to ensure you're using the correct search operators.

Good luck,
Chris

**Comment by norcalbiostat** [comment]
Hi @chris18254 I am using `lang:en` in the searchterm, but not going to do it after every term. i'm collecting tweets that have a variety of keywords and tags, and the search query is limited to like, 120 characters or something like that.

**Comment by chris18254** [comment]
Hi @norcalbiostat, 

In that case, try putting in the search orperator after eacht search term the language restriction should apply to and devide them accordingly, using boulean operators (in caps), e.g.

`x <- search_fullarchive("searchterm1 lang:en OR searchterm2)", ...` or
`x <- search_fullarchive("searchterm1 AND searchterm2 lang:en", ...)`

 Best,
Chris

**Comment by hadley** [comment]
There's no `language` argument to `stream_tweets`, so I think @chris18254's solution is correct here.
