### ISSUE TITLE
Preferred method for exiting stream_tweets(...timeout=Inf)?

### ISSUE THREAD

**Issue by ghostbeagle** [ropensci/rtweet#352]
Hello. I was curious what the preferred method was for safely shutting down a stream_tweets() query that is set to timeout=FALSE or timeout=Inf.  I'm using Rstudio and will normally use "Session>Interrupt R" to do this, but was unsure if there is a better or different preferred option for closing an infinite stream.

**Comment by llrs** [comment]
In Rstudio the easiest way would be to click on the top right STOP signal it appears when a command is running on the console.
