### ISSUE TITLE
Created only about 15 tweets rate limited, created 25 tweets and suspended

### ISSUE THREAD

**Issue by BigTimeStats** [ropensci/rtweet#353]
Already got my app suspended after tweeting about 25 tweets. Trying to better understand why and how to avoid in the future. Really not trying to be spammy, just to get my analysis out there for some wider distribution. Are there any best practices to automating this kind of work?  Read through the Twitter API docs but didn't really find anything specific.

Profile: https://twitter.com/BigTimeStats
Example tweet: https://twitter.com/BigTimeStats/status/1173343311282597888

Worked for the first 15-25 tweets via `rtweet::post_tweet()`, now receiving this message:

```
$errors
$errors[[1]]
$errors[[1]]$message
[1] "Application cannot perform write actions. Contact Twitter Platform Operations through https://support.twitter.com/forms/platform"

$errors[[1]]$code
[1] 261
```

Thanks for the help and package!

**Comment by llrs** [comment]
You probably need to use your own token.
