### ISSUE TITLE
search_fullarchive setup issue 

### ISSUE THREAD

**Issue by rbaird18** [ropensci/rtweet#359]
I have a developer account but I can't seem to get the search_full archive function to work. Perhaps I am setting up the token incorrectly? Do I need to include an endpoint in the token?

**Token:**
![image](https://user-images.githubusercontent.com/55812453/66524802-af6fe380-eab0-11e9-9b7b-5c61590e36e0.png)
**search_fullarchive**
![image](https://user-images.githubusercontent.com/55812453/66524863-df1eeb80-eab0-11e9-87d0-10e2376a6c96.png)

**Results**
I tried to use both the app name and developer environment label inside the function for env_name but got the following errors for both:
![image](https://user-images.githubusercontent.com/55812453/66525064-7e43e300-eab1-11e9-87ca-30d820e622e7.png)

Thanks in advance!
-Ryan

**Comment by rbaird18** [comment]
I believe so. This is what the app looks like:
![image](https://user-images.githubusercontent.com/55812453/66589886-c3692300-eb4c-11e9-99ef-8b795885c107.png)

**Comment by Arf9999** [comment]
In your code, the app name is different? 

"street_flooding" vs "flooding"?

**Comment by rbaird18** [comment]
Yeah my token works for a standard search (search_tweets). I don't recall getting any results to warrant reaching the request limit for the month but I guess it's possible. So I don't need to set up the token any differently for premium API requests vs standard API requests?

**Comment by Arf9999** [comment]
You can check your usage using: https://developer.twitter.com/en/dashboard

Your token seems to be set up correctly, I followed the same process. You could double check your access_token and access_secret are correct, but otherwise I can't see any issue with the way you've created it.

**Comment by rbaird18** [comment]
Thanks for the feedback, Andrew!

**Comment by norcalbiostat** [comment]
@rbaird18 -  [This SO post](https://stackoverflow.com/questions/56413157/downloading-historical-tweets-via-rtweet-from-premium-api-via-r) implies that you do need to set up a token differently to search the full archive. You need a bearer token. But it didn't work for me. 
[This twitter documentation](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search#Introduction) implies that consumer+access token works just the same as a bearer token. 
FWIW i get the "Forbidden" error message when using the consumer+access token, and "not a valid access token" when I use the bearer token. 

I can't help you much further, i can't get it to work myself _at all_. 

@Arf9999  - how did you setup your `token_book`? Did you do the same `create_token()`?

**Comment by Arf9999** [comment]
I created the token with `create_token()`, the `search_fullarchive()` creates a bearer token automatically.

**Comment by Arf9999** [comment]
> Yeah my token works for a standard search (search_tweets). I don't recall getting any results to warrant reaching the request limit for the month but I guess it's possible. So I don't need to set up the token any differently for premium API requests vs standard API requests?

Weeks later and I just had a thought on this: Have you tried using the token according to the name you assigned, rather than the one you read using readRDS()?  Possibly the token info is not being saved or read correctly?

**Comment by mfreyrie** [comment]
I'm also having the exact issue... I also noticed that if I follow the API URL I get this error
![immagine](https://user-images.githubusercontent.com/60174951/72880256-cdc7bb00-3cfe-11ea-8fc4-dbfd83538e34.png)

**Comment by collindever** [comment]
@rbaird18 I was able to get `search_fullarchive` working with your code ... this issue I believe is that your `App Name` cannot be the same as your `Dev Environment Label`. Give that a try and see if it works for you.

**Comment by snvv** [comment]
I have the same problem. As @rbaird18
I have tried both the app name (LongSearch) and developer environment ( FullResearch). 

My question is what is the script rtweet_SetUpToken.r and where to find it?
