### ISSUE TITLE
lists_statuses() returns truncated tweets 

### ISSUE THREAD

**Issue by giocomai** [ropensci/rtweet#362]
### Problem

`lists_statuses()` returns truncated tweets in the `text` column.

### Expected behavior

I'd expect `lists_statuses()` to work similarly to other rtweet functions and retrieve full tweets. 

### Reproduce the problem

``` r
library("rtweet")

twitter_token <- readRDS("twitter_token.rds")
temp <- rtweet::lists_statuses(list_id = 81552450,
                                n = 10,
                                token = twitter_token)
temp$text
#>  [1] "What happens when a women takes part in a race traditionally reserved for men and manages to win? Petrunya does pre… https://t.co/rq0b5uLdOM"    
#>  [2] "Dag Hammarskjöld, Swedish UN Secretary General, died in a suspicious plane crash in 1961 on his way to ceasefire ne… https://t.co/q7MW7zLd8W"    
#>  [3] "EU budget, #SakharovPrize winner, Turkey-Syria debate and Jean-Claude Juncker’s farewell.  All this and more in thi… https://t.co/q84n8zaP2w"    
#>  [4] "A political murder mystery, a thriller about power and corruption and the story of an anti-heroine challenging patr… https://t.co/Elg0ECEb6d"    
#>  [5] "Business in the Chamber will start at 2.30pm today.\n\nThe Speaker plans to make a statement at 3.30pm on the EU (Wit… https://t.co/8dlKHRVhUc"  
#>  [6] "Following #EUCO conclusions, the Council (Art50) has taken the first formal step towards the conclusion of the… https://t.co/07Y9MLp2Tr"         
#>  [7] "UPDATE on the agenda: vote on third vice-chair postponed, ID request to vote on the Coordinators' decision on the p… https://t.co/mugozd7xHz"    
#>  [8] "🤜🤛 #GDPR &amp; blockchain: a relationship of tensions. But blockchain also offers means to achieve #GDPR objectives. Mo… https://t.co/7cpdBodV1A"
#>  [9] "The #Eplenary is on this week! Key items to be discussed include Brexit/EU Funds, the EU Summit and the EU Budget f… https://t.co/ApCs8mdn1W"    
#> [10] "Danes se začenja oktobrsko plenarno zasedanje Evropskega parlamenta v #Strasbourg 🗣 🎙\n👉 znan bo dobitnik nagrade… https://t.co/serELMFlQz"
```

<sup>Created on 2019-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### rtweet version

‘0.6.9’

### Fix

Adding the `tweet_mode = "extended"` parameter in the `lists_statuses_()` function fixes this issue.

See [relevant commit](https://github.com/giocomai/rtweet/commit/59bc5906a0246cfef5c27313db53fd56d3e3c3f1).

**Comment by mkearney** [comment]
Excellent! I didn't realize I had missed adding 'tweet_mode = "extended"' to this endpoint function. Can you submit as a pull request?

**Comment by giocomai** [comment]
Thanks! Pull request submitted!

**Comment by simardcasanova** [comment]
Hi there,

I'm using 0.7.0 and there is still an issue with tweets being truncated when using `lists_statuses()`. Thanks!

**Comment by llrs** [comment]
Thanks for the report @simardcasanova (and for searching before opening a new issue :+1: ), there is a similar issue on `get_timeline` with the development version on  #575. Will track it there as I think both issues have the same root cause and hope to fix both at the same time.
