### ISSUE TITLE
Accessing `counts` endpoint

### ISSUE THREAD

**Issue by ConorIA** [ropensci/rtweet#369]
### Problem

Twitter offers the [counts endpoint](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search#CountsEndpoint) for the 30-day and full archive searches. If my understanding is correct, this may be a useful budgeting tool to determine how many results (and therefore how many requests) a given search will find. However, there does not seem to be a function in *rtweet* that wraps this endpoint. 

### Expected behavior

It should be possible to call the counts endpoint.

Apologies if I am missing something here.

**Comment by mkearney** [comment]
You're not missing anything. This should definitely be added!

**Comment by ConorIA** [comment]
Great! I got this started, but I do not currently have a paid account, so my queries are being rejected. 
https://github.com/ConorIA/rtweet/commit/2f5bc01d76e45adc7eef830ae02623a76934d53f

The next code that will need to be addressed is actually parsing the return. If someone could provide a response object in a RDS (maybe that isn't allowed), I could probably code it. 

Should I open a WIP PR, or would you rather I wait until this has all the pieces together?

**Comment by simoncarrignon** [comment]
i have a paid account so could do some test, is there some branch/fork with code already written to access the counts.json endpoint?

**Comment by ConorIA** [comment]
Hi @simoncarrignon, yes!

https://github.com/ConorIA/rtweet/tree/counts

**Comment by simoncarrignon** [comment]
great! I am trying but I get those warnings and error message:

```
***Warning: list(message = "There were errors processing your request: Unknown parameter:'maxResults'", sent = "2020-02-18T21:28:06+00:00", transactionId = "000268cd00fb4109")
Error in if (is.list(x) && has_name_(x, "status")) { :
  missing value where TRUE/FALSE needed

```

**Comment by simoncarrignon** [comment]
And two other things:  twitter api use `counts` would'nt be more consistent to use `counts = TRUE`? Also I guess that query to counts endpoint should integrate the field `"bucket" : option` (where option can be: "day", "hour", "minute")

**Comment by llrs** [comment]
Currently the API returns an error message 401: "Unauthorized: Stream is not enabled for count requests" with the API v1.1 (even when querying the search/tweets/30day/env/counts.json.

In [the roadmap](https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map) there is a replacement in API v2 for Full-archive Tweet counts, but not yet for 30day. I'll wait to rtweet > 1.0.0 to add support for this with API v2.

**Comment by llrs** [comment]
You can use `tcr <- tweet_counts_recent(query = "#rtweet")` to query the [recent counts endpoint](https://developer.twitter.com/en/docs/twitter-api/tweets/counts/api-reference/get-tweets-counts-recent)
