### ISSUE TITLE
rtweet search_tweet limits to 18000

### ISSUE THREAD

**Issue by shevelp** [ropensci/rtweet#370]
Hi! I am trying to collect more than 18000 tweets using search_tweet, so im using:
`x= search_tweets("y", n= 50000, include_rts = FALSE, retryonratelimit = TRUE, until = "2019-11-05" )`
Starts collecting tweets but when it reaches 100% of the process..
`Downloading [=========================================] 100%
retry on rate limit...
waiting about 13 minutes... `

**Comment by gadenbuie** [comment]
The Twitter API rate-limits search results to 18,000 per 15 minutes. If you ask for more than 18,000 tweets, Twitter won't give them to you until your rate limit resets. When you set `retryonratelimit = TRUE`, `search_tweets()` will pause, wait until your rate limit resets and then try to get more tweets. As you can see in the printed message, that wait was about 13 minutes when you ran this.

**Comment by shevelp** [comment]
thx!
