### ISSUE TITLE
Adding the collapse delimiter as parameter

### ISSUE THREAD

**Issue by brunj7** [ropensci/rtweet#374]
Thanks for this great package! This is a suggestion:

It will be great if the user was able to choose the delimiter as a parameter for  'flatten()` and thus `write_as_csv()`

Let me know if it sounds useful. Happy to do a PR with this small change implemented

**Comment by mkearney** [comment]
Would happily accept this as a PR, but I would want to check how it gets implemented in `save_as_csv()` via flattening/deflattening–i.e., `read_as_csv()` assumes `$mentions_user_id` is space delim so ideally it'd be able to detect (obvi ones: space, comma, plus-sign) and allow user spec via `delim` argument.
