### ISSUE TITLE
No method for reauthorizing?

### ISSUE THREAD

**Issue by jorisc** [ropensci/rtweet#376]
After posting a tweet with the post_tweet() command, I was sent to a browser page and was immediately logged in because of an automatic password program. The command worked, but I want to use it with another twitter account.

I want to change accounts but in the documentation there doesn't seem to be any method for changing the account. I guess my tokens are saved somewhere in a environment variable but I can't find it (I've looked in appData/local and appData/roaming, on a Windows computer obviously).

Any ideas on how I can delete my old login information and login with another account?

**Comment by mkearney** [comment]
Yes. The following will delete your current token and then unset your environment variable:

``` r
unlink(Sys.getenv("TWITTER_PAT"))
Sys.unsetenv("TWITTER_PAT")
```

Btw, deleting your token sounds more dangerous than it actually is. If you accidentally delete your token–*and you're working within a local session of R*–then you will just have to re-authorize next time you send a request (and then the token will be stored for you again).

You could also copy the current token and move it to the desktop prior to deleting it

``` r
file.copy(Sys.getenv("TWITTER_PAT"), "~/Desktop/current-rtweet-token.rds")
unlink(Sys.getenv("TWITTER_PAT"))
Sys.unsetenv("TWITTER_PAT")
```

**Comment by jorisc** [comment]
Thanks a lot,
That worked.

Van: Michael W. Kearney <notifications@github.com>
Verzonden: donderdag 19 december 2019 17:11
Aan: ropensci/rtweet <rtweet@noreply.github.com>
CC: Joris Cuppen <j.cuppen@researchned.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [ropensci/rtweet] No method for reauthorizing? (#376)


Yes. The following will delete your current token and then unset your environment variable:

unlink(Sys.getenv("TWITTER_PAT"))



Sys.unsetenv("TWITTER_PAT")

Btw, deleting your token sounds more dangerous than it actually is. If you accidentally delete your token–and you're working within a local session of R–then you will just have to re-authorize next time you send a request (and then the token will be stored for you again).

You could also copy the current token and move it to the desktop prior to deleting it

file.copy(Sys.getenv("TWITTER_PAT"), "~/Desktop/current-rtweet-token.rds")



unlink(Sys.getenv("TWITTER_PAT"))



Sys.unsetenv("TWITTER_PAT")
