### ISSUE TITLE
stream_tweets(): redirect data stream to standard output

### ISSUE THREAD

**Issue by albertojleon** [ropensci/rtweet#379]
My concern was that when parsing large numbers of tweets, gigabytes of data would accumulate without having a good way to start their processing (other than closing and reopening the stream). If we implement a way to redirect the data stream to the standard output, then it can be piped to the `split` command, and subsequently, blocks of data can be parsed as soon as they are downloaded.

A working example with a new parameter `write_json_stdout` can be found here: https://github.com/albertojleon/rtweet/blob/master/R/stream.R

What do you think?

**Comment by hadley** [comment]
I think it would be better to achieve this within R, although I'm not yet sure how to make that happen.
