### ISSUE TITLE
Invalid Path on Windows for set_renv (via create_token)

### ISSUE THREAD

**Issue by jonthegeek** [ropensci/rtweet#380]
### Problem

I created a token following the instructions in the vignette (using the access_token method). I then restarted my R session and tried to get_token, but it launched a browser window to allow the rtweet app to access my account.

### Expected behavior

It should have reloaded my token.

### Reproduce the problem

This appears to be a windows-specific issue (and COULD be idiosyncratic to something about my machine). This is what was added to my .Renviron: `TWITTER_PAT=C:\Users\jonth\Documents/.rtweet_token.rds`

Updating the `\`'s to `/`'s manually fixed the issue.

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")

[1] ‘0.7.0’
```

### Session info

``` r
## copy/paste output
sessionInfo()

R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.7.0

loaded via a namespace (and not attached):
[1] httr_1.4.1     compiler_3.6.2 magrittr_1.5   R6_2.4.1       tools_3.6.2   
[6] jsonlite_1.6   packrat_0.5.0 
```

**Comment by brshallo** [comment]
I had the exact same issue on my Windows machine. Only happened after updating to 0.7.0 -- older version of `{rtweet}` had been fine -- was only after updating R and {rtweet} that bumped into issue and had to edit .Renviron manually to fix.
