### ISSUE TITLE
get_timeline doesn't retrieve 3200 tweets for realDonaldTrump

### ISSUE THREAD

**Issue by Shooony** [ropensci/rtweet#382]
### Problem

I can't retrieve all of realDonaldTrump tweets. I sometimes get only a few, or a couple hundred. 

### Expected behavior

Using `get_timeline` I would expect to get all of realDonaldTrump's recent 3200 tweets.

### Reproduce the problem

``` r
djt <- get_timeline("realDonaldTrump", n = 3200)
nrow(djt)
```

### rtweet version

0.7.0

### Session info

R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.2

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1

### Token

run the code below and copy/paste the output. if you don't feel comfortable 
sharing that information, then share the first 3-4 characters for the 
oauth_app ($APP_NAME$) and key ($KEY$) as they appear in the printed output 
#> <Token>
#> <oauth_endpoint>
#>  request:   https://api.twitter.com/oauth/request_token
#>  authorize: https://api.twitter.com/oauth/authenticate
#>  access:    https://api.twitter.com/oauth/access_token
#> <oauth_app> pol*****
#>   key:    Snh****************
#>   secret: <hidden>
#> <credentials> oauth_token, oauth_token_secret, user_id, screen_name

**Comment by hadley** [comment]
Now tracking in #510
