### ISSUE TITLE
Confusion about bearer tokens

### ISSUE THREAD

**Issue by alexpghayes** [ropensci/rtweet#387]
I'm trying to understand bearer tokens better by using two tokens that I have for different applications.

I have two tokens, `token1` and `token2`, that are clearly different:

``` r
> identical(token1, token2)
[1] FALSE
```

However, the corresponding bearer tokens are identical. When and why is this the case?

``` r
> bearer1 <- bearer_token(token1)
> bearer2 <- bearer_token(token2)
> 
> 
> identical(bearer1, bearer2)
[1] TRUE
```

**Comment by colts183281** [comment]
Yea I'm working through the same issue. One thing I know is that if you open different projects you create different bearer_tokens but it would be useful to use different bearer tokens in the same project. I'm trying to work through the code and see if I can figure out what's going on.

**Comment by llrs** [comment]
The problem might come from how the bearer are stored. They are added to the rtweet::.state enviroment, so the second bearer token overwrites the first bearer token (if the second gets created at all!) See the `get_bearer` function.
