### ISSUE TITLE
No browser popup, returns 'readRDS(x) : error reading from connection'

### ISSUE THREAD

**Issue by DeJeroenBakker** [ropensci/rtweet#393]
Hi! I'm setting up rtweet for the first time, and according to the documentation I should be able to do so without a developer account by signing into my Twitter account through a browser pop-up. This is the code I'm running:

``` r
library(rtweet)
search_tweets("Test")
```

Which returns:

``` r
Error in readRDS(x) : error reading from connection
```

My browser does not open a new window to allow me to sign in. I have tried setting different default browsers, but no results. Should I wait for my developer application to be approved, or is there another way to solve this?

I'm using the latest version of rtweet (0.7.0) and have httpuv installed.

**Comment by rectalex** [comment]
I have the same problem

**Comment by chris18254** [comment]
Hi you two,

have you tried installing the [httpuv-Package](https://github.com/rstudio/httpuv), as suggested [here](https://rtweet.info/#api-authorization)?
If that doesn't work for you, try setting up a developer account by carefully following [these instructions](https://rtweet.info/articles/auth.html).

Good luck!

**Comment by DeJeroenBakker** [comment]
Hi Chris,

Yes, I have httpuv installed (as stated in my original post), but still no pop-up. Fortunately, I've gotten the developer credentials in the meantime so I have been able to set up the API manually.
