### ISSUE TITLE
Authentication problems with premium account

### ISSUE THREAD

**Issue by snvv** [ropensci/rtweet#394]
**Problem**
I have a premium account but it fails with fullarchive giving the following error message:

Warning: list(message = "Forbidden: Authentication succeeded but account is not authorized to access this resource.", sent = "2020-03-05T14:08:24+00:00", transactionId = "XXXX")

I used both Browser-based authentication and Access token/secret method(*) but the error remains
(*) https://rtweet.info/articles/auth.html

**Reproduce the problem**
co_archive <-search_fullarchive(q = "#CoronaVirusSA", 
                                   n = 50, 
                                   fromDate = "20200210",
                                   toDate = "20200213",
                                   env_name = "env",
                                   parse = TRUE, 
                                   token = mytoken)

**rtweet version**
> packageVersion("rtweet")
> [1] ‘0.7.0’

**Session info**

> > sessionInfo()
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Debian GNU/Linux bullseye/sid
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
>  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] rtweet_0.7.0
> 
> loaded via a namespace (and not attached):
> [1] httr_1.4.1     compiler_3.6.3 magrittr_1.5   R6_2.4.1       tools_3.6.3 jsonlite_1.6.1

**Token**

> mytoken <- create_token(
>   app = "**snvv**",
>   consumer_key = "XXXXXXX",
>   consumer_secret = "XXXXXXXXXXXXXX",
>   access_token = "XXXXXXX-XXXXXXXXXX",
>   access_secret = "XXXXXXXXXXXXXXXXXXXX",
> )

> mytoken <- create_token(
>   app = "**research**",
>   consumer_key = "XXXXXXX",
>   consumer_secret = "XXXXXXXXXXXXXX",
>   access_token = "XXXXXXX-XXXXXXXXXX",
>   access_secret = "XXXXXXXXXXXXXXXXXXXX",
> )

snvv is the App Name and research is the Dev environment label.

PS. I have read all the relevant posts here, but nothing works in my case.

Thank you
Sotiris

**Comment by chris18254** [comment]
Hi Sotiris,

> snvv is the App Name and research is the Dev environment label.

Try setting your env_name accordingly:

`co_archive <-search_fullarchive(q = "#CoronaVirusSA",
n = 50,
fromDate = "20200210",
toDate = "20200213",
env_name = "research",
parse = TRUE,
token = mytoken)`

Best,
Chris

**Comment by snvv** [comment]
Thank you Chris
research is the label on the tweeter environment "Search Tweets: Full ArchiveSandbox, Dev environment label **Research**". 
From the error message, I know that Authentication succeeds, but for some reason, I don't have permission to access the premium account. 
Regards
Sotiris

**Comment by chris18254** [comment]
Hi Sotiris,

in your query, however, the "env_name" doesn't match your Twitter developer environment name: 

```
co_archive <-search_fullarchive(q = "#CoronaVirusSA",
n = 50,
fromDate = "20200210",
toDate = "20200213",
env_name = "env", #You have to exactly match your Dev environment label here
parse = TRUE,
token = mytoken)
```

**Comment by snvv** [comment]
Hi Chris
My bad!!!!
Thank you a lot.
Regards
Sotiris

**Comment by van-mar** [comment]
Hi, 
i just stumbled upon this issue. 
I am getting the same error "Forbidden: Authentication succeeded but account is not authorized to access this resource."

search_fullarchive(q = "#volkswagen",
  n = 100,
  fromDate = "201509010000",
  toDate = "201509300000",
  env_name = "prod",
  parse = TRUE,
  token = mytoken
)

env_name and app name are correctly used.

I am using the sandbox package full archive. 

Do you might have another idea why it does not work?

Thanks for your help.
Vanessa
