### ISSUE TITLE
rate_limit() broken

### ISSUE THREAD

**Issue by thoughtfulbloke** [ropensci/rtweet#395]
### Problem

Sometime in the past week since I last ran this code (more likely in the last few hours) something has changed at the Twitter API end that has broken rtweet's rate_limit function. This has had a flow on effect to functions using retryonratelimit = TRUE, breaking those functions as well.

I tested this on two separate Macs so I do not believe it is an individual machine issue (and it was working a week ago)

### Expected behavior

library(rtweet)

RL <- rate_limit()

should return rate limit information

### Reproduce the problem

library(rtweet)

> RL <- rate_limit()

Error in if (!is_json(rsp)) { : argument is of length zero

> 

``` r
## insert code here

```

### rtweet version
tested with 0.7.0 

### Session info

``` r
## copy/paste output
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_NZ.UTF-8/en_NZ.UTF-8/en_NZ.UTF-8/C/en_NZ.UTF-8/en_NZ.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] rtweet_0.7.0

loaded via a namespace (and not attached):
 [1] httr_1.4.1     compiler_3.6.1 magrittr_1.5   R6_2.4.1      
 [5] tools_3.6.1    curl_4.2       Rcpp_1.0.3     jsonlite_1.6  
 [9] openssl_1.4.1  askpass_1.1   
```

### Token

``` r
## copy/paste output
rtweet::get_token()

<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> Rtweet_for_my_work
  key:    OsV7{edited down by David Hood}
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret
```

**Comment by Arf9999** [comment]
I'm getting the same error. - Looks like twitter has changed something.

**Comment by malcolmbarrett** [comment]
I'm having this, too, but it also seems intermittent. Here, for example, are a bunch of GH Action builds of a twitter bot: https://github.com/malcolmbarrett/epibot/actions. It's failed on and off with the rate limit error but has also succeeded several times. I was also able to run `rate_limit()` just now without issue using several tokens. 

Is this perhaps not a bug but an intermittent issue with the API?

**Comment by thoughtfulbloke** [comment]
Could be intermittent - after not working at all for me yesterday, I am getting normal behaviour today, but I am a little reluctant to mark it closed quite yet- if it is unreliable (and intermittent rather than fixed) I will still be needing to write a bunch of my own exceeding rate limit code.

**Comment by Arf9999** [comment]
Twitter message from one of the dev supporters at twitter:
https://twitter.com/andypiper/status/1235932796503437313?s=20

Seems that it was an issue that is now resolved.

**Comment by thoughtfulbloke** [comment]
Great. Since this confirms that this particular issue was transitory at Twitter's end, and is not going to need any fixes to rtweet code, I am going to mark the issue closed.

**Comment by msaeltzer** [comment]
This seems to be happening again. It is an intermittent error. If I include an exception handler that retries after 20 seconds it runs longer, but sooner or later it crashes.
