### ISSUE TITLE
Invalid time error using get_followers

### ISSUE THREAD

**Issue by jantleon** [ropensci/rtweet#396]
Hi, I'm trying to get someone's followers. There are more than 75000 followers, so I have to use the parameter retryonratelimit. 

I'm using this code:

vox <- lookup_users("vox_es")

vox <- get_followers(
  "vox_es", n = vox$followers_count, retryonratelimit = TRUE
)

But it returns this error:

Downloading [=========================================] 100%
75000 followers!
Waiting about 14.8 minutes for rate limit reset...
Waiting about -0.1 minutes for rate limit reset...
**Error in Sys.sleep(as.numeric(rl$reset, "secs") + 2) : 
  valor de 'time' no válido**

I've already tried CRAN and Github versions, and no one works. How could I solve that problem?

Cheers!

**Comment by llrs** [comment]
This got fixed in `get_friends` but not on `get_followers` as reported by a comment I overlook on #277

**Comment by hadley** [comment]
Now tracking in #510
