### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached

### ISSUE THREAD

**Issue by mahdijavid** [ropensci/rtweet#397]
when I try to use ' get_friends() ' functions I get this error:

Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [api.twitter.com] Resolving timed out after 10000 milliseconds

I ran it both on my local host(windows 10 - R x64 3.6.3) and Kaggle's R Kernel. I got same error.
I asked my friends to run it on their own laptop and they also got the same error.

and this is my code:

library('rtweet')
vignette("auth", package = "rtweet")
app_name <- "****************************"
consumer_key <- "****************************"
consumer_secret <- "****************************"
access_token_key <- "****************************"
access_token_secret <- "****************************"
token <- create_token(app_name, consumer_key, consumer_secret, access_token_key, access_token_secret )
token
path_to_token <- file.path(path.expand("~"), ".twitter_token.rds")
saveRDS(token, path_to_token)
env_var <- paste0("TWITTER_PAT=", path_to_token)
cat(env_var, file = file.path(path.expand("~"), ".Renviron"), 
    fill = TRUE, append = TRUE)

readRenviron("~/.Renviron")

fds <- get_friends("jack")

I would appreciate you if you help to to solve the issue :)

**Comment by Arf9999** [comment]
Your code says get_friends(), but your query is for get_followers().  Do both fail?

try this and give the result:

fds <- get_friends("jack", token = NULL)

**Comment by mahdijavid** [comment]
@Arf9999 
Hello, thanks for reply.
yes I have this problem for both.
and I tried your code, got the same error :/

**Comment by Arf9999** [comment]
What is the result of get_token()

**Comment by mahdijavid** [comment]
@Arf9999 
![image](https://user-images.githubusercontent.com/5354899/76398265-d305c580-6391-11ea-9ca6-8c6fedc298c2.png)

**Comment by Arf9999** [comment]
It seems like there is something funny with your app.

Try removing (or renaming - so that they aren't seen as .rds files) all the files named ".rtweet_token.rds" or similar from your home directory. Restart R, and load rtweet without creating a token. 

If you try to use get_friends or get_followers, you should get the default rtweet token - first use should open a browser authorisation page.

Please show the result of the function and get_token() after you've done that. If it works, it is likely that there is an issue with your app.

**Comment by mahdijavid** [comment]
I created another app with a simple name, 
I removed all the files you motioned,
and ran it again
same error :/

I am using "http://127.0.0.1:1410" as Callback URL. is it OK?!

**Comment by mahdijavid** [comment]
@Arf9999 
I created another app with a simple name,
I removed all the files you motioned,
and ran it again
same error :/

I am using "http://127.0.0.1:1410" as Callback URL. is it OK?!

**Comment by Arf9999** [comment]
Have you tried not creating an app at all?  rtweet has a default app that allows access to the functions that you're trying to use.

Are you getting the browser authorisation screen?

**Comment by mahdijavid** [comment]
@Arf9999 
yup, I tried it.

no I am not getting the browser authorization screen

**Comment by Arf9999** [comment]
what is the result of  `Sys.getenv("TWITTER_PAT")` ?

There is a similar issue closed here: https://github.com/ropensci/rtweet/issues/202#issuecomment-499334711

**Comment by mahdijavid** [comment]
@Arf9999 
this is what I get by running that code:

'/root/.rtweet_token3.rds'

**Comment by mahdijavid** [comment]
I also tried https://github.com/ropensci/rtweet/issues/202#issuecomment-499334711
still have the same error

**Comment by Arf9999** [comment]
Try creating a token by decompressing that file. 

token1 <- readRDS('/root/.rtweet_token3.rds')

Then try explicitly calling that token:

get_friends("jack", n=200, token = token1)

NB: Do all of this on a local machine, not a cloud instance.

**Comment by Lxhnnn** [comment]
Hello, how did you solve it in the end

**Comment by Unina** [comment]
I met the same problem. But the difference is when I run `Sys.getenv("TWITTER_PAT")`, I got this:

```
[1] ""
```

What should I do to continue?
I've tried everything I know, but it just doesn't work...

**Comment by llrs** [comment]
@Unina, I think you need to restart the R session after creating the token. If you are making few calls you can use `token <- get_token()`, to use the rtweet token
