### ISSUE TITLE
Scraping tweets from a specific user in a specific timeframe.

### ISSUE THREAD

**Issue by isadugd** [ropensci/rtweet#398]
I am working with package 'rtweet' to scrape tweets. 

Whilst I am able to successfully scrape the 3200 most recent tweets from a specific user, using the 'get_timeline' function:
tmlMLP <- get_timeline("MLP_officiel"), n = 3200)

I believe that 3200 is the maximum retrievable with that function. But I want to get tweets from 2015-2017 from that user. Is there a way to do this?

**Comment by hadley** [comment]
Now part of #510 — once that is resolved, you'll be able to the maximum number of tweets supported by the twitter API.
