### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle): gnutls_handshake() failed: An unexpected TLS packet was received.

### ISSUE THREAD

**Issue by hmeleiro** [ropensci/rtweet#400]
Hello,

I'm having an issue downloading all of the followers from a user. Since the process can last a fex days, I'm doing this from a Raspberry. The first aproach was to just use the retryonratelimit argument, but then an error came up and I though that maybe my raspberry could not handle a dataframe that big in R session enviroment (RAM limits maybe?).

So the next thing I tried was to get batches of 75k followers each call, write them in a csv file and continue the extraction using the next_cursor function.

This is the code I came up with:

```
library(rtweet)
library(readr)

source("01_auth.R") # This is the auth with my app API keys

# This is the users for which I want all of the followers
seed <- c("el_pais", "elmundoes", "abc_es", "lavanguardia", "elcorreo_com") 

# First I write a csv fil with just the column names
write_csv( data.frame("user_id", "seed") ,
           "data/marcomuestral.csv", 
           col_names = F, 
           append = F)

# Then I start iterating through the users
for (s in seed) {
  print(s)
  
  ## I look up how many followers the user has has?
  info <- lookup_users(s)
  N <- info$followers_count 
  n <- 0 # This is a counter to know when to stop
  
  
  # Don't stop ntil we dont have the number of followers as we know the user has...
  while (n < N) { 
    
    # The first time I dont use the page argument
    if (n == 0) {
      try({
        seed_flw <- get_followers(s,
                                  n = 75000, 
                                  retryonratelimit = T,
                                  verbose = F
        )
        
        page <- next_cursor(seed_flw) # store the next_cursor id for the next iteration
        
      }) 
      
    } else {
      
      try({
        
        seed_flw <- get_followers(s,
                                  n = 75000, 
                                  retryonratelimit = T, 
                                  verbose = F,
                                  page = page 
        )
        
        page <- next_cursor(seed_flw) # store the next_cursor id for the next iteration
        
        
      })
    }
    
    n <- n + nrow(seed_flw) # We add up the number of followers we have already
    
    
    if (nrow(seed_flw) > 0) {
      
      seed_flw$seed <- s
      
      # Write
      write_csv( seed_flw ,
                 "data/marcomuestral.csv", 
                 col_names = F, 
                 append = T)
    }
    
    print(as.character(n))
    
  }
  
}
``` 

But then this error came up:

`
Error in curl::curl_fetch_memory(url, handle = handle) : 
  gnutls_handshake() failed: An unexpected TLS packet was received.
Calls: lookup_users ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call
Ejecución interrumpida
`

Am I doing some thing wrong? What is this error telling me about? I'm no Curl advance user.

**Comment by hmeleiro** [comment]
By the way, another issuer I encounter was that using the `next_cursor()` function and the `page` argument retrieved duplicated user_id followers (a lot of them actually).

**Comment by llrs** [comment]
Hard to tell what was your initial error with retryonlimit. The second error is about connection interrupted or a packet was different than expected. Closing it, but if it happens again reopen or open a new issue
