### ISSUE TITLE
search_tweets issue with retryonratelimit

### ISSUE THREAD

**Issue by pq90** [ropensci/rtweet#401]
Hi!

I've been using the Twitter API with rtweet for a while, and in a new application, after several days downloading information with no problem, yesterday it stoped working properly. My queries are like this:

```
tweets_total = search_tweets('coronavirus OR "covid_19" OR ... OR #estadodealarma',  
n = 1000000, include_rts = FALSE, lang = "es", retryonratelimit = TRUE, since = fecha-1, until = fecha)
```

 where "fecha" is a proper date, and the query is not longer than 256 characters. A few days ago, it downloaded all the info, with many stops by the Twitter API restrictions, but it worked. However, since yesterday, it started donwloading the first part of tweets, and after the first restriction, it stoped. The error I get is the following:

```
Downloading [=========================================] 100%
retry on rate limit...
waiting about 12 minutes...
Warning: Rate limit exceeded - 88
Warning message:
Rate limit exceeded 
```

So I only get the first 18.000 tweets. 

Do you know how to solve this problem? I tried to change the token and Twitter account, but the problem remains the same. I'm using 0.7.0 rtweet version.

Thank you very much for your help!

**Comment by 7Sis** [comment]
Yeah, I second that request for help! Same issue...

**Comment by pq90** [comment]
It started working again after a couple of days. It looks like the IP was banned or something like that. The same tokens worked properly in different computers with different IPs.

**Comment by wtmoreland3** [comment]
I have started experiencing the same issue. I have been downloading data fairly regularly for the past 3-4 weeks and have been receiving the "Warning: Rate limit exceeded - 88" the past two days despite setting retryonratelimit = TRUE

**Comment by Chris-Julien** [comment]
Coming here to say this is my problem as well; I used search_tweets with no problem a few days ago (and got over a million!) but now when I try to scrape the same key word (ie. my code has not changed at all) it only returns a maximum of 18000. retryonratelimit is still set to TRUE. Thanks for any help with this!

**Comment by llrs** [comment]
This seems more about a Twitter problem that an rtweet bug. Without a reproducible example I cannot debug or try to fix this.
