### ISSUE TITLE
Twitter Developer Labs data and formats

### ISSUE THREAD

**Issue by andypiper** [ropensci/rtweet#402]
Hello from Twitter Developer Relations! I know you (Michael!) have already met with some of our team.

First of all: Thank You, for building on our API, and for supporting our developer communities! You, and many projects like this one, are among the reasons why Twitter data is much-appreciated by developers. We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around!

We're currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add support for Twitter Developer Labs to twitter-lite! We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI.

As we hope you know, we do list rtweet on our developer libraries page https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries and we would really love to continue to do so as you continue to help the R and research communities. Thank you all, again!

**Comment by llrs** [comment]
Hi Andy, great to see that Twitter Developers are here! I'm trying to keep up to date the package closing bugs, as Michael couldn't lately. Once those are fixed I hope to add more features including support for API v2 and Academic Research product. Certainly as a first step I will try to add Twitter Developer Labs. 
Closing the issue, but please write again if there is anything else you want to share.
