### ISSUE TITLE
this site can't be reached - 127.0.0.1 refused to connect.

### ISSUE THREAD

**Issue by as0205** [ropensci/rtweet#405]
<img width="1189" alt="Screen Shot 2020-03-27 at 3 00 11 PM" src="https://user-images.githubusercontent.com/59662506/77790783-ccd34280-703b-11ea-8579-c4a6966885ef.png">

**Comment by JamesVU2000** [comment]
Hello, I have rhis same problem

**Comment by llrs** [comment]
Sorry cannot reproduce. I assume this was while trying to set up your own token? If it doesn't work wait a little and try again
