### ISSUE TITLE
get_timeline and rate limit

### ISSUE THREAD

**Issue by YvonneSch** [ropensci/rtweet#406]
Dear crowd intelligence,

first of all: thank you for the continuous support and help! As a person just being thrown into RStudio and working on a big project, the answers provided in other threads are always a big help! 
I am currently working on a project that compares the happiness (measured by positive linguistic expressions) of Christian and Atheist twitter users, assuming that followers of e.g. the pope are more religious.

### What has been done
- Created twitter token
- List of Atheist and Christian figures 
- Retrieve followers of figures by means of a loop
- Filter out protected accounts and only 'English' language
- Filter for geo location in the US

### Problem

Comparable to issue #266 and #109: I have a large amount of users, thus the Error 'Rate limit exceeded - 88' pops up.

### Reproduce the problem

``` r
#attempt 1: retrieve timelines normally
atheist_tmls <- get_timeline(atheist_data_f$user_id, n = 10, check=FALSE, retryonratelimit = TRUE)
#problem: 'Warning: Rate limit exceeded 88 (this has to do with API limits)

#attempt 2: function to wrap get_timeline for any amount users
#solution presented in issue #266 
get_timeline_unlimited <- function(users, n){
  
  if (length(users) ==0){
    return(NULL)
  }
  
  rl <- rate_limit(query = "get_timeline")
  
  if (length(users) <= rl$remaining){
    print(glue("Getting data for {length(users)} users"))
    tweets <- get_timeline(users, n, check = FALSE)  
  }else{
    
    if (rl$remaining > 0){
      users_first <- users[1:rl$remaining]
      users_rest <- users[-(1:rl$remaining)]
      print(glue("Getting data for {length(users_first)} users"))
      tweets_first <- get_timeline(users_first, n, check = FALSE)
      rl <- rate_limit(query = "get_timeline")
    }else{
      tweets_first <- NULL
      users_rest <- users
    }
    wait <- rl$reset + 0.1
    print(glue("Waiting for {round(wait,2)} minutes"))
    Sys.sleep(wait * 60)
    
    tweets_rest <- get_timeline_unlimited(users_rest, n)  
    tweets <- bind_rows(tweets_first, tweets_rest)
  }
  return(tweets)
}
#produces no error messages, yet does NOT return a new dataframe as expected..

#attempt 3: function to avoid time limit
#solution presented in issue #109 
## initialize params and data obj for the loop
#n <- length(users)
#data <- vector("list", n)
n <- length(atheist_data_f$user_id)
atheist_tmls <- vector("list", n)
## assuming you have one token saved as environment variable
## then that's the token you'll want to make checks to rate limit
token <- get_tokens()

## execute for loop
for (i in seq_along(atheist_data_f)) {
  atheist_tmls[[i]] <- get_timeline(atheist_data_f$user_id[i], n = 100)
  rl <- rate_limit(token, "statuses/user_timeline")
  ## if rate limit exhausted, then wait to rate limit reset
  if (rl$remaining == 0L) {
    Sys.sleep(as.numeric(rl$reset, "secs"))
  }
}

#no warning (if session terminated before), but: produces complicated 'Large List' instead of dataframe I can work with
```
### What is needed? 
A solution to either 

- find a new fix for the 'standard' version of the code (attempt 1)
- adapt the loop (attempt 2) to produce a new dataframe with the timelines 
- Produce a dataframe rather than a list (attempt 3)

### rtweet version

[1] ‘0.7.0’

### Session info

R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252 
[2] LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] rtweet_0.7.0

loaded via a namespace (and not attached):
 [1] fansi_0.4.1      crayon_1.3.4     assertthat_0.2.1
 [4] R6_2.4.1         lifecycle_0.2.0  jsonlite_1.6.1  
 [7] magrittr_1.5     pillar_1.4.3     httr_1.4.1      
[10] rlang_0.4.5      cli_2.0.2        curl_4.3        
[13] rstudioapi_0.11  vctrs_0.2.4      ellipsis_0.3.0  
[16] tools_3.6.2      glue_1.3.2       compiler_3.6.2  
[19] pkgconfig_2.0.3  askpass_1.1      openssl_1.4.1   
[22] tibble_3.0.0    

### Token

<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> rstats[...]
  key:    uS00s[...]
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret

**Comment by NataliaUmansky** [comment]
You should be able to make the list into a dataframe with 

`df <- do_call_rbind(atheist_tml)`

**Comment by YvonneSch** [comment]
@NataliaUmansky Thank you very much, that indeed was the little detail resolving the entire issue!
