### ISSUE TITLE
Need basic description of common data structures

### ISSUE THREAD

**Issue by hadley** [ropensci/rtweet#41]
I assume there is a common data structure based on the motivation for this package, but it isn't documented in the readme (or in the vignettes that I skimmed)

**Comment by hadley** [comment]
To that end, I'd recommend a `README.Rmd` that actually shows some example results. It would also be useful to see how the output of one function can be used as the input for another.

**Comment by mkearney** [comment]
Agreed. I've been hesitant to display actual results for sake of privacy, but I can either generate fake data or, and this is prob the best solution, I could use data from public figures and not print results for misc. followers.

**Comment by mkearney** [comment]
Thanks for the feedback!!

**Comment by hadley** [comment]
I think is this basically done — the common data structure is the data frame 😄
