### ISSUE TITLE
Error in authentication token 

### ISSUE THREAD

**Issue by DavidPozo91** [ropensci/rtweet#410]
I try to uses rtweet comand, but, when I applied a simple search like this:
rt <- search_tweets("rstat", n = 180, include_rts = FALSE)
The console display the next message:

"Error: Not a valid access token".

I uses this codes:

appname <- "xx"
key <- "xx"
secret_key <- "x"
token <- "xx"
token_secret<- "xxx"
tk<-create_token( app = appname, consumer_key = key,
                        consumer_secret = secret_key,
                        access_token = token,
                        access_secret = token_secret )

I installed the devtools::install_github("mkearney/rtweet"), but the same message appears.

**Comment by PriyaShaji** [comment]
I am having exactly same issue, any help is appreciated to resolve it.

**Comment by DavidPozo91** [comment]
I soluve the problem. Firts read this article https://rtweet.info/articles/auth.html. You need a Browser-based authentication. Next, Try this code: 

token <- create_token(
  app = "scraper_tw",
  consumer_key = "XXX",
  consumer_secret = "XXX")
token

Finally, the browser open a window and ask if you autorhizate to use de twitter api.

**Comment by PriyaShaji** [comment]
Hi, Thankyou for the reply. So, I was able to run the program in the r-console. But it was throwing `Error: Not a valid access token` when I was rendering Rmarkdown file for the same. I tried several ways of solving but the following worked in my case:

Step 1) Get the api key, api secret key, access token, access token secret. I got all these values from my twitter developer application page. I did not use R code to get/create the token.

Step 2)After that I ran following R code:

 ```{r }
##------- store api keys (these are fake example values; replace with your own keys)

library(rtweet)

api_key <- "aaa"
api_secret_key <- "bbb"
access_token <- "ccc"
access_token_secret <- "ddd"

```
```{r }
##-------- check to see if the token is loaded

get_token()  ## this will show your oath endpoint information and oath app information i.e. api key and secret key
```
Step 3) In this final step you can run your ` search_tweets()` function.

Note: This method was successful in rendering RMarkdown file and did not throw any error.
