### ISSUE TITLE
Search Tweets: not all hashtags and mentions are extracted

### ISSUE THREAD

**Issue by cgeroli** [ropensci/rtweet#412]
### Problem
When running functions such as get_timeline() and search_tweets(), or even with sandbox functions search_last30(), I get a dataframe with 90 columns. However the information contained in "hashtags" and "mentions_user_id" columns is only partial: not all hashtags present in a tweet appear in the corresponding column and not all Twitter accounts mentioned in the tweet appear in "mentions_user_id".

### Expected behavior
The information I expected to find in these columns was:
- "hashtags": all hashtags present in the tweet
- "mentions_user_id": the user_id of all twitter accounts mentioned in the corresponding tweet

### Reproduce the problem
The problem is that sometimes the "hashtags" column is evaluated to NA, but when I checked the original tweet directly from Twitter I could see that some hashtags were present. Also, sometimes it reports only 2-3 hashtags even if in the original tweet there were more. As I said, this doesn't happen all the time, sometimes the list of hashtags is complete, sometimes not.

The same happens for "mentions_user_id" (and of course, "mentions_screen_name"): not all Twitter users mentioned in the tweet (@) are extracted.

I'm not sure this is a bug, maybe is it because I'm using the free APIs (standard and sandbox)?

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
0.7.0
```

**Comment by nfhavey** [comment]
Hey there,

I'm pretty sure both of those results are restricted to the Premium APIs.

**Comment by hadley** [comment]
I think this is likely to be fixed now, thanks to the recent refactorings. If not, as @nfhavey says, it's likely to be a limitation of the underlying twitter API, not rtweet.
