### ISSUE TITLE
Iterate backwards: "get_timeline"

### ISSUE THREAD

**Issue by mstefan-git** [ropensci/rtweet#419]
Say you want to download all of a user's tweets since a specific date.  Following up on #147 and #200, I tried to **iterate backwards** through time using the **"max_id"**-argument in the **"get_timeline()"**-function.

Here is a MWE which should do exactly that for all of Donald Trump's tweets since January 1, 2017:

library(bit64)
library(rtweet) 
library(tidyverse) 

target <- "2017-01-01"
target <- paste(target, "00:00:00")
target <- as.POSIXct(target)

batches <- vector(mode="list", length=0)  
earliest <- Sys.time()                    
new_max = NULL
                            
while(target < earliest){                                    
      batch <- get_timeline('@realDonaldTrump', n=3200, max_id=new_max)  
      batches[[length(batches)+1]] <- batch                      
      earliest <- min(batch$created_at)                          
      old_min  <- min(as.integer64.character(batch$status_id))  
      new_max  <- as.character.integer64(old_min- 1)            
      print(earliest)                                            
}

data <- bind_rows(batches, .id = "column_label")

I tried this for other user accounts, too. Often times only the first batch appears to work. Thereafter, all other batches are identical and the code does not iterate backwards through time.

**Comment by Arf9999** [comment]
Using the standard twitter API, this simply won't work. The API will only deliver a maximum of 3200 tweets for get_timeline(). 
https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline
