### ISSUE TITLE
Error in curl_fetch_memory schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326)

### ISSUE THREAD

**Issue by western11** [ropensci/rtweet#423]
### Problem
I'm trying to get followers by id's using `get_followers()` with looping function (length = 161 id's)
``` r
fol_fol <- vector(mode = 'list', length = length(active_fol$screen_name))

for (i in seq_along(active_fol$screen_name)) {
  message("Getting followers for user #", i, "/161")
  fol_fol[[i]] <- get_followers(active_fol$screen_name[i], 
                                  n =1000, 
                                retryonratelimit = TRUE)

```
However, it always shows an error after several pull. it's usually between after pulling followers from 20-50 account. 

### Error output

``` r
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
```
**note:** the code doesn't always produces error like this, only after several follower pulls at random number (between 20-50 account. max i can get is after 71 account)

I have no idea how curl/schannel/TLS works, yet i tried to google it and find out maybe my curl/liburl are broken. or maybe some configuration on my developer app . but i follow this vignette to create developer app and Authorization methods based on Access token/secret method.
https://rtweet.info/articles/auth.html

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")

# > ‘0.7.0’
```

### Session info

``` r
## copy/paste output
sessionInfo()

> R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 10586)
```

### Token

``` r
## copy/paste output
rtweet::get_token()

>
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> Automated Twitter SNA
  key:    A5csjkdrS****************
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret
```

**Comment by llrs** [comment]
Probably this should be reported to curl. But if you provided a `traceback()` it might be more helpful. Closing now because the intermittent behavior will make it very hard to track it at the moment.
