### ISSUE TITLE
Cannot open the connection and cannot open file ".Renviron"

### ISSUE THREAD

**Issue by ortutt** [ropensci/rtweet#424]
### Expected behavior

Trying to open a connection to the Twitter API is unsuccessful, coming up with two errors: cannot open the connection and cannot open file ".Renviron": Permission denied

### Reproduce the problem

``` r
 token <- create_token(
   app = "covid19opposition",
   consumer_key = api_key,
   consumer_secret = api_secret_key,
   access_token = access_token,
   access_secret = access_token_secret)
```
Error in file(con, "w") : cannot open the connection
In addition: Warning message:
In file(con, "w") :
  cannot open file '/Users/or/.Renviron': Permission denied

### rtweet version

0.7.0

``` r
## copy/paste output
packageVersion("rtweet")
```

### Session info

R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.7.0

loaded via a namespace (and not attached):
[1] httr_1.4.1     compiler_4.0.0 magrittr_1.5   R6_2.4.1       tools_4.0.0    jsonlite_1.6.1
``` r
## copy/paste output
sessionInfo()
```

### Token

NA

**Comment by llrs** [comment]
Do you have rights to edit .Renviron file? do you have internet connection?
