### ISSUE TITLE
retweet with a comment

### ISSUE THREAD

**Issue by luisotavio88** [ropensci/rtweet#426]
Hi,

I am using **post_tweet** function to retweet a status, But I could not find how to retweet a status adding my comments. 

Is it possible?

Thanks. 

Luis Otavio

**Comment by jcrodriguez1989** [comment]
+1
I would also love to get this new feature.
Some workarounds:
https://github.com/tweepy/tweepy/issues/618
https://stackoverflow.com/questions/29680965/how-do-i-properly-retweet-with-a-comment-via-twitters-api

thanks!

**Comment by Arf9999** [comment]
You can comment on a tweet by including the URL of the original tweet in the text.
