### ISSUE TITLE
Search_fullarchive stopped getting Premium tweets after 10 requests

### ISSUE THREAD

**Issue by shreya2105** [ropensci/rtweet#429]
### Problem

Search_fullarchive stopped getting Premium tweets after 10 requests 

### Expected behavior
Should have allowed to scrape tweets in multiples of 500. After 10 requests, the search result stopped getting any results, even though I had signed up for 250 requests for a month, out of which 79 requests have been exhausted, and of this only 10 got desired results, rest of them fetched nothing. 

### Reproduce the problem
``` r
##token = rtweet::create_token("***,"abc", "abcd", "abcde")
##tweet <- search_fullarchive("("#beyonce") (lang:en OR lang:hi)", n = 500, fromDate = "201911250000", toDate = "201911120000", env_name = "***", safedir = NULL, parse = TRUE, token = token) 
```
### rtweet version

``` r
packageVersion("rtweet") --rtweet_0.7.0
```

###ERROR

bad restore file magic number (file may be corrupted) -- no data loaded

**Comment by llrs** [comment]
This should be fixed once #375 gets merged. Closing it now.
