### ISSUE TITLE
Language argument "lang=" doesn't seem to work with get_timelines

### ISSUE THREAD

**Issue by mfuoli** [ropensci/rtweet#430]
### Problem

The language argument doesn't seem to work with the command get_timelines. When I specify English for the language filter, for example, I still get examples in other languages.

### Reproduce the problem

Below is an example of a simple query which retrieves tweets in English and Spanish, even though I specify English as the target language.

``` r
## insert code here
LATAM <- get_timelines("LATAMAirlines", n = 500, lang = "en") 
```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
```

### Session info

``` r
## copy/paste output
sessionInfo()
```

### Token

``` r
## copy/paste output
rtweet::get_token()
```

**Comment by hadley** [comment]
I don't see any evidence that this is supported by the twitter API, so I think this is a case of #470.
