### ISSUE TITLE
rtweet.info is down

### ISSUE THREAD

**Issue by jeroen** [ropensci/rtweet#435]
If there are no plans to get it backup, perhaps update the links to the official ropensci docs: http://docs.ropensci.org/rtweet

**Comment by wahyudinnasrulloh** [comment]
Yes, i on my way to learn rtweet but unfortunately, it's down

**Comment by mrmvergeer** [comment]
in the mean time of the site being offline, you could check the internet archive version: https://web.archive.org/web/*/rtweet.info

**Comment by jeroen** [comment]
The same docs are available at http://docs.ropensci.org/rtweet
