### ISSUE TITLE
lookup_friendships stops collecting info

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [ropensci/rtweet#436]
I am using the function **lookup_friendships()**  with a list of more than 500 pairs of users.
It stops collecting the info after 180 pairs. I guess I need to configure the **retryOnLimit** somewhere.. can you please help?

**Comment by Arf9999** [comment]
There is no retryonratelimit option for that function call to the API. 

You'll need to create your own by looping and using the ratelimits() function.

**Comment by Arf9999** [comment]
There is no retryonratelimit option for that function call to the API. 

You'll need to create your own loop to manage the ratelimiting.

You can check the ratelimits for your token by calling ratelimits()

**Comment by MAGALLANESJoseManuel** [comment]
> There is no retryonratelimit option for that function call to the API.
> 
> You'll need to create your own by looping and using the ratelimits() function.

Do you an example on the use of ratelimits() function?

**Comment by Arf9999** [comment]
If you use this to control a loop:

`rl <- rtweet::rate_limit( query = "lookup_friendships")`

It'll give you the option to see how many requests remain until ratelimit is reached. Max is 15, Each request will surface 12 pairs. So you'll need to divide your list of accounts by (15 * 12 = 180)

It also lets you know when the rate limit will be reset, so you can pause between loops:

`sys.Sleep(as.numeric(rl[1, "reset"] *60)`

**Comment by hadley** [comment]
Now tracking in #510
