### ISSUE TITLE
Sandbox: use of search_30day & search_fullarchive

### ISSUE THREAD

**Issue by gboura** [ropensci/rtweet#437]
I have been trying to make requests using the search_30day and search_fullarchive functions. I have not paid for the Premium package, however I have set up a development account and I can use Sandbox. When I try to make a request using the search_30day and search_fullarchive functions, I get the following error:

"Warning: list(message = "Forbidden: Authentication succeeded but account is not authorized to access this resource.", sent = "2020-08-03T16:53:59+00:00", transactionId = "XXXX")"

Please note that I specified the right token and dev environment name. I also set n=100, so as to be in line with the maximum number of tweets that can be returned using sandbox. Any ideas why this issue comes up? Would I need to pay for the Premium package to use these functions or I could use them just with the sandbox package?

For reference, I tried these two requests:

`rt <- search_30day("update OR disruption from:FirstinGlasgow", n=100, env_name = "development", safedir = NULL, parse = TRUE, toDate = "202008030000", token = mytoken)`

`rt <- search_fullarchive("update OR disruption from:FirstinGlasgow", n=100, env_name = "development", safedir = NULL, parse = TRUE ,fromDate = "201301010000", toDate = "201302010000", token = mytoken)`

Thanks!

**Comment by jouunas** [comment]
I’m currently experiencing the same issue. Have you been able to solve the problem?

**Comment by natesheehan** [comment]
You will defiantly need permission (e.g. bank card details) for ```search_fullarchive```. 

Unsure RE ```search_30day``` as it is a free tool, but I am guessing if your ```token``` and ```env_name``` are correct then it will probably also need bank permissions.
