### ISSUE TITLE
Search_fullarchive doesn't support query longer than 500 characters

### ISSUE THREAD

**Issue by syumet** [ropensci/rtweet#441]
### Problem

`Search_fullarchive` doesn't support query longer than 500 characters.

### Expected behavior

According to [premium spec](https://developer.twitter.com/en/pricing/search-fullarchive), `Search_fullarchive` should support queries that up to 1024 characters.

### Reproduce the problem

``` r
## sorry that I wouldn't be able to provide the query here
> nchar(query)
[1] 927
> foo <- search_fullarchive(q = query, n = 100, fromDate=201911010000, toDate = 201911300000, env_name = prod)
tweets/search/fullarchive/.Primitive("prod") ***Error: q cannot exceed 500 characters.
```

### rtweet version

``` r
> packageVersion("rtweet")
[1] ‘0.7.0’
```

**Comment by llrs** [comment]
Not sure how to test this as I don't have a premium API access. Could you provide the `backtrace()` to see where is the source of the error?

**Comment by syumet** [comment]
https://github.com/ropensci/rtweet/blob/master/R/search_tweets.R line 364

**Comment by hadley** [comment]
I removed this error during a refactoring (since `TWIT_get()` will now forwarded the twitter error), so this is now fixed 😄
