### ISSUE TITLE
I want to search tweets of a specific list , I was able to, but now I can't. has the instructions changed?

### ISSUE THREAD

**Issue by mmogit11** [ropensci/rtweet#444]
I used to search lists like this:

`search_tweets("list:105150333")
`
but now when I do that, I get a data frame with 0 rows and 0 columns
has anything changed and I should write something else in search_tweets() function
or searching in lists contents has been banned altogether?

thanks in advanced

**Comment by llrs** [comment]
Cannot reproduce. Maybe you reached your API calls limits, or your token changed/was no longer working?
