### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by hg-wells** [ropensci/rtweet#447]
Hi,

I've searched for this but I could not find it anywhere, I hope this is pertinent and I apologise if not. 

Are wildcards accepted by search_tweets? 

For example, can we use the star symbol as a wildcard to search on all words that contain the letters entered (e.g. "mammo*" would find "mammogram" OR "mammography" OR "mammoplasty")?

Thank you

**Comment by Arf9999** [comment]
No. But you could just search for "mammo" and you'll get the same results.

You'll also get results with "mammon", and "mammoths" though.

**Comment by hg-wells** [comment]
Thanks for your reply.

I might be wrong, but I think the latter is not correct (when I search for
"mammo" I only get "mammo", nothing more).

**Comment by Arf9999** [comment]
That's weird. I usually have the opposite issue (I get unwanted versions of a character string which i need to filter). You do appear to be right, though - possibly something has changed from Twitter's side. 

In your case you may need to build a search string accordingly:

`search_tweets("'mammogram' OR 'mammography' OR 'mammoplasty'")`

**Comment by hg-wells** [comment]
Thanks, yes it seems to me as well that I would need to build a search
string including all words.
