### ISSUE TITLE
lookup_users returns tweet not user info

### ISSUE THREAD

**Issue by soroosj** [ropensci/rtweet#455]
Hello

When I use the lookup_users function, I anticipated extracting Twitter user information such as number of followers, number following, etc.   However the output looks like attributes of most recent tweet.  Apologies if missing anything obvious.

glimpse(lookup_users("soroosj"))

Rows: 1
Columns: 90
$ user_id                 <chr> "32776890"
$ status_id               <chr> "1322564688962592771"
$ created_at              <dttm> 2020-10-31 15:42:48
$ screen_name             <chr> "soroosj"
$ text                    <chr> "@pp"
$ source                  <chr> "Twitterrific for iOS"
$ display_text_width      <int> NA
$ reply_to_status_id      <lgl> NA
$ reply_to_user_id        <chr> "12787712"
$ reply_to_screen_name    <chr> "pp"
$ is_quote                <lgl> FALSE
$ is_retweet              <lgl> FALSE
$ favorite_count          <int> 0
$ retweet_count           <int> 0

**Comment by Arf9999** [comment]
There are 90 columns. User profile information is included. Look at columns 75-90

**Comment by soroosj** [comment]
Perfect.  Exactly what I needed, Andrew.  Thank you.
