### ISSUE TITLE
post_tweet hangs when posting media

### ISSUE THREAD

**Issue by neuwirthe** [ropensci/rtweet#460]
Im am using rtweet 0.7.0 with R 4.0.3 on MacOS 10.15.7 and habe an intermittent problem.
I am sending a sequence of tweets (20 up to 30).
This works nicely when the tweets only consist of text.
When I also send media (png files), post_tweet hangs after a few tweets.
The number is changing for different attempts.
When I stop code execution, I get

`Error in curl::curl_fetch_memory(url, handle = handle) : Operation was aborted by an application callback`

The I have to wait for quite some time (up to a few hours) before I can send tweets
with images again.

Am I hitting a limit of the Twitter API. Is there a way to avoid this problem?

**Comment by llrs** [comment]
Could you provide the code you use to send your sequence of tweets? Did you check your API limits? 
If you hit them it doesn't have to do with rtweet but how Twitter works, and nothing can be done on rtweet side.

**Comment by neuwirthe** [comment]
Without any change in my code it is working again. Perhaps some temporary resource limit in GutHub was the problem.
