### ISSUE TITLE
Authentication token shows authentication complete but r console says it is not a valid token 

### ISSUE THREAD

**Issue by j-anderson-sci-comm** [ropensci/rtweet#464]
Hi I'm a communication PhD student learning computational methods with r and while I've gotten rtweet to work before its having issues with the same token code as I've used before. When I create the authorization token it redirects me to a web page and shows "authorization complete", but when I try to use the rtweet package r console returns "Error: Not a valid access token". I haven't found this specific situation yet with other people but I have a feeling I'm making a very simple mistake here. Any help would be appreciated! My code is below:

library(tidyverse)
library(rtweet)
library(httpuv)

app_name <- "XXXXX"
api_key <- "XXXXX"
api_secret_key <- "XXXXX"
access_token <- "XXXXX"
access_secret_token <- "XXXXX"

CCS_token <- create_token(
  app = app_name, 
  consumer_key = api_key, 
  consumer_secret = api_secret_key)

CCS_token

CCS_Posters <- search_users("#carboncapture", n=200)

**Comment by llrs** [comment]
Did you check that the token retuned by `get_token()` is the same than the one you provided/created now? I found that sometimes it doesn't pick the right token. Perhaps you have another one that is no no longer valid.

**Comment by j-anderson-sci-comm** [comment]
> Did you check that the token retuned by `get_token()` is the same than the one you provided/created now? I found that sometimes it doesn't pick the right token. Perhaps you have another one that is no no longer valid.

I just checked and it's showing the correct token in the environment

**Comment by llrs** [comment]
And did you check on that you have the right permissions to read and that you didn't go over your `rate_limit`s?

**Comment by j-anderson-sci-comm** [comment]
> And did you check on that you have the right permissions to read and that you didn't go over your `rate_limit`s?

Yes- I just checked the permissions and those are right, and I haven't collected twitter data in well over a month so I don't think it would be a problem with rate_limit

**Comment by Arf9999** [comment]
Are you using this on a desktop or cloud instance? Getting auth via web is an issue on cloud based systems.

**Comment by j-anderson-sci-comm** [comment]
Do you mean the working directory? This is set to OneDrive

**Comment by j-anderson-sci-comm** [comment]
> Are you using this on a desktop or cloud instance? Getting auth via web is an issue on cloud based systems.

Do you mean the working directory? This is set to OneDrive currently

**Comment by Arf9999** [comment]
No, I mean your R instance, is it running locally (e.g. through RStudio desktop) or on a cloud instance (RStudio Server, Rstudio Cloud)?

**Comment by j-anderson-sci-comm** [comment]
> No, I mean your R instance, is it running locally (e.g. through RStudio desktop) or on a cloud instance (RStudio Server, Rstudio Cloud)?

It is on r desktop

**Comment by j-anderson-sci-comm** [comment]
I solved the issue by fixing the data collection syntax ("token = ccs_token") as it was not recognizing the correct token in the environment.

**Comment by llrs** [comment]
Glad you could solve it!
