### ISSUE TITLE
Token showing authorization complete, but rconsole returning "not a vlid access token"

### ISSUE THREAD

**Issue by j-anderson-sci-comm** [ropensci/rtweet#465]
Hi I'm a communication PhD student learning computational methods with r and while I've gotten rtweet to work before its having issues with the same token code as I've used before. When I create the authorization token it redirects me to a web page and shows "authorization complete", but when I try to use the rtweet package r console returns "Error: Not a valid access token". I haven't found this specific situation yet with other people but I have a feeling I'm making a very simple mistake here. Any help would be appreciated! My code is below:

library(tidyverse)
library(rtweet)
library(httpuv)

app_name <- "XXXXX"
api_key <- "XXXXX"
api_secret_key <- "XXXXX"
access_token <- "XXXXX"
access_secret_token <- "XXXXX"

CCS_token <- create_token(
  app = app_name, 
  consumer_key = api_key, 
  consumer_secret = api_secret_key)

CCS_token

CCS_Posters <- search_users("#carboncapture", n=200)

**Comment by llrs** [comment]
Isn't this the same as in #464?

**Comment by j-anderson-sci-comm** [comment]
> Isn't this the same as in #464?

It is! Github showed an error 404 when I posted so I thought it didn't post 464
