### ISSUE TITLE
lookup_users() not working for large lists?

### ISSUE THREAD

**Issue by ezgikurt** [ropensci/rtweet#466]
### Problem

Hi, I'm using lookup_users() to get the location and account created date for a large list of user-ids. I've obtained the list of user-ids without any problem using get_followers, they were all following one account. There are around 650k ids. 

The problem arose here. When I tried to go through this large list using lapply(), it produced lots of NULL values. I know Twitter doesn't have NULL values for account_created_at (unless there is some problem with the account). 

Indeed if I go and use lookup_users() individually for the user ids that gave me the NULL for account_created_at, I got the true value (trying a few different cases). They were not NULL. 

```r
x_list <- lapply(x_flw$user_id, function(x){a<- lookup_users(x); list(a$account_created_at, a$location)})
```

Then I tried to break this NULL fields into chunks (maybe it's running into some time-out error in the background?) and tried again, only to have some of them populated with true values, and some still NULL. Again I tried individual user ids that gave me the NULL values with lookup_users(). They gave me the true values.

```r
#missing:
mis_ind <- which(twitter1$dates=="") # I put all the dates in a dataframe before and identified the NULLs, I had transformed it before.

x_loc_list <- list()
l_list <- chunk(mis_ind, 50000)

for (i in 1:length(l_list)){
  users = x_flw$user_id[mis_ind[l_list[[i]][1]:l_list[[i]][2]]]
  tmp <- lapply(users, function(x){a<- lookup_users(x); list(a$account_created_at, a$location)})
  x_loc_list[[i]] <- tmp
}
```

The lists are pretty long and I'm not running into a problem if I do it for 1000 values. Haven't tried for 5000. Should I just do it for smaller chunks? 

Do you know what could be the problem? I also tried it on two different machines: An AWS server and an office computer with stable internet connection. The following info is from the office computer:

### rtweet version

``` r
packageVersion("rtweet")
0.7.0
```

### Session info

``` r
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 10240)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.7.0

loaded via a namespace (and not attached):
 [1] fansi_0.4.1      utf8_1.1.4       assertthat_0.2.1 crayon_1.3.4     R6_2.5.0         lifecycle_0.2.0  jsonlite_1.7.1  
 [8] magrittr_2.0.1   pillar_1.4.7     httr_1.4.2       cli_2.2.0        rlang_0.4.8      curl_4.3         rstudioapi_0.13 
[15] vctrs_0.3.5      ellipsis_0.3.1   tools_4.0.3      glue_1.4.2       compiler_4.0.3   askpass_1.1      pkgconfig_2.0.3 
[22] openssl_1.4.3    tibble_3.0.4
```

### Token

``` r
## copy/paste output
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> court_data
  key:    DAKBPdnvjTVkOon2JQzaDw6XD
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret```

**Comment by ezgikurt** [comment]
Ah okay @llrs makes sense, didn't know about the API limit. It hits it exactly at item 901 so it looks like that's what it is. 

Any way that I can make it wait whenever it hits the limit like using `retryonratelimit=TRUE` option in `get_followers()`? Or should I try to write to ad-hoc thing into the loop (check if it's NULL, if so wait for 15 minutes)? 

Sorry about the unclear code, here's a clearer example:

```r
cnn <- lookup_users("cnn")
x_flw <- get_followers(
  "cnn", n = 10, retryonratelimit = TRUE
)

x_list <- lapply(x_flw$user_id, function(x){a<- lookup_users(x); list(a$account_created_at, a$location)})

loc_info <- lapply(x_list, function(x){
  if (is.null(x[[2]])){
    ""
  } else {
    x[[2]]}
}) %>% unlist

date_info <- lapply(x_list, function(x){
  if (is.null(x[[1]])){
    ""
  } else {
    as.character(x[[1]])}
}) %>% unlist

twitter1 <- data.frame(dates= date_info, locations = loc_info)

#missing:
mis_ind <- which(twitter1$dates=="")

x_loc_list <- list()
l_list <- chunk(mis_ind, 50000)

for (i in 1:length(l_list)){
  users = x_flw$user_id[mis_ind[l_list[[i]][1]:l_list[[i]][2]]]
  tmp <- lapply(users, function(x){a<- lookup_users(x); list(a$account_created_at, a$location)})
  x_loc_list[[i]] <- tmp
}

```

**Comment by llrs** [comment]
Not sure there's a way to use `retryonlimits`, I think you won't be able. 
The best workaround is what you propose: every 900 calls, wait ~15 minutes and continue. Not sure if there is some other intelligent way to get around this using other endpoints. Good luck!

**Comment by ezgikurt** [comment]
Great, thanks a lot @llrs

**Comment by Arf9999** [comment]
> Not sure there's a way to use `retryonlimits`, I think you won't be able.
> The best workaround is what you propose: every 900 calls, wait ~15 minutes and continue. Not sure if there is some other intelligent way to get around this using other endpoints. Good luck!

Rather than simply use a pause of 15 minutes, I'd recommend that you check the remaining limits on the specific token by using `ratelimits(lookup_users)`
It will give feedback on the number of calls remaining, and the time to reset of the rate limit.

**Comment by llrs** [comment]
Oh, nice! `rate_limits("lookup_users")` works great

**Comment by ezgikurt** [comment]
> > Not sure there's a way to use `retryonlimits`, I think you won't be able.
> > The best workaround is what you propose: every 900 calls, wait ~15 minutes and continue. Not sure if there is some other intelligent way to get around this using other endpoints. Good luck!
> 
> Rather than simply use a pause of 15 minutes, I'd recommend that you check the remaining limits on the specific token by using `rate_limits("lookup_users")`
> It will give feedback on the number of calls remaining, and the time to reset of the rate limit.

Thanks for the reply! I ended up using this in conjunction with [this answer](https://github.com/ropensci/rtweet/issues/266#issuecomment-537084036).. Code still running, but trials worked so I'm hopeful.
