### ISSUE TITLE
Raise error on unsupported parameters

### ISSUE THREAD

**Issue by llrs** [ropensci/rtweet#470]
From [here](https://recology.info/2020/12/api-client-params/) it seems it would be better to alert users of unused arguments. Not sure if this could be made more general or a table/list would be nice (as a summary or cheatsheet): 

> ```r
> library(rtweet)
> search_tweets("hillaryclinton", n = 3, foo = "bar")
> ```
> Works just fine even though foo is absolutely not a parameter supported by the Twitter API. They must ignore parameters they don’t support. This is same behavior as the GitHub API we saw above.
> 
> In the case of Twitter and GitHub one might want to raise errors on unsupported parameters client side in rtweet to avoid any use confusion of parameters being silently dropped.

**Comment by hadley** [comment]
This is going to be very difficult to do, unless twitter provides a machine readable API description.
