### ISSUE TITLE
Switch to app dir for saving token?

### ISSUE THREAD

**Issue by maelle** [ropensci/rtweet#479]
:wave: here! In meetupr dev version following [Jenny Bryan's advice](https://github.com/rladies/meetupr/pull/84/files/6017235edf214a69c2c0af579ed4efa5c015ed2c#diff-9c940e8ad2b7bc4c26ec3da57b94bc00e73e2166cfed689da51a4c59bcc0a310) the token is now by default stored in an app dir (users can still choose another location, that they then need to enter as parameter to an authentication function, so nothing lives in .Renviron). It is a more conventional way to store a secret.

Of course for rtweet this would be a breaking change but I thought I'd mention this idea @llrs.

**Comment by llrs** [comment]
Yeah, updating the package but do not introducing break changes is the most challenging tasks I face. I would probably need to support both types for some time and later move to a single folder (Although I don't like to add another dependency). 
Improving the token handling will definitely happen. For instances, I have troubles knowing with which account I'll be tweeting, from my personal account or a bot I created.

**Comment by maelle** [comment]
In tidytags we're seeing an issue with the token on Windows, where rtweet tries to load it from "C:UsersrunneradminDocuments/.rtweet_token.rds" after a dummy token was created in https://github.com/bretsw/tidytags/blob/6de4cc1c0dfb4bcca388ee20bc3d0a9cd4705c58/tests/testthat/setup-tidytags.R#L17 (I did some printing in https://github.com/bretsw/tidytags/runs/1941838960?check_suite_focus=true#step:9:242) At least with rappdirs the OS specific part would be handled by rappdirs so less such errors hopefully?

I am reminded of https://ropensci.org/blog/2019/04/30/qualtrics-relaunch/ reg breaking changes :-)

**Comment by llrs** [comment]
Indeed, good point. 
Yes, I reread the post before starting with rtweet. reg breaking changes, that happened after qualtRics package was off CRAN (and probably have much less users).

Note to myself: I when the token via `.Renviron` & `~/.rtweet_token.rds` to the folder of the application. This would avoid a breaking change and help move to the new location to current users (who updated).

**Comment by hadley** [comment]
Now done; this isn't a breaking change because this is just where the token is cached, not configured.

**Comment by maelle** [comment]
@bretsw in case you're brave enough to switch to rtweet dev version for a bit :slightly_smiling_face:
