### ISSUE TITLE
Chunked media tests are rather slow

### ISSUE THREAD

**Issue by hadley** [ropensci/rtweet#490]
They take about 60s on my computer, which is particularly frustrating because they're the first test.  Do you think it would be possible to test it with smaller images? It would also be useful to generate locally somehow, to avoid having to download a large file and then immediately re-upload it elsewhere. 

If you want to exercise the chunked path without using such large files, one option would be to provide a `chunk_size` argument that could be set to a smaller size for test.

**Comment by llrs** [comment]
Yes those test aren't fast. Haven't decided yet what to do, whether store them locally and add them to .Rbuildignore for tests or generate new plots with ggplot2.

**Comment by hadley** [comment]
I don't think storing >20 MB of files in a package just for these tests would be a good idea either.

**Comment by hadley** [comment]
I'll take a swing at this.
