### ISSUE TITLE
Scrape a thread?

### ISSUE THREAD

**Issue by taleac** [ropensci/rtweet#493]
Hello! Is it possible to scrape an entire thread (i.e., original post, and all nested replies)?

Thanks so much!

**Comment by llrs** [comment]
Hi, there's a development feature (that might change till next release) that enables this.
Basically you'll need to `tweet_threading(lookup_statuses('1084143184664510470'))`

**Comment by taleac** [comment]
![image](https://user-images.githubusercontent.com/70964783/109347761-a4525a80-7841-11eb-992f-a2ad5458bad7.png)
Hello - unfortunately, this worked only once. Now I get an error and I cannot fix it.

**Comment by llrs** [comment]
Ok, we'll look into it. Thanks for reporting it back

**Comment by llrs** [comment]
The user id 1364705060245172234 does not exists. So it cannot look up the threads of an nonexistent user. Please, next time copy and paste the code, having to manually write the code makes it harder for me to help you.
