### ISSUE TITLE
Handle user consistently

### ISSUE THREAD

**Issue by hadley** [ropensci/rtweet#502]
* All functions should allow either username or id (as string or double)
* One function to check if input is ok
* Helper for adding appropriate parameter to API call
* Determine if `as_screenname` and `as_userid` can be eliminated

**Comment by hadley** [comment]
Consider use of bit64

**Comment by Arf9999** [comment]
The `as_screenname` and `as_userid` functions may be required for edge cases:

It is possible to have an all numeric user name e.g. @123456
![image](https://user-images.githubusercontent.com/36820513/109385043-9233f300-78f9-11eb-8071-fd2a666b2a74.png)

**Comment by hadley** [comment]
Ah I'd wondered about that. Still that only implies the need for `as_screenname()`.  I think the logic could be something like this:

```R
user_type <- function(x, arg_name = "user") {
  if (is.numeric(x)) {
    "user_id"
  } else if (is.character(x)) {
    if (inherits(x, "screenname")) {
      # needed for purely numeric screen names
      "screen_name"
    } else if (all(grepl("^[0-9]+$", x))) {
      "user_id"
    } else {
      "screen_name"
    }
  } else {
    stop("`", arg_name, "` must be a screen name or user id", call. = FALSE)
  }
}
```
