### ISSUE TITLE
Consistent pagination interface

### ISSUE THREAD

**Issue by hadley** [ropensci/rtweet#510]
## Cursors

Add `next_cursor` attribute to outptut (of single inputs). Should pass `cursor, `retryratelimit` and `verbose` arguments on to `TWIT_paginate_cursor()`. 

* [x] `direct_messages()`
* [x] `get_followers()`
* [x] `get_friends()`
* [x] `lists_members()`
* [x] `lists_memberships()`
* [x] `lists_subscribers()`
* [x] `lists_subscriptions()`

## `max_id`

Add `max_id` attribute to outptut (of single inputs). Should pass `since_id`, `max_id`, `retryratelimit` and `verbose` on `TWIT_paginate_max_id()`.

* [x] `get_favorites()`
* [x] `get_my_timeline()`
* [x] `get_timeline()`
* [x] `get_mentions()`
* [x] `lists_statuses()`
* [x] `search_tweets()`

## Other

* [ ] `search_users()` — uses `page` paramter
* [x] `lookup_users()` — `TWIT_paginate_chunked()`
* [x] `lookup_tweets()`  — `TWIT_paginate_chunked()`

**Comment by hadley** [comment]
Consider `sleep_on_rate_limit` instead of `retryratelimit`. Would need to deprecate functions already using `retryratelimit`.

**Comment by hadley** [comment]
@llrs do you have any thoughts on argument name? I think `sleep_on_rate_limit` is slightly easier to read and a more accurate description of what it does, but I don't feel that strongly about it. (But I do only want to make the change once, since it's a bunch of functions that need this as an argument.)

**Comment by hadley** [comment]
Common documentation in progress in #554

**Comment by llrs** [comment]
I think it might be slightly easier to understand wait_on_rate_limit, but it is still long. (wait_on_limit?)

**Comment by hadley** [comment]
Cursor plan:

* Add `rtweet_cursor`  attribute to result of `TWIT_paginate_cursor`
* Ensure parsing preserves/restores the attribute
* Re-work `next_cursor()` following `max_id()`/`since_id()`
* Ensure all functions have necessary arguments

**Comment by hadley** [comment]
I'm going to leave `my_friendships()` and `lookup_friendships()` as is as there doesn't appear to be any indication that they're actually used anywhere (e.g. https://github.com/search?l=R&q=my_friendships&type=Code).

**Comment by hadley** [comment]
I'm going to close now; `search_users()` uses its own unique pagination style so while we certainly could make consistent with everything else, I don't think it's particularly high priority.
