### ISSUE TITLE
Long running paginated queries should offer some way to save progress

### ISSUE THREAD

**Issue by hadley** [ropensci/rtweet#531]
e.g. https://github.com/ropensci/rtweet/issues/388

Maybe they could save interim results to a temporary directory, which is automatically deleted when the function returns successfully. If it fails, it would generate a message telling you how to recover the partial data.

**Comment by alexpghayes** [comment]
This is a consistent pain point for me, would really appreciate either support in `rtweet` itself or pointers to other API-calling code that handles this gracefully. In particular, imagine `get_followers()` for someone with 10 million followers, which after rate limits should take 10,000,000 followers * (1 minute / 5000 followers) = 2000 minutes.

**Comment by hadley** [comment]
You'll basically have to architect this in a way where you're capturing state to disk. I would suggest storing a list of things to do and a list of things that you've done. Then you loop until your to do list is done, saving both to disk at each iteration.
