### ISSUE TITLE
Same endopoint but different arguments and functions

### ISSUE THREAD

**Issue by llrs** [ropensci/rtweet#536]
`post_follow` and `post_friendship` call the same [endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/post-friendships-update) but have different arguments (to update a relationship).

`post_follow` should be split and provide only one function for each endpoint

**Comment by hadley** [comment]
Do you have a plan for what to name those functions?

**Comment by llrs** [comment]
We were discussing this on #480, following your idea possibly `friendship_update` and `friendship_create`, `friendship_destroy`, `mute_user`.
