### ISSUE TITLE
Remove home argument from get_timeline

### ISSUE THREAD

**Issue by hadley** [ropensci/rtweet#550]
Since according to https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-home_timeline, you can only get the home timeline for the authenticated user (i.e. `get_my_timeline()`)

**Comment by llrs** [comment]
The home argument changes the endpoint it is called:
`api <- if (home) "/1.1/statuses/home_timeline" else "/1.1/statuses/user_timeline"`
Perhaps it signals that it should be organized differently to better mimic Twitter API?

**Comment by hadley** [comment]
I think `home` makes sense in `get_timeline_user()` since `get_timeline()` and `get_my_timeline()` share a lot of code, so I'll deprecate it `get_timeline()` but otherwise leave it alone.
