### ISSUE TITLE
Use of negation term not working in premium search

### ISSUE THREAD

**Issue by silasprincipe** [ropensci/rtweet#561]
### Problem

Hi! I'm using the `search_fullarchive` function with a Research account. Everything is working, except that I need to search the following query:

"ocean decade" -is:retweet

That is, I have to use a negation term to avoid downloading retweets. However, when I try to do this I receive the following error

`Warning: list(message = "There were errors processing your request: Reference to invalid operator 'is:retweet'. Operator is not available in current product or product packaging. Please refer to complete available operator list at http://t.co/operators. (at position 20)", sent = "2021-04-07T13:36:53+00:00", transactionId = "0060d685008c9c46")`

I appreciate any help that you can give regarding this problem.

### Expected behavior

I expected that the search would work, as using this query on other platforms/the Twitter itself it works.

### Reproduce the problem

``` r
queries <- c('"ocean decade" -is:retweet')


ts <- search_fullarchive(
        q = queries,
        n = 10000,
        fromDate = "202007010000",
        toDate = "202103310000",
        env_name = "odresearch",
        safedir = "data/tweets_search",
        token = token
)
```

### rtweet version

``` r
> packageVersion("rtweet")
[1] ‘0.7.0’
```

### Session info

``` r
sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openssl_1.4.3 rtweet_0.7.0 

loaded via a namespace (and not attached):
 [1] fansi_0.4.2       prettyunits_1.1.1 assertthat_0.2.1  utf8_1.1.4        crayon_1.4.1      R6_2.5.0         
 [7] lifecycle_1.0.0   jsonlite_1.7.2    magrittr_2.0.1    pillar_1.5.0      httr_1.4.2        cli_2.3.1        
[13] rlang_0.4.10      progress_1.2.2    curl_4.3          rstudioapi_0.13   vctrs_0.3.6       ellipsis_0.3.1   
[19] tools_4.0.4       glue_1.4.2        hms_1.0.0         compiler_4.0.4    askpass_1.1       pkgconfig_2.0.3  
[25] tibble_3.0.6     
```

**Comment by llrs** [comment]
I don't have a premium API access, according to [Twitter's page](https://developer.twitter.com/en/docs/twitter-api/enterprise/rules-and-filtering/operators-by-product) it should work. 

Perhaps you can retrieve them without the operator and then filter by retweeted_status for now.

**Comment by silasprincipe** [comment]
@llrs yes, I was able to download without the negation term and filter using the retweeted_status. But according to Twitter it should work, so I was just wondering if it was something on my side or a bug...

But maybe something to verify in the future, as the negation term really speed-up the process.

Thanks for now!

**Comment by llrs** [comment]
A couple more of questions: Was this working previously? Are you sure this token has premium features? Could it be that you have more than one token? (check if in your home directory you have more than one rtweet_token file, they could be called rtweet_token.rds, rtweet_token2.rds, rtweet_token3...)

**Comment by igorbrigadir** [comment]
> I'm using the search_fullarchive function with a Research account.

rtweet is not the correct package to use if you have Academic Access `v2` - it's a different "fullarchive" endpoint.

rtweet calls the v1.1 Premium fullarchive API, https://developer.twitter.com/en/docs/twitter-api/premium/search-api/api-reference/premium-search 

Academic Access is for v2 full archive Search: https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-all a different API.

Here’s an R example of using Academic Access v2 endpoint: https://gist.github.com/schochastics/1ff42c0211916d73fc98ba8ad0dcb261 or as a package: https://github.com/cjbarrie/academictwitteR

Multiple tokens also do not work with Premium API, or with Academic Access, both are authenticated as an Application Only endpoint.

Hope that helps!

**Comment by silasprincipe** [comment]
@igorbrigadir many thanks for that! I was not aware that I should use another way for getting tweets through the Academic Access. I appreciate your help.

**Comment by llrs** [comment]
Thanks @igorbrigadir for stepping in. I missed this even if it was on the beginning of the question. There will be support for v2 API soon see #445.
