### ISSUE TITLE
About q argument of search_users() function

### ISSUE THREAD

**Issue by gulinan** [ropensci/rtweet#573]
Hi, 

I would like to ask whether `q` argument in `search_users()` function does a query over Twitter user profile or tweets. In the help menu it says "Query to be searched, used in **filtering relevant tweets** to return from Twitter's REST API". However, my experience shows that it does query over Twitter profile information searching for "word block" given in `q` argument and returns the latest tweets of that Twitter user. Thanks a lot.

**Comment by llrs** [comment]
Indeed, the description of what does the function is incorrect. This has been fixed on the development version of the package. Thanks for the note!

**Comment by gulinan** [comment]
One more question: I guess `ts_plot()` function takes `created_at` variable as an input argument to plot it on the horizontal axis. When I convert its type to Date and use `scale_x_date()` layer along with `ggplot2`, it throws "Error: Invalid input: date_trans works with objects of class Date only".  I would really appreciate your help to figure out how i can use `ts_plot()` with `scale_x_date()` layer. Here is a small reproducible example:

```{r}

library(rtweet)
library(ggplot2)

my_search <- search_tweets(q = "coffee", n = 100)

my_search %>%
   mutate(created_at = as.Date(created_at)) %>% 
   ts_plot("days") + 
   scale_x_date(position = "top")  #did not work
  
```

**Comment by llrs** [comment]
Probably because it is a transposed plot with coord_flip(), try with scale_y_date(), but I don't think ts_plot will be supported on next releases

**Comment by gulinan** [comment]
Hi, unfortunately, it did not work. Maybe, it would be better to use ggplot from scratch rather to use ts_plot for manipulating axes with date objects. Thanks a lot for your prompt replies!..

**Comment by llrs** [comment]
You might be aware of ts_data that is the function that prepares the data for the plot with ggplot2. Probably you can use it and then build your own plot with ggplot2:

```r
library(tidyverse)
library(rtweet)


my_search <- search_tweets(q = "coffee", n = 100)
my_search %>%
    ts_data() %>% 
    mutate() %>%
    ggplot() +
    ...
```

**Comment by gulinan** [comment]
Yes, it would be better!..Thanks a lot!..
