### ISSUE TITLE
get_timeline doesn't gather whole texts

### ISSUE THREAD

**Issue by respektive-reen** [ropensci/rtweet#575]
### Problem

During the last days I used the `get_timeline()` function, to gather some tweets from german twitter accounts. At first glance, all data looked fine, but during the validation process I noticed an issue in the 'text'-field. 

After 120 characters the text is automatically cutoff and adds a shortlink to the text field instead of showing all 280 characters in the text field.

### Expected behavior

Is there an option to gather all 280 characters in the text field?

### Reproduce the problem

``` r
## insert code here

mdb_Abercron <- get_timeline(user = "mvabercron", n=3200)


### rtweet version


rtweet_0.7.0.9000

**Comment by llrs** [comment]
Thanks for reporting, this seems like a problem extracting the data from the response. 
You seem to be using rtweet development version where this is an area were some major changes are happening (see #558 and #572). If this is important to you right now use the stable version on CRAN (rtweet version 0.7.0 correctly returns all the text). I hope to fix this on the development version soon but it might require some more time.

**Comment by respektive-reen** [comment]
Dear Lluís, your suggestion worked perfectly. Thank you for your quick response and your help!

**Comment by llrs** [comment]
Reopening, (as the issue isn't solved and) this also affects `lists_statuses` see https://github.com/ropensci/rtweet/issues/362#issuecomment-828222075

**Comment by llrs** [comment]
On the examples of Twitter API endpoint [statuses/home_timeline](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-home_timeline) shows a truncated text too. This is on purpose from the API. 

However, there are some reports of an undocumented parameter: `tweet_mode = "extended"`  which was [used previously](https://github.com/ropensci/rtweet/blob/af71a484e9cbbdfb739e2b4e684e84840f3ba1a9/R/timeline.R#L177)  and suggested as part of a PR https://github.com/ropensci/rtweet/issues/362#issuecomment-567549511 and from other tools that use it https://github.com/tweepy/tweepy/issues/1170. Using it the functions return the full text  (field changes from text to full_text) and `display_text_range` and `extended_entities`. This should make it easier to provide a more homogeneous report of the data.

**Comment by llrs** [comment]
This was handled on #572
