### ISSUE TITLE
Get Twitter poll data?

### ISSUE THREAD

**Issue by acircleda** [ropensci/rtweet#576]
I am wondering if there is a way to 1) recognize if a Tweet is a poll, and 2) access poll options and results.
There is some metadata info [here](https://developer.twitter.com/en/docs/twitter-api/enterprise/enrichments/overview/poll-metadata). when getting a tweet in `rtweet` it contains several of the entities listed (hashtags, URLs, symbols). It says you can get the options, expiration, and duration (but sadly, no results). It would be nice enough just to recognize which tweet is a poll.

**Comment by llrs** [comment]
There is a way to identify if there is a poll but only for some products. See more about this [here](https://developer.twitter.com/en/docs/twitter-api/enterprise/enrichments/overview/poll-metadata) as part of #572 I'm improving the support for these entities so it will eventually be possible.

I think that with twitter API v2 it will be possible to retrieve results as part of the [extensions ](https://developer.twitter.com/en/docs/twitter-api/expansions)that now can be requested.

**Comment by llrs** [comment]
This is will be possible in next release and already in the devel branch: if the endpoint allows to add `poll.fields` (look for `set_fields()`) and the `attachments.poll_ids` extension you will know the how long has it been active, end time of the poll, id, options and voting_status. Closing now.
