### ISSUE TITLE
get_friends() -- Error in Sys.sleep(as.numeric(rl$reset, "secs") + 2) :    invalid 'time' value

### ISSUE THREAD

**Issue by vwirtschafter** [ropensci/rtweet#579]
It looks like this bug has reemerged in the get_friends() function -- any suggestions for how to fix this?

friends <- get_friends(list_users, token=bearer_token(), retryonratelimit = TRUE)
1 friend networks collected!
2 friend networks collected!
3 friend networks collected!
4 friend networks collected!
5 friend networks collected!
6 friend networks collected!
7 friend networks collected!
8 friend networks collected!
9 friend networks collected!
10 friend networks collected!
11 friend networks collected!
Waiting about 10.7 minutes for rate limit reset...
Waiting about 0 minutes for rate limit reset...
Error in Sys.sleep(as.numeric(rl$reset, "secs") + 2) : 
  invalid 'time' value

**Comment by llrs** [comment]
Hi!
I'm not sure if you don't like the message about friends networks collected or the error with time. Which bug are you referring to?
Could you provide information about the version of the package you use?

**Comment by vwirtschafter** [comment]
The code appears to break when collecting friend networks after the rate limit resets. The number of feeds is far greater than 11. 

I am using this version: rtweet  0.7.0   2020-01-08 [1] CRAN (R 4.0.2)

Thanks so much for your assistance!

**Comment by llrs** [comment]
This should be already fixed on the next release; if you use the current github version you shouldn't get this error. 
Closing this report now but if you install the development version and find the same problem I'll reopen the issue.

**Comment by vwirtschafter** [comment]
Hmm, I just updated to the github version, and reran the code, now this is the error:

"Waiting about -0.1 minutes for rate limit reset..."

**Comment by llrs** [comment]
Ok, then I'll look into further into it. Thanks!

**Comment by llrs** [comment]
I can't find that error message and I think the rate limit error message hasn't changed since Hadley modified it. It might be that the new version was installed but the session not refreshed so the old rtweet was still being used. Closing for now
