### ISSUE TITLE
Replace suspended Twitter account with current account in vignettes, tests, etc.

### ISSUE THREAD

**Issue by ronblum** [ropensci/rtweet#580]
### Problem

Some of the vignettes, tests, etc., such as `vignettes/rtweet.Rmd`, use the Twitter handle `realDonaldTrump` as an example. However, this account has been permanently suspended, so another account should be considered. 

### Expected behavior

Examples use a current Twitter account.

### rtweet version

0.7.0

**Comment by llrs** [comment]
Yes, in some cases (if not all) that account has been already replaced on the dev version.

**Comment by llrs** [comment]
I think it was fixed on #606 and replaced by R related accounts
