### ISSUE TITLE
Unable to send private message to *some* users "Error: Twitter API failed [403]  * Cannot find specified user. (108)"

### ISSUE THREAD

**Issue by simonheb** [ropensci/rtweet#585]
My bot sends DMs using `post_massage()`. I use the current (working version from github). It works for 90% of users. In some cases it fails with 
```
Error : Twitter API failed [403]
 * Cannot find specified user. (108)
```
I don't want to share the user's ids publicly here, but I've noticed that these were always "long" ids like  `123776651554348****` but not all of them. To be specific: This line does not work:
```
post_message("test message", user="123776651554348****")
```
while it does work with different IDs

**Comment by simonheb** [comment]
Ok, I figured out that somewhere (probably during an involontary type-cast the id get's changed. I the above case `123776651554348***5` became  `123776651554348***4`, which does not exist

**Comment by llrs** [comment]
It seems you send some DM to many people with user_id. I had a patch to reduce API calls when user ids are used. Hope that #586 is useful.
