### ISSUE TITLE
How to check if the authenticating user is blocked

### ISSUE THREAD

**Issue by simonheb** [ropensci/rtweet#589]
With previous versions (latest version on cran) of `rtweet` I was able to implement a test of who has blocked the authenticating user.

The test simply proceeded by calling `lookup_users` for a set of candidates first as the authenticating users and then for a dummy user. The accounts who blocked the authenticating user would then be those who were returned in the second call, but not in the first call.

### Problem

In the latest version from github, `lookup_users` (so I guess the API does that) also returns full lines for users who have blocked the authenticating users.

### Expected behavior

There seems to be no API endpoint to list users who have blocked the authenticating users. But (as in the past) any command that would return NAs or nothing for users who have blocked the authenticating user would do the trick.

What worked in the past:
```
candidates<-c("username1","username2")
a<-lookup_users(candidates,token=token)
not_reached_user<-a$screen_name[is.na(a$text)]
b<-lookup_users(candidates,token=token_dummyuser)
not_reached_dummy<-b$creen_name[is.na(b$text)]
blocked<-setdiff(not_reached_user,not_reached_dummy)
```

### rtweet version
0.7.0.9000

Any leads on how to get the desired behavior back would be appreciated. `get_timeline` is not a good idea, because this gets messy if used for a large number of `candidates` (users)

**Comment by llrs** [comment]
Hi thanks for reporting this. But I'm a bit lost with your example and the description you make of the change between 0.7.0 and 0.7.0.9 . Where does the `not_reached_user` and the `not_reached_dummy` variables come from? 

There are some endpoints to [retrieve and block users](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/mute-block-report-users/api-reference/post-blocks-create). If needed I can add support to them.

**Comment by simonheb** [comment]
Sorry, I had made some changes to the code example that made it nonsensical that I have fixed now.

This is not about trying to block users, but to try and find out which users blocked the authenticating user. I don't think there's an API endpoint for that. However, I seem to have found a fix for that. The following code works to check out which users have blocked the authenticating user. The difference between the versions seems to have been that `lookup_users` does not return the text of the latest status anymore unless `parse=FALSE` is set, but I guess that's intentional.

```
candidates<-c("username1","username2")
a<-lookup_users(candidates,token=token,parse=FALSE)
not_reached_user<-a[[1]]$screen_name[is.na(a[[1]]$status$text)]
b<-lookup_users(candidates,token=dummy,parse=FALSE)
not_reached_dummy<-b[[1]]$screen_name[is.na(b[[1]]$status$text)]
print(setdiff(not_reached_user,not_reached_dummy))
```

**Comment by llrs** [comment]
Knowing if users has blocked anyone will be possible with the new [API v2](https://developer.twitter.com/en/docs/twitter-api/users/blocks/api-reference/get-users-blocking).

The status can be retrieved on the github version using:

```r
a <- lookup_users(candidates) 
tweets_data(a)
```
Important to have the `parse = TRUE`, I haven't tested what happens without it. 


This is part of the ongoing efforts to reduce the number of columns showed by default. This might change. Probably once there are some calls to API v2, I will explore what values are returned and reduce the default columns to show the same columns regardless if you call API v1 or v2.
