### ISSUE TITLE
Brainstorm: how avoid dead user IDs when exploring with get_friends()

### ISSUE THREAD

**Issue by alexpghayes** [ropensci/rtweet#596]
Found an edge case that is a bit of a PITA to deal with. Say you want to do something like BFS on the following graph. `get_friends()` will return links to "dead" nodes that you can't actually query later on. Is there anything we can do about this on the `rtweet` side or am I going to have to deal with this myself?

``` r
library(rtweet)

friends <- get_friends("SomervilleYIMBY")$ids

bad_friend <- "15089927"

bad_friend %in% friends
#> [1] TRUE

lookup_users(bad_friend)
#> Error: Twitter API failed [404]
#>  * No user matches for specified terms. (17)
```

<sup>Created on 2021-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by llrs** [comment]
The case described here seems similar to #592. I don't recall having seen any kind of user data returned that mentions if the user is blocked to you, private or deleted. This endpoint at least doesn't provide more than ids, so nothing rtweet can do unfortunately. 

However when run with: `lookup_users(friends)` that users disappears from the results, so one solution would be to always add a user you know it exists when using `lookup_users` and compare between the feed id and the returned data.frame:

```r
all_friends <- lookup_users(friends)
bad_friends <- setdiff(friends, all_friends$id_str)
```

**Comment by alexpghayes** [comment]
Thanks, didn't think there was anything `rtweet` could do but wanted to check.
