### ISSUE TITLE
Comments on authentication docs for users that had used rtweet before

### ISSUE THREAD

**Issue by maelle** [ropensci/rtweet#600]
I had an old app from before, created without a developer account, without a bearer token. I wonder what the docs should recommend in this case (I ended up requesting a developer account).

It'd also make sense to have something, even just a link to the changelog, to indicate long-time users might want to renew their authentication setup.

Beyond docs I suppose it might be difficult to have a function à la `usethis::git_sitrep()` providing a situation report and useful hints?

**Comment by llrs** [comment]
I am working on a similar check at #591 that would find duplicate tokens and move them to the right place to be used by rtweet. I will think how to better report these changes.
