### ISSUE TITLE
In authentication docs, hint at where auth_save() is saving the token + how to use on CI

### ISSUE THREAD

**Issue by maelle** [ropensci/rtweet#602]
and point to auth_save() docs to explain how to change that directory?
It's good to know that it's outside the project because it makes it usable across projects.

In this vignette I'd also expect/appreciate some docs on how to use the auth on CI (including some security advice, maybe a pointer to other docs like the googledrive ones).

**Comment by gadenbuie** [comment]
Relatedly, it'd be very helpful if one could use `auth_save()` to save the auth `.rds` file somewhere specific other than the default location and similarly if `auth_find()` (iirc an internal function) could be configured, perhaps through an env var or global option to find the serialized auth object in the custom location. This would very much simplify non-interactive use cases, e.g. shinyapps.io and other places.

**Comment by llrs** [comment]
There is an internal function `auth_path` that provides this information (and there is a way to set it to other locations which I don't think it is wise to advertise much).   
However, there is also a pending PR to change the default location #591 for which could be "customized via the specific environment variables R_USER_DATA_DIR, R_USER_CONFIG_DIR and R_USER_CACHE_DIR" as per documentation [tools::R_user_dir](https://search.r-project.org/R/refmans/tools/html/userdir.html).   
Would that be enough for the use case you have in mind @gadenbuie ? 

Note to myself this is not documented on the PR and should be probably better documented on the `auth_save` help page

**Comment by gadenbuie** [comment]
That strategy works great for personal machines or in places where users run code interactively. But in some scenarios it's necessary to store the auth object somewhere outside the user data/config/cache directories. (Or there's an alternative auth flow for unattended sessions that I missed in the docs.)

For example, to deploy an app that uses rtweet to shinyapps, I needed to locate the `.rds` file created by `auth_save()` (which required reading the source) and moving that into the directory with my app. Then, after making sure that file is git-ignored, I had to manually read it in and use it to auth with `auth_as(readRDS(".auth.rds"))`. 

I'm sure there are other scenarios where it's not possible to rely on user-level folders for auth caching and in general it'd be nice if some of the key pieces of information were exposed to the user. In particular, it'd be helpful to have a way to communicate where the auth file is stored (either when it's created or by exporting `auth_path()`). It'd also be helpful to be able to set a variable to automatically discover the auth object in the non-standard location, but that's certainly not as pressing.

**Comment by gadenbuie** [comment]
Anyway, while I appreciate rtweet handling the caching for me, it'd be really nice if `auth_save()` and `auth_as()` could also handle file paths, even if the user has to signal that they're using a file path with a `/`, `./` or `../` prefix

```r
# cached at the user level
auth_save(auth, "some-name")
auth_as("some-name")

# saved and loaded from a file 
auth_save(auth, "./some-name.rds")
auth_as("./some-name.rds")
```

**Comment by llrs** [comment]
`auth_save` currently reports, and invisibly returns, the path where it stores the file (but this is not documented yet) . However, `auth_as` could also accept paths to credentials (I think it is easier to test if such file exists than to check a correct path). 

---
I would normally recommend against using rtweet development version for production, there are a couple of things that previously worked that now do not and some breaking changes (and more might come) before its release.

**Comment by gadenbuie** [comment]
> `auth_save` currently reports, and invisibly returns, the path where it stores the file (but this is not documented yet)

You're right. I think I missed that announcement and then had a hard time figuring out where it was stored. And yeah, just checking if a file exists would be easier than signalling with some kind of path component, that's a good idea.
