### ISSUE TITLE
Add installation instructions for dev version in the README?

### ISSUE THREAD

**Issue by maelle** [ropensci/rtweet#604]
Using R-universe?

```
install.packages("rtweet", repos = 'https://ropensci.r-universe.dev')
```

or something like that.

**Comment by llrs** [comment]
There are many people using rtweet, I don't want them to install the developer version and then come back with bugs reports yet. I will wait to add something like this until the package is more stable. There are still two big user-facing changes I'm planning: renaming functions (and splitting some), support Twitter v2 API. I don't want to confuse people as I'm not updating the version number on the DESCRIPTION file each time and I don't want to encourage using the development version of the package.

**Comment by maelle** [comment]
Yeah makes sense. I suppose that more generally it's a problem with the pkgdown websites of rOpenSci packages being for the dev version whereas users of the CRAN version might be reading it. :sweat:

**Comment by llrs** [comment]
Yes, I asked about it on the slack (and maybe on the corresponding repo of rOpenSci).

**Comment by maelle** [comment]
yes this is tracked https://github.com/ropensci/dev_guide/issues/200

**Comment by llrs** [comment]
Done since a couple of weeks
