### ISSUE TITLE
Pre-compute vignette or make it an article

### ISSUE THREAD

**Issue by maelle** [ropensci/rtweet#609]
In all cases, it'd make sense to evaluate the code in there regularly (or have the same code in the tests) cf #608 

## Article

Not a vignette so might be less accessible (I'm thinking of users with a bad internet connection but maybe that doesn't go well with using an API wrapper).

## Pre-computed vignette

cf https://ropensci.org/blog/2019/12/08/precompute-vignettes/ + you could add a reminder in an unexported `release_bullets()` function cf https://ropensci.org/blog/2021/03/16/ropensci-news/#package-development-corner

**Comment by maelle** [comment]
Overall the code in the vignette is outdated.

**Comment by maelle** [comment]
The vignette about streaming is also old and probably outdated.

**Comment by llrs** [comment]
I recently updated the rtweet.rmd vignette, so now it should be up to date. 
I still want to update the streaming vignette.

Just writing my thought somewhere before I forget:
I'm not decided what to do with the vignettes, if leave them "as is" or turn it into an article or demo (Does pkgdown handle those?) In theory demos are more user accessible (from the R terminal) but I don't think users know use them (I didn't even expect to find so many packages with demos on  my own computer :sweat_smile: ). 
Maybe it can be an article and as part of the release `knitr::purl` the code to a demo. 
Also with the new runnable examples users should get a better sense of what is possible to do with rtweet.

**Comment by maelle** [comment]
I was about to point to the same links as in my first comment :joy: :see_no_evil: 

Reg pkgdown yes it handles articles!

I never use demos, I'd copy-paste chunks from articles/vignettes as an user.

**Comment by llrs** [comment]
I ended up using a child document to have the vignette and the article with the same code (one is not evaluated the other it is).
The article is almost the same as the vignette (just some minor change on the title and introduction), so if the article fails the vignette code will be updated too (but vignette doesn't have the images or results of the article). 
Closing now.
