### ISSUE TITLE
add more grouping to reference index?

### ISSUE THREAD

**Issue by maelle** [ropensci/rtweet#610]
maybe functions that return tweets vs not? The first section is very long.

**Comment by llrs** [comment]
I was testing that on e4f8979e90f383b2d3d840e193b8b03c258f40fb. How often are the documents re-built?

**Comment by maelle** [comment]
There was an error: https://github.com/r-universe/ropensci/runs/4274304506?check_suite_focus=true

Can you try building the docs locally to see if you can reproduce the error?

**Comment by llrs** [comment]
Sorry, I forgot that now the build system was also on r-universe. I can reproduce that error locally. The problem is with building the reference index, so maybe I haven't used the right structure to have subtitles. I'll explore any lead and report back to pkgdown or here anything I find.
