### ISSUE TITLE
Questions with search_tweets 

### ISSUE THREAD

**Issue by Jezzffihuter** [ropensci/rtweet#612]
### Problem

Hi, I am a green hand for the rtweet package and Twitter research.  
I have just used _**search_tweets**_ to retrieve test data, but I have two questions. Please forgive me if I am asking silly questions.

1. The package returns the following 90 columns.
user_id status_id created_at screen_name text source display_text_width reply_to_status_id reply_to_user_id reply_to_screen_name is_quote is_retweet favorite_count retweet_count quote_count reply_count hashtags symbols urls_url urls_t.co urls_expanded_url media_url media_t.co media_expanded_url media_type ext_media_url ext_media_t.co ext_media_expanded_url ext_media_type mentions_user_id mentions_screen_name lang quoted_status_id quoted_text quoted_created_at quoted_source quoted_favorite_count quoted_retweet_count quoted_user_id quoted_screen_name quoted_name quoted_followers_count quoted_friends_count quoted_statuses_count quoted_location quoted_description quoted_verified retweet_status_id retweet_text retweet_created_at retweet_source retweet_favorite_count retweet_retweet_count retweet_user_id retweet_screen_name retweet_name retweet_followers_count retweet_friends_count retweet_statuses_count retweet_location retweet_description retweet_verified place_url place_name place_full_name place_type country country_code geo_coords coords_coords bbox_coords status_url name location description url protected followers_count friends_count listed_count statuses_count favourites_count account_created_at verified profile_url profile_expanded_url account_lang profile_banner_url profile_background_url profile_image_url
I would like to confirm what do these column mean with rtweet. I think this is the best platform to seek answers.

2. I see that there are 6042 posts by id _**1399370000000000000**_, which seems too much for the global topic of #vaccine. While I suspect that the posts retrieved are not representative of all available posts globally, I would like to know how can I conduct real random sampling with specified filters (or no filter) for the vaccine topic? Alternatively, can filters combine with random sampling with stream_tweets?

3. May I know if there is any feature helpful to detect and exclude bots? What could be the recommended way to address possible bots?

Please inform me if I need to present more information. Many thanks for your help!

### Reproduce the problem

``` r
## insert code here
less_test <- search_tweets(q = "#vaccine", n = 18000, retryonratelimit = TRUE, include_rts = TRUE)
less_test <- apply(less_test,2,as.character)
write.csv(less_test,"less_test.csv")
```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
[1] ‘0.7.0’
```

### Session info

``` r
## copy/paste output
sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 936

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidytext_0.3.0 rtweet_0.7.0   jsonlite_1.7.2 ggplot2_3.3.3  dplyr_1.0.4   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        pillar_1.6.0      compiler_4.0.3    prettyunits_1.1.1
 [5] progress_1.2.2    tokenizers_0.2.1  tools_4.0.3       digest_0.6.27    
 [9] evaluate_0.14     lifecycle_1.0.0   tibble_3.0.6      gtable_0.3.0     
[13] lattice_0.20-41   pkgconfig_2.0.3   rlang_0.4.10      Matrix_1.2-18    
[17] DBI_1.1.1         curl_4.3          yaml_2.2.1        xfun_0.22        
[21] withr_2.4.2       janeaustenr_0.1.5 httr_1.4.2        knitr_1.33       
[25] askpass_1.1       hms_1.0.0         generics_0.1.0    vctrs_0.3.6      
[29] grid_4.0.3        tidyselect_1.1.0  glue_1.4.2        R6_2.5.0         
[33] fansi_0.4.2       rmarkdown_2.8     purrr_0.3.4       magrittr_2.0.1   
[37] SnowballC_0.7.0   scales_1.1.1      ellipsis_0.3.1    htmltools_0.5.1.1
[41] assertthat_0.2.1  colorspace_2.0-0  utf8_1.2.1        stringi_1.5.3    
[45] openssl_1.4.3     munsell_0.5.0     crayon_1.4.1     
```

**Comment by llrs** [comment]
Hi @Jezzffihuter, welcome to use rtweet. If you have more questions please open them here:  https://discuss.ropensci.org/ as many of your questions are not about possible bugs of the package (or new features).

1)  This should be covered by the documentation or be "self" explanatory. Is there any column you don't understand? (ie, I won't explain all the columns as this has changed on the development version of the package). 

2) It is not clear to me how do you obtain that id, probably with `less_test[, "status_id"]`. However I would advise against using as.character to all columns. There might be problems introduced by doing so. However, when I tried your code I didn't find the issue you mention, but I probably haven't got the same data as you did get when calling `search_tweet`. 

The `search_tweet` function already returns a sample of all the tweets of that hashtag. But you can always select just some tweets from those already retrieved for your analysis. `stream_tweets` does collect all the tweets on the terms searched you can as well later select randomly some of the tweets saved. 

3) There is this package that might help you: https://github.com/mkearney/tweetbotornot. What do you mean to address bots? Delete them, not omit them when capturing data.

**Comment by Jezzffihuter** [comment]
Hi @llrs, thanks for your comments. Just a few follow-ups, I will open issues in https://discuss.ropensci.org/ for similar problems.
My code is as below: 
twitter_token <- create_token(
  app = my_appname,
  consumer_key = my_key,
  consumer_secret = my_secret,
  access_token = my_access_token,
  access_secret = my_access_secret)
test <- search_tweets(q = "#vaccine", n = 10000, retryonratelimit = TRUE, include_rts = TRUE)
View(test) # appears normal
class(test) # "tbl_df"     "tbl"        "data.frame"
# test <- apply(test,2,as.character)
write.csv2(test, file = "test.csv")
1. It could be too demanding to seek explanations for all columns, and many of the columns are self-explanatory.  However, sometimes I need to check the exact meanings for columns. It would be best if I could be given a hint of the documentation.
2. The problem could be cause by "test <- apply(test,2,as.character)", but if I delete this line, there would be an error when writing the tibble into csv. How will you address such problem? I see some general posts, but not specific to the package and may cause problem just as "test <- apply(test,2,as.character)".

Many thanks for your patience to my silly questions.

**Comment by llrs** [comment]
1) No, the columns do not match the object types of that help page.
2) Yes, there are nested list on that tibble. You will need to flatten it. In the package there is the `write_as_csv` function. Use it to store the results on a csv. It will unnest columns and handle correctly the data without converting it to character. Read the documentation of `unlist` and of its arguments, this behavior is expected and normal. 

PS: I edited your last comment to make it easier for me to read the code and error message (used ``` to create a code block).

**Comment by Jezzffihuter** [comment]
Yes, thanks for the tips! Just some follow-ups.
1. May I know where to see the explanations of the objects retrieved by rtweet (90 columns) for sure?
2. I see the problem solved with write_as_csv https://github.com/ropensci/rtweet/issues/226. Still, this seems not the case for me.
```r
twitter_token <- create_token(
  app = my_appname,
  consumer_key = my_key,
  consumer_secret = my_secret,
  access_token = my_access_token,
  access_secret = my_access_secret)
test <- search_tweets(q = "#vaccine", n = 10000, retryonratelimit = TRUE, include_rts = TRUE)
View(test) # appears normal
class(test) # "tbl_df"     "tbl"        "data.frame"
test <- apply(test,2,as.character)
write.csv2(test, file = "test.csv")
write_as_csv(test, file = "test.csv")```

**Comment by llrs** [comment]
1. You'll need to look up the source code of the package. This has changed on the development version on the default branch here on github.
2. I don't see any proof that this is not the case with `write_as_csv`. Could you explain how using it didn't fix the issue to storing the data in a csv correctly? Showing some rows of the test.csv file would help. 
I'm closing this issue as this is not about any bug or feature request on the package. But you can continue to reply

**Comment by Jezzffihuter** [comment]
Sorry, I forgot to mention the details for question 2.
```r

twitter_token <- create_token(
  app = appname,
  consumer_key = key,
  consumer_secret = secret,
  access_token = access_token,
  access_secret = access_secret)

test <- search_tweets(q = "#vaccine", n = 100000, retryonratelimit = TRUE, include_rts = TRUE)
View(test)
class(test) # "tbl_df"     "tbl"        "data.frame"

# Below is the solution by Saving to csv problem #226. 

## install devtools package if it's not already
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools")
}

## install dev version of rtweet from github
devtools::install_github("mkearney/rtweet")

## load rtweet package
library(rtweet)
save_as_csv(test, file = "test.csv")
**_Error in save_as_csv(test, file = "test.csv") : 
  argument 2 matches multiple formal arguments_**

```
As the document can not be saved, I can only present the screenshot of View(test), which seems good.
![image](https://user-images.githubusercontent.com/65488456/126898311-c56bf07e-2dac-4f8b-87dc-2c496a401270.png)
Some hints would be highly appreciated.

**Comment by llrs** [comment]
Ok, now you switched to use the development version of the package which as you found the `save_as_csv` function doesn't work well. Please install again the CRAN version and use the `save_as_csv` function with data obtained with that rtweet version. Between installing and loading a package restart the R session, this would prevent some bugs to appear but might show the other problems.

**Comment by Jezzffihuter** [comment]
Thanks for your patience. I deleted the existing rtweet and use Tools - Install Packages (including dependencies).
![image](https://user-images.githubusercontent.com/65488456/126900490-fe11025d-c2d5-4274-b96d-0bfc23c97ed5.png)
![image](https://user-images.githubusercontent.com/65488456/126900559-224019eb-c9c1-4216-862e-92ff54144066.png)
I restarted R Studio before loading rtweet and save_as_csv. 
The Console returns the following:
```r

> remove.packages("rtweet", lib="~/R/win-library/4.0")

Restarting R session...

> install.packages("rtweet")
Installing package into ‘C:/Users/Jezzffihuter/OneDrive - HKUST Connect/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
also installing the dependency ‘tibble’

  There is a binary version available but the source version is later:
       binary source needs_compilation
tibble  3.1.2  3.1.3              TRUE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/rtweet_0.7.0.zip'
Content type 'application/zip' length 3547621 bytes (3.4 MB)
downloaded 3.4 MB

package ‘rtweet’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Jezzffihuter\AppData\Local\Temp\RtmpOugctz\downloaded_packages
installing the source package ‘tibble’

trying URL 'https://cran.rstudio.com/src/contrib/tibble_3.1.3.tar.gz'
Content type 'application/x-gzip' length 694155 bytes (677 KB)
downloaded 677 KB

ERROR: failed to lock directory 'C:/Users/Jezzffihuter/OneDrive - HKUST Connect/Documents/R/win-library/4.0' for modifying
Try removing 'C:/Users/Jezzffihuter/OneDrive - HKUST Connect/Documents/R/win-library/4.0/00LOCK-tibble'
Warning in install.packages :
  installation of package ‘tibble’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Jezzffihuter\AppData\Local\Temp\RtmpOugctz\downloaded_packages’
> library(rtweet)
package �rtweet� was built under R version 4.0.5
> save_as_csv(test, file = "test.csv")
Error in save_as_csv(test, file = "test.csv") : 
  argument 2 matches multiple formal arguments

```

I guess we are close to solve the problem:)

**Comment by llrs** [comment]
The error while installing the package tibble prevented to install the CRAN version of rtweet. You also seem to have several versions of R on the same machine and using a version of rtweet built for a newer R version on an older R version. 
I'm not sure this will work. Please sort this out before posting here again and make sure that the version of the package you are loading is rtweet 0.7.0 with `packageVersion("rtweet")`.
