### ISSUE TITLE
Authentication help needed

### ISSUE THREAD

**Issue by JamesWhite23** [ropensci/rtweet#614]
### Problem

I am looking to mine tweets for data using rtweet but I cannot get it to authenticate. I have checked the past forums and the solutions that work for others dont seem to work for me. I have the relevant keys, but i get error messages. I am a masters student and i have been learning how to use R but covid isolation means i am a real amateur, sorry if this is inappropriate for this forum but contact with my lecturers is limited. I really dont know what im doing so if the problem is really simple then sorry, im also new to github and have never used markdown before so apologies if this is a mess.

### Expected behavior

The different guides say that a browser window should open upon successful authentication but i never get that, only errors

### Reproduce the problem

library(rtweet)

consumer_key <- "aaa"
consumer_secret <- "bbb"
access_token <- "ccc"
access_secret <- "ddd"

create_token(
  app = "adder_data",
  consumer_key,
  consumer_secret,
  access_token,
  access_secret,
  set_renv = TRUE
)

0.7.0

### Session info

``` r
## copy/paste output
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.7.0

loaded via a namespace (and not attached):
 [1] httr_1.4.2        compiler_4.1.0    magrittr_2.0.1    R6_2.5.0         
 [5] htmltools_0.5.1.1 tools_4.1.0       yaml_2.2.1        tinytex_0.32     
 [9] rmarkdown_2.9     knitr_1.33        jsonlite_1.7.2    digest_0.6.27    
[13] xfun_0.24         rlang_0.4.11      evaluate_0.14
```

**Comment by llrs** [comment]
I understand that the actual keys and tokens have been redacted, but check that they are actually the ones provided by twitter on your developer page for your"adder_data" app. You won't be able to see them now, so you will need to regenerate them. 
Also, It will be easier to help you if you could paste the error message you get when you try to use any of the functions that call the API. Other than that with the limited information you provided I cannot provide more help.

Sorry, this is for bugs on the package not a help forum and I will close the issue. I would recommend to check with your lectures or classmates to check what have they done.
