### ISSUE TITLE
Error in tweet(x$quoted_status) : scopes

### ISSUE THREAD

**Issue by WahiduzzamanKhan** [ropensci/rtweet#615]
### Problem

Frequently getting `Error in tweet(x$quoted_status) : scopes` when searching for tweets using `search_tweets()`. It seems the error occurs pretty randomly. The last day I was getting the error while searching for `$cake`, but today I am not getting the error. Today I am getting it for `$tsla`. Maybe the error occurs when a specific kind of tweets is in the resulting data?

### Expected behavior

The expected behavior is to get a data.frame containing twitter statuses matching the search query.

### Reproduce the problem
``` r
library(rtweet)
twitterToken <- create_token(
  app = "****",
  consumer_key = "****",
  consumer_secret = "****",
  access_token = "****",
  access_secret = "****"
)
tweets <- search_tweets(q = "$tsla, n = 2000, include_rts = FALSE, lang = "en", type = "recent")
Error in tweet(x$quoted_status) : scopes
```

### rtweet version
``` r
[1] ‘0.7.0.9000’
```

### Session info
``` r
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.7.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        lubridate_1.7.10  prettyunits_1.1.1 withr_2.4.2       crayon_1.4.1     
 [6] rappdirs_0.3.3    R6_2.5.0          jsonlite_1.7.2    lifecycle_1.0.0   httr_1.4.2       
[11] rlang_0.4.11      progress_1.2.2    curl_4.3.1        rstudioapi_0.13   vctrs_0.3.8      
[16] generics_0.1.0    ellipsis_0.3.2    tools_4.1.0       bit64_4.0.5       glue_1.4.2       
[21] bit_4.0.4         hms_1.1.0         compiler_4.1.0    askpass_1.1       pkgconfig_2.0.3  
[26] openssl_1.4.4
```

**Comment by llrs** [comment]
There have been numerous reports of sporadic errors, but without a reproducible example I cannot find the root cause of this. If you could provide the `traceback()` or further information about this case, it would help.

**Comment by phileasdg** [comment]
I am experiencing the same error using `search_tweets()`. Here is an example of my code:

```
search_term <- "foo"

twitterdata <- search_tweets(
  search_term, n = 1000, include_rts = FALSE)
```

Here is the traceback for my case:
```
Error in tweet(x$quoted_status) : scopes

7.
stop(end)
6.
tweet(x$quoted_status)
5.
FUN(X[[i]], ...)
4.
lapply(x, tweet)
3.
do.call("rbind", lapply(x, tweet))
2.
tweets_with_users(tweets)
1.
search_tweets(search_term, n = 1000, include_rts = FALSE)
```

I am running the latest versions of R, Rstudio, and Rtweets.

**Comment by alexpghayes** [comment]
Here is a slightly different example that results in a similar error for me:

``` r
library(rtweet)

users <- c("1453846961585594370", "999975127071805451", "56766111", "14554529", 
  "378229870", "867373726291161088")

get_favorites(users)
#> Error in FUN(X[[i]], ...): scopes
```

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by llrs** [comment]
Ok, this example was reproducible and found the reason. Thanks for the report @alexpghayes .

The problem is for example with tweet id "1400810492843630598" (one of the favorited tweets of the third user you queried) which includes the new data about scopes. I made the error more informative and handled it.
