### ISSUE TITLE
post_tweet does not pass on token when `destroy_id` is specified

### ISSUE THREAD

**Issue by simonheb** [ropensci/rtweet#617]
That's it. That's the whole issue. I am to inexperienced with git to know whether this should be solved via a pull request or some other way,
The relevant line of code is here: https://github.com/ropensci/rtweet/blob/69ae10048fd450479c9acc7ef03d2b994c9042d1/R/post-tweet.R#L99

**Comment by llrs** [comment]
Good catch! This can be fixed via a pull request.

**Comment by llrs** [comment]
Merged
