### ISSUE TITLE
 `direct_messages` returns repetitions of the same page, if `n` is set to higher values

### ISSUE THREAD

**Issue by simonheb** [ropensci/rtweet#618]
### Problem
When I retrieve many direct messages, e.g., with `n=150`, I get an object in return that has the right number of "pages", but all elements in the list contain the same value.

### Expected behavior
I expect one data frame of ~150 entries or a list of ~4 pages with ~40 distinct entries each. What I get is a list with ~pages and 40 identical entries

### Reproduce the problem

You need an account with sufficiently many private messages
``` r
messages<-direct_messages(n = 150,token=token,retryonratelimit = TRUE)
identical(messages[[1]],messages[[2]])
identical(messages[[1]],messages[[3]])
```

### rtweet version

``` r
[1] ‘0.7.0.9000’
```

**Comment by simonheb** [comment]
The problem seems to be here
https://github.com/ropensci/rtweet/blob/69ae10048fd450479c9acc7ef03d2b994c9042d1/R/http.R#L230

For DMs, the returned JSON does have `json$next_cursor`, but it does not have `json$next_cursor`. I am not sure we can simply switch to using this, at it might affect other parts.

**Comment by simonheb** [comment]
Are there any thoughts on this issue? Otherwise I might go ahead an implement this in a PR

**Comment by llrs** [comment]
I hadn't look into it. I think it is reasonable to use an ifelse there, if you send a PR I'll review it. As a general comment thing I think it is better to use `*_str` because the long double need special handling (If you take care of that it is also fine). Thanks!

**Comment by llrs** [comment]
I modified the code as suggested, but I cannot test it, let me know if you find any other problem.
