### ISSUE TITLE
Typo in default function value for `host` in `TWIT_method` and no implementation for DELETE and PUT

### ISSUE THREAD

**Issue by simonheb** [ropensci/rtweet#620]
https://github.com/ropensci/rtweet/blob/69ae10048fd450479c9acc7ef03d2b994c9042d1/R/http.R#L26

There's a t missing in the default value. Also there's no `DELETE` and `PUT`, even though the API references sometimes uses them. E.g., here: https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/welcome-messages/api-reference/list-welcome-messages

**Comment by llrs** [comment]
Fixed the typo, thanks!
I don't think we use PUT or DELETE methods so far, but I'll keep that in mind (and leave the issue open)
