### ISSUE TITLE
get_followers() returning 5000 followers instead of 75000

### ISSUE THREAD

**Issue by j-anderson-sci-comm** [ropensci/rtweet#621]
I wrote a script to collect followers for a list of accounts in a data frame using the "get_followers()" function, but it returns only 5000 followers at each request instead of 75000. I am still a relatively inexperienced coder so I am not sure what I have done wrong. Any help would be greatly appreciated!

My code:
sci_users_clean

sci_snowball_2_users <- data.frame(screen_name = "", user_id = "")
for(i in 1:nrow(sci_users_clean))
{
  following <- get_followers(sci_users_clean$screen_name[i], n = 1000, retryonratelimit = TRUE)
  ad_hoc <- data.frame(screen_name=sci_users_clean$screen_name[i], following=following)
  sci_snowball_2_users <- rbind(sci_snowball_2_users, ad_hoc)
}

Output per iteration:
75000 followers!
70000 followers!
65000 followers!
60000 followers!
55000 followers!
50000 followers!
45000 followers!
40000 followers!
35000 followers!
30000 followers!
25000 followers!
20000 followers!
15000 followers!
10000 followers!
5000 followers!
Waiting about 15 minutes for rate limit reset...

**Comment by llrs** [comment]
If you have 5 users on the initial sci_users_clean the code is doing exactly as expected, as you request 1000 followers for each account (not the 75000 you mention). I don't know where this idea of 75000 followers come but you can remove the n argument value you have and it would try to retrieve more followers on each iteration.

(It would also help if you provided which version of rtweet are you using)

**Comment by Arf9999** [comment]
CRAN version: 75000 is the twitter rate limit of requests for follower status_ids  per 15 minutes.  Each query (i.e. account that is being followed) uses 5000 of that rate limit. So if you've set n = 1000, you'll be able to make a maximum of 15 requests, i.e. a maximum of 15000 user_ids will be returned. The console will show the decreasing rate limit number, decreasing by 5000 per call. 

`retryonratelimit = TRUE` will allow you to increase the n value to whatever you like (even more than 75000), but you'll have to wait for long periods while the script pauses for the rate limit to be reset. 

If you're querying large followings (i.e. hundreds of thousands) it can take a very long time.

**Comment by j-anderson-sci-comm** [comment]
> CRAN version: 75000 is the twitter rate limit of requests for follower status_ids per 15 minutes. Each query (i.e. account that is being followed) uses 5000 of that rate limit. So if you've set n = 1000, you'll be able to make a maximum of 15 requests, i.e. a maximum of 15000 user_ids will be returned. The console will show the decreasing rate limit number, decreasing by 5000 per call.
> 
> `retryonratelimit = TRUE` will allow you to increase the n value to whatever you like (even more than 75000), but you'll have to wait for long periods while the script pauses for the rate limit to be reset.
> 
> If you're querying large followings (i.e. hundreds of thousands) it can take a very long time.

I see! I misunderstood how retryonratelimit = TRUE functioned here, and I see now that it's not necessary for the functioned I intended. The issue is that while I only want 1000 followers from each account, I have a very large number of accounts of interest and it is only returning 5000 followers every 15 minutes instead of 75000.

**Comment by llrs** [comment]
Yes, this is a known bug on the version of CRAN of get_followers, as internally the number of followers that retrieves is set to 5000.  This is fixed on the devel version on this repository. You could try this version or wait for the next rtweet release on CRAN. 

Closing the issue as this has already been fixed.

**Comment by Arf9999** [comment]
Really? I use that function in the CRAN version and do not have that issue.  Is it possibly linked to the default app?

**Comment by j-anderson-sci-comm** [comment]
> Yes, this is a known bug on the version of CRAN of get_followers, as internally the number of followers that retrieves is set to 5000. This is fixed on the devel version on this repository. You could try this version or wait for the next rtweet release on CRAN.
> 
> Closing the issue as this has already been fixed.

Thank you!

**Comment by llrs** [comment]
@Arf9999 Could be that I didn't understand the code of get_followers and the 5000 refers to the pagination instead of the limit of each query. But I won't delve further on this issue either it is already solved or non existent/related to other usage problem I don't have time to debug.
