### ISSUE TITLE
rtweet tutorial for beginners

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [ropensci/rtweet#624]
Hello rtweet !

I don't have any bugs or issues to report but wanted to share that **I made a tutorial on how to use this package**. 

I tested and ran the code before I placed it in the tutorial. I wanted to publish the markdown file as it was a `learnr` document, but  I don't have access to RStudio connect, as I have added a few quiz questions at the end (guide / tutorial / mini quiz). 

I do hope this gets included in the package as I believe it will help more people learn the power behind this package. I also saved my twitter data so people can learn even if they don't have Twitter Developer account.

the files are on my [GitHub](https://github.com/PythonCoderUnicorn/rtweet-tutorial)

Thanks for all hard work!

**Comment by llrs** [comment]
Hi, great to see more material about how to use the package for beginners :partying_face: 

The development version has undergone many big changes (and there are some more coming), including updating the vignette. I will use your tutorial to improve the [Getting Started vignette](https://docs.ropensci.org/rtweet/articles/rtweet.html). Many thanks for the feedback!!

**Comment by resulumit** [comment]
I also have some workshop materials on collecting tweets with this package.

Slides: https://resulumit.com/teaching/twtr_workshop.html
Repository: https://github.com/resulumit/twtr_workshop

**Comment by llrs** [comment]
Thanks the introduction an explanation [from slide 93](https://resulumit.com/teaching/twtr_workshop.html#93) are great, however, I'm not sure how did you create the data for network plots. You seem not to use the network_plot (and network_data) from rtweet (I'm just curious if you knew they existed or not).

**Comment by resulumit** [comment]
I recommend students to use `tidygraph` for network data creation/manipulation,  `ggraph` for visualisation. I think these offer increased functionality and control. Currently, from [slide 229](https://resulumit.com/teaching/twtr_workshop.html#229) onwards, but slides get updated frequently.

**Comment by llrs** [comment]
Many thanks for your tutorials, seeing what functions did you mentions and show, I added them to the new vignette. I hope your audience will find easier the rtweet introduction (on the next release).
