### ISSUE TITLE
get_trends() results omit observed "Trending" in Twitter

### ISSUE THREAD

**Issue by geotheory** [ropensci/rtweet#629]
Pulling the trending data for UK (`get_trends(woeid = '23424975')`) returns a list of mainly sport and pop individuals and references.

<img width="884" alt="image" src="https://user-images.githubusercontent.com/1282581/136662550-b6996cdc-4e07-4199-9644-985046352fec.png">

But in Twitter I can currently see "_Home Office_" and "_White Privilege_":

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1282581/136662608-f2cab9bb-f4d6-42f5-8d80-aa26d7cc0279.png">

Any idea why these are not coming through the API?

**Comment by llrs** [comment]
What you seem to show is what is happening not trends, I think this is different for Twitter. But the trends is something I haven't explored.

**Comment by llrs** [comment]
Ok, as you said, this is not something of the rtweet package, so I'm closing this issue, if you find that there is something on rtweet, let me know with a new issue with the details.
