### ISSUE TITLE
rtweet_bot authentification working in local not via GitHub Actions

### ISSUE THREAD

**Issue by Valexandre** [ropensci/rtweet#632]
Hello,

I come across a weird authentification issue using the new rtweet_bot function. I'd like to tweet something via Github Actions regularly. My script works when running on my computer, but not on GH.

Here is how my auth looks like 

```
tweetbot_token <- rtweet::rtweet_bot(
  api_key = Sys.getenv("TWITTER_KEY"),
  api_secret = Sys.getenv("TWITTER_SECRET_KEY"),
  access_token =  Sys.getenv("TWITTER_TOKEN"),
  access_secret =  Sys.getenv("TWITTER_TOKEN_SECRET")
 )
rtweet::auth_as(tweetbot_token)

rtweet::post_tweet(status = "This is a test tweet.")
```

It sends a test tweet via my laptop
But I get this on GH

```
Error: Error: Twitter API failed [400]
 * Bad Authentication data. (215)
Execution halted
```

This happens here. Is there somethin I am [missing here](https://github.com/Valexandre/GH_Actions_Trajets) ?

Thanks a lot.

**Comment by llrs** [comment]
The error is telling that the authentication failed. Did you double check the credentials provided match between your computer and the ones stored as secret on your repository? If they match I'm not sure what is going on, I think that other users already use `rtweet_bot` on GHA without problems.

**Comment by Valexandre** [comment]
I'll do that again then 
Thanks Luis.
I'll tell you.

**Comment by Valexandre** [comment]
Ok then. This is solved. I put the tokens in an environment secret repo. 
I thought it was reachable for all repos, but it obviously wasn't. Thanks again.

**Comment by llrs** [comment]
Glad it wasn't a issue within rtweet, and thanks for using it. I think secreta are only shared within a organization using a special repo, but I might be wrong. Good luck with your peoject
