### ISSUE TITLE
Feature Request: Expose the API that shows who liked a tweet

### ISSUE THREAD

**Issue by steveharoz** [ropensci/rtweet#638]
The API is described here: https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-tweets-id-liking_users

It gives a list of WHO liked a tweet. Not just a count of how many people did.

I could see it operating just like `get_retweeters(status_id)`. It could be `get_likers(status_id)`

**Comment by llrs** [comment]
Hi, 
Support for API v2 is likely to come this 2022, but I've been busy working on other parts of the package. 
About the name of said function, there have been discussions (https://github.com/ropensci/rtweet/issues/480) about renaming the existing functions to provide an easier usage of the API. It would probably be `liking_users(status_id)`

**Comment by llrs** [comment]
This is now possible using API v2, for example: `tlu <- tweet_liking_users("567053242429734913")`
