### ISSUE TITLE
How to save collected tweets to .json file

### ISSUE THREAD

**Issue by nipnipj** [ropensci/rtweet#639]
Hello! I'm trying to learn how to use this package and the following question emerged.
How can we save the output of `search_tweets("trump", n = 100, include_rts = F, parse = F)` to a `.json` file that can be read by `parse_stream`?

**Comment by llrs** [comment]
Hi @nipnipj,
To parse a stream you'll need to use `stream_tweets`, which doesn't search for tweets but reports the live tweets about the query to a .json file. However, it seems like you want to do something and you don't know how. Maybe if you explain what you are trying to do it would be easier for me to help.
I'm closing this as this is not a bug or a feature request, but I'll keep helping if I can.
