### ISSUE TITLE
The status code 401 resulting from using incorrect bearer token on a GET request doesn't reach the user

### ISSUE THREAD

**Issue by jiwanheo** [ropensci/rtweet#641]
Hi! Thank you for the awesome package.

I'm calling `rtweet_app()` with an intentionally incorrect bearer token, that is `auth_save`'d. 

I'd expect error to occur with [jsonlite](https://github.com/ropensci/rtweet/blob/affad4ba51ead30b847a41b85dc2b0280502670d/R/http.R#L302-L303) from the `from_js` call in `TWIT_get`, but it doesn't reach here. Instead, the error I get is: "Error in .makeMessage(..., domain = domain) : object 'account' not found"

After reading the source code, I think the problem is that `handle_protected` stops the code [here](https://github.com/ropensci/rtweet/blob/affad4ba51ead30b847a41b85dc2b0280502670d/R/http.R#L45), when it [tries to find](https://github.com/ropensci/rtweet/blob/affad4ba51ead30b847a41b85dc2b0280502670d/R/http.R#L376) `account`, when params don't contain `screen_name` or `user_id`. 

Not sure if this is by design, but I'd love to reach the httr error message on invalid tokens.

Thank you!

**Comment by llrs** [comment]
Hi  Jiwan,

yes, handle_protected seems to be mishandling the http error 401 (which I thought was specific to protected accounts). This will need to be handled different to detect protected accounts and at the same time report other common errors. 
Thanks for spotting this.
