### ISSUE TITLE
Search Query with emoji

### ISSUE THREAD

**Issue by LuigiC72** [ropensci/rtweet#642]
Good evening,
a rather general question: is it possible via search_tweets to run a query based on a specific emoji/emoticon?
Thanks
Best
Luigi

**Comment by llrs** [comment]
I'm not sure how are these converted used, in principle I don't don't see why not. 
You could probably could try searching pasting the emoji on a string and see what happens or perhaps look for their description ":+1:" ":sad:" and so on.

Try it and let me know if/what works or doesn't. Thanks!

**Comment by LuigiC72** [comment]
Thanks for the reply! It seems to me no. But I keep working on that. Best, Luigi

**Comment by llrs** [comment]
Could you post the search (and code) you tried? It would help me guide what kind of search users would like to have. Maybe down the road it can support it

**Comment by LuigiC72** [comment]
It's just a question that came from a student of mine. I was explaining her how to convert emoticons to text for a sentiment analysis and then she asked me if she could run a query directly with an emoticon. However, following your advice, say you run the following query: <<search_tweets(":Grinning Face:", n = 200, include_rts = FALSE)>> you do not get tweets with the emoticon "grinning face". Any help in this respect would be greatly appreciated. Thanks!

**Comment by llrs** [comment]
I'm busy with other things, but perhaps other users know how to do this, or maybe you come up with something. 
But I tested it on the website and it is possible to plainly search an emoji so probably something like 
```
search_tweets("🪲", n = 200, include_rts = FALSE)
```
Might work, but I haven't tested it.

**Comment by LuigiC72** [comment]
Solved it :-) 

library(emo)
library(rtweet)

x <- emo::ji("smile")
smile <- search_tweets(x, n = 200, lang = "en", include_rts = FALSE)
print(smile $text[1:5])

Thanks
Luigi
