### ISSUE TITLE
authentication not working- leads to error page

### ISSUE THREAD

**Issue by animathis** [ropensci/rtweet#646]
I am trying to use create_token to begin the process of using rtweets. I have the correct API keys, and the proper authentification is set up through the Twitter developer page (with the callback URL that is specified in https://cran.r-project.org/web/packages/rtweet/rtweet.pdf). When I run create_token, it sends me to the right popup from twitter asking me to approve the login. However, when I do, all I get is a page that says this site can't be reached. Am I using the wrong callback URL? Or is the function not working for anybody else?

**Comment by llrs** [comment]
I'm not sure I understand your question. You can't specify the callback url on the create_token function, but it should work the same as everybody else. Are you behind a firewall or have restricted some network properties? Did you try several times with some time between them?

**Comment by llrs** [comment]
Any updates on this issue? Did you find it again? (I'm closing it for now, but if there is some reproducible problem or others report trouble it might be reopened).
