### ISSUE TITLE
Adding members to lists

### ISSUE THREAD

**Issue by stephlocke** [ropensci/rtweet#652]
### Problem

I cannot add members to a list using `post_list()` and I get the error message:
> Error: Twitter API failed [403]
> \* You aren't allowed to add members to this list. (104)

Rate limit investigation info:
- I initially ran a full successful list creation operation for ~600 accounts. Then the next creation action errored part ways through. It didn't work again, even with just trying to add 7 accounts.
- Running `rate_limit()` has not shown any change in limit remaining for `/lists/:id&PUT` or `	
/lists/:id/members&POST` after errors. Both say 300.
- I initially waited 15 mins in case of rate limit and still got the issue. I then turned my machine off overnight and came back to it this morning, getting the same issue.
- I've tried with a variety of older and newer auth mechanisms to see if that varies the rate limit or the error.

I read the issue about protected accounts impacting this operation (#592) and have excluded the protected accounts.

### Expected behavior

1. Create a list
2. Add members to the list

### Reproduce the problem

This is taken from the examples.  It's set with private to minimise impact on others but the same experience occurs if it's a public list.

``` r
library(rtweet)
auth_setup_default()
users <- c("_R_Foundation", "R_dev_news", "rweekly_live", "RConsortium", "rstats4ds",
           "icymi_r", "rstatstweet", "RLadiesGlobal")

r_lst <- post_list(users,
                   "r-accounts",
                   description = "R related accounts", private = TRUE)
```

### rtweet version

After receiving the error, I ported from the CRAN version to the latest commit.

``` r
> packageVersion("rtweet")
[1] ‘0.7.0.9011’
```

### Session info

``` r
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] rtweet_0.7.0.9011

loaded via a namespace (and not attached):
 [1] httr_1.4.2       compiler_4.1.0  
 [3] magrittr_2.0.2   R6_2.5.1        
 [5] cli_3.1.1        promises_1.2.0.1
 [7] later_1.3.0      tools_4.1.0     
 [9] withr_2.4.3      curl_4.3.2      
[11] Rcpp_1.0.7       jsonlite_1.7.3  
[13] httpuv_1.6.3     openssl_1.4.6   
[15] rlang_1.0.1      askpass_1.1     
```

**Comment by llrs** [comment]
There have been some problems with lists API endpoints recently (#643 ), and I'm not sure what is happening with them. They previously worked, there is no official documentation of any change; yet now it hasn't worked well for some time (I think I noticed a couple of weeks before this commit, https://github.com/ropensci/rtweet/commit/f555522bf3eeb53e550869bb89f41772dfebaadd) .

Thanks for filling the detailed report. I will try to investigate this further.

**Comment by llrs** [comment]
@stephlocke Thanks for the continuous updates. 
I didn't find anything yet on their forum https://twittercommunity.com/c/twitter-api/rest-api-v1-1/6, maybe it is time to raise these cases (just documenting, where to post/search )

**Comment by llrs** [comment]
I can't say I tested much more the functionality but Twitter is moving to the API v2 so I don't think it is worth expending much more time with API v1 and trying to circumvent its limitations. I'm closing the issue.
