### ISSUE TITLE
get_friends sometimes returns a single empty column

### ISSUE THREAD

**Issue by neilcharles** [ropensci/rtweet#656]
### Problem

I installed the github version of rtweet to avoid the known problem with the cran version that get_follows fails when passed a list that contains locked users. But when the current development version get_follows is run on a fairly large number of users (50-100), it will return the error:

Error in rbind(deparse.level, ...) :                                                                                   
  numbers of columns of arguments do not match

This seems to happen because get_follows will sometimes randomly return only an empty `from_id` column and no `to_id`. This is not caused by locked accounts and it's possible to pull valid results for the same account afterwards.

### Expected behavior

get_follows should always return two columns - `from_id` and `to_id` - whatever is returned by Twitter's API and should probably retry on whatever is causing this failure.

### Reproduce the problem

I've run the below code multiple times and always get a failure but on different rows each time.

``` r
library(rtweet)
library(tidyverse)

#Get members for an >80 person Twitter list
source_list <- lists_members(1358773756974555136)

#Run get_friends for source_list users but nest results using purrr::map so that rbind doesn't fail
#Some values in source_list_follows$friends will be empty, single column tables
source_list_follows <- source_list %>% 
  mutate(friends = map(.x = user_id, .f = ~get_friends(.x, retryonratelimit = TRUE, n = 5000, verbose = TRUE)))

#Re-run get_friends for one of the failed rows to show that it works
get_friends(source_list$user_id[FAILED_ROW_NUMBER], retryonratelimit = TRUE, n = 5000, verbose = TRUE)

```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
```
0.7.0.9012

### Session info

``` r
## copy/paste output
sessionInfo()
```

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggraph_2.0.5      tidygraph_1.2.0   forcats_0.5.1     stringr_1.4.0     dplyr_1.0.7       purrr_0.3.4      
 [7] readr_2.1.2       tidyr_1.2.0       tibble_3.1.6      ggplot2_3.3.5     tidyverse_1.3.1   rtweet_0.7.0.9012

loaded via a namespace (and not attached):
 [1] ggrepel_0.9.1      Rcpp_1.0.8         lubridate_1.8.0    prettyunits_1.1.1  assertthat_0.2.1   digest_0.6.29     
 [7] utf8_1.2.2         ggforce_0.3.3      R6_2.5.1           cellranger_1.1.0   backports_1.4.1    reprex_2.0.1      
[13] httr_1.4.2         pillar_1.7.0       progress_1.2.2     rlang_1.0.1        curl_4.3.2         readxl_1.3.1      
[19] rstudioapi_0.13    igraph_1.2.11      polyclip_1.10-0    munsell_0.5.0      tinytex_0.36       broom_0.7.12      
[25] compiler_4.0.3     modelr_0.1.8       xfun_0.29          askpass_1.1        pkgconfig_2.0.3    openssl_1.4.6     
[31] tidyselect_1.1.1   gridExtra_2.3      graphlayouts_0.8.0 fansi_1.0.2        viridisLite_0.4.0  crayon_1.4.2      
[37] tzdb_0.2.0         dbplyr_2.1.1       withr_2.4.3        MASS_7.3-53        grid_4.0.3         jsonlite_1.7.3    
[43] gtable_0.3.0       lifecycle_1.0.1    DBI_1.1.2          magrittr_2.0.2     scales_1.1.1       cli_3.1.1         
[49] stringi_1.7.6      farver_2.1.0       viridis_0.6.2      fs_1.5.2           xml2_1.3.3         ellipsis_0.3.2    
[55] generics_0.1.2     vctrs_0.3.8        tools_4.0.3        glue_1.6.1         tweenr_1.0.2       hms_1.1.1         
[61] colorspace_2.0-2   rvest_1.0.2        haven_2.4.3

**Comment by llrs** [comment]
Many thanks for the explanation and the example, the problem you mention might be due to the reasons you mention. However, I the rate limit makes the wait too long just to reproduce the error and  there is no FAILED_ROW_NUMBER defined so even when it will finish retrieving all the profiles it won't reproduce the error. 

Could you share your `traceback()` after the error message is raised and post the user id reported with `source_list$user_id[FAILED_ROW_NUMBER]` it would be easier to solve the bug and check it is solved.  Or simply a user where get_followers fails with the error message reported. But, if the function sometimes return valid data and sometimes it doesn't then the fault is on the Twitter's API, and at most rtweet could mitigate the problems.

**Comment by neilcharles** [comment]
Sorry, I know saying it always fails somewhere random after running for ages isn't hugely helpful.

I ran the same Twitter list again and output the `traceback()` to a file because it's enormous.

```r
source_list <- lists_members(1358773756974555136)

test_output <- get_friends(source_list$user_id, retryonratelimit = TRUE, n = 5000, verbose = TRUE)

zz <- file("trace_out", open = "wt")
sink(zz)
sink(zz, type = "message")
traceback()
sink(type = "message")
sink()
```

Then I manually searched the `traceback()` output for a failed `get_friends()` pull.

The problem ones look like this. I'm not including the full traceback dump at it's >60k lines but shout if you want it.
It's a single column table containing just a single `from_id`. Apologies, I said empty table in my opening post above, it's not empty, it's one column (`from_id`), containing a single value with the user id that was requested, and no `to_id` column.

```console
structure(list(from_id = "331821111"), class = c("tbl_df", 
       "tbl", "data.frame"), row.names = c(NA, -1L), rtweet_cursor = "0")
```

So the failed pull in this case was user_id 331821111. But once my rate limit resets, I can manually pull that single user with no problems.

```r
get_friends(331821111, retryonratelimit = TRUE, n = 5000, verbose = TRUE)
```

I think you're probably right that it's Twitter's API rather than rtweet but hoped maybe rtweet could retry if it receives no data from Twitter, otherwise `get_friends()` will always fail when passed a large number of users. My workaround is to do the purrr::map line above and then handle the missing ones afterwards, running `get_friends()` across those ones again until they're all populated.

**Comment by llrs** [comment]
I'm sorry but I do not think rtweet can distinguish between Twitter's API returning an incomplete response and having other problems with the request, at most I can make get_friends error if the final parsed result doesn't have the two expected columns.

But the incomplete Twitter response is  worth raising to Twitter' support team.

**Comment by neilcharles** [comment]
Fair enough, thanks for the speedy reply :)  I'll use the workaround, running one account at a time and wrap it with my own retry.

Thought it was worth a note anyway as even if Twitter is the cause, it does make rtweet return an error after running for a long time.

**Comment by llrs** [comment]
I recommend following good practices when interacting with APIs and do not wait till the end to save the result while iterating through a list. Like those recommended by [polite](https://cran.r-project.org/package=polite).
I'm not sure if there are other endpoints that report this kind of data in bulk downloads, perhaps they exists for API v2 and you could use them.
