### ISSUE TITLE
tweet_threading() significantly faster for 2nd tweet in thread

### ISSUE THREAD

**Issue by charliejhadley** [ropensci/rtweet#693]
### Problem

The time for `tweet_threading()` to run depends on which numbered tweet in a thread is provided.

### Expected behaviour

Tweet position in thread shouldn't affect function speed.

### Reproduce the problem

Here's an example thread: https://twitter.com/charliejhadley/status/1508513828593672192

And a function for comparing the speed for each tweet:

```r
library(rtweet)
library(tictoc)

charlie_thread_ids <- c("1508513828593672192", "1508513830372007936", "1508513831974232077", "1508513833580699652")

time_thread_pos <- function(thread_tweets, position){
  
  tic(paste("Time for tweet number", position, "of", length(thread_tweets)))
  tl <- tweet_threading(thread_tweets[position])
  toc()
  
  return(tl)
  
  
}

tl_2 <- time_thread_pos(charlie_thread_ids, 2)
# Time for tweet number 2 of 4: 0.61 sec elapsed
tl_3 <- time_thread_pos(charlie_thread_ids, 3)
# Has not completed.
```

### rtweet version

```r
> packageVersion("rtweet")
[1] ‘0.7.0.9017’
```

### Session info

```r
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.6.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tictoc_1.0.1      rtweet_0.7.0.9017

loaded via a namespace (and not attached):
 [1] fansi_1.0.2       prettyunits_1.1.1 utf8_1.2.2        crayon_1.5.0      withr_2.5.0       R6_2.5.1          jsonlite_1.8.0    lifecycle_1.0.1   magrittr_2.0.2   
[10] pillar_1.7.0      httr_1.4.2        rlang_1.0.2       progress_1.2.2    cli_3.2.0         curl_4.3.2        vctrs_0.3.8       ellipsis_0.3.2    tools_4.1.1      
[19] bit64_4.0.5       glue_1.6.2        bit_4.0.4         hms_1.1.1         compiler_4.1.1    askpass_1.1       pkgconfig_2.0.3   openssl_2.0.0     tibble_3.1.6 
```

**Comment by llrs** [comment]
In API v2 there is an endpoint to collect threads, so it is know to be problematic with API v1
However, perhaps there is something I can do to try improve it before using API v2. 
By has not completed how long did you leave it running?  What is bottleneck you found on the function? Do you have any suggestions on how to improve it?

**Comment by llrs** [comment]
There are several infinite loops on the current version. Many thanks for the testing thread! I improved the function on #695. Could you test it and tell me if it works well? There are some scenarios I haven't tested but as you seem to be using it you might find new bugs. Let me know if there is something else buggy.

**Comment by charliejhadley** [comment]
I tested https://github.com/ropensci/rtweet/tree/threading and it now appears that timing isn't affected by tweet position in a thread!

I've discovered a new issue, which is that traversing forwards doesn't appear to work. This was found by testing https://github.com/ropensci/rtweet/commit/b899da38a1649cb3fe412d8319b5e11d31547087.

### Setup function

```r
time_thread_pos <- function(thread_tweets, position, traverse = "backwards"){
  
  tic(paste("Time for tweet number", position, "of", length(thread_tweets)))
  tl <- tweet_threading(thread_tweets[position], traverse = traverse)
  toc()
  
  return(tl)
  
}
```

### Example thread

I think it's important to test longer threads for this functionality. You can find lots here - https://awesomethread.com/threads. Here's a 10 tweet thread I chose:

```r
jeffs_thread <- c("1256278643224965120", "1256278643883442176", "1256278644508377088", "1256278645255008256", "1256278645905055745", "1256278646605504512", "1256278647226265600", "1256278647914156033", "1256278648690262018", "1256278649600225280")
```

### traverse = "backwards"

This successfully finds all previous tweets:

```r
purrr::map(c(1:3, 9, 10), ~paste(nrow(time_thread_pos(jeffs_thread, .x, "backwards")), "tweets found from position", .x)) 
# Time for tweet number 1 of 10: 0.297 sec elapsed
# Time for tweet number 2 of 10: 0.538 sec elapsed
# Time for tweet number 3 of 10: 0.642 sec elapsed
# Time for tweet number 9 of 10: 1.768 sec elapsed
# Time for tweet number 10 of 10: 1.843 sec elapsed
# [[1]]
# [1] "1 tweets found from position 1"
# 
# [[2]]
# [1] "2 tweets found from position 2"
# 
# [[3]]
# [1] "3 tweets found from position 3"
# 
# [[4]]
# [1] "9 tweets found from position 9"
# 
# [[5]]
# [1] "10 tweets found from position 10"
```

### traverse = "forwards"

This only finds the provided tweet.

```r
purrr::map(c(1:3, 9, 10), ~paste(nrow(time_thread_pos(jeffs_thread, .x, "forwards")), "tweets found from position", .x)) 
# Time for tweet number 1 of 10: 2.259 sec elapsed
# Time for tweet number 2 of 10: 2.224 sec elapsed
# Time for tweet number 3 of 10: 2.372 sec elapsed
# Time for tweet number 9 of 10: 2.325 sec elapsed
# Time for tweet number 10 of 10: 2.201 sec elapsed
# [[1]]
# [1] "1 tweets found from position 1"
# 
# [[2]]
# [1] "1 tweets found from position 2"
# 
# [[3]]
# [1] "1 tweets found from position 3"
# 
# [[4]]
# [1] "1 tweets found from position 9"
# 
# [[5]]
# [1] "1 tweets found from position 10"
```

**Comment by llrs** [comment]
Thanks for testing it and providing new sources to check the functionality. 

I don't have time now to look in detail with these, but the current limitation is that to retrieve a thread we need to look up the author's tweets via their timeline. The timeline endpoint on API v1 is capped to 3200 tweets so if the thread is from a prolific author or long ago it won't be able to find the thread as mentioned on the PR (I also set up a message on the verbose mode to mention this). Perhaps there is some room of improvement...

**Comment by llrs** [comment]
Now it should work with those threads (but only tested on the one provided). I though `get_timeline` would automatically search all the tweets but unless told explicitly it won't. I also had some problems with `get_timeline`, but I couldn't reprex it, if this was the case when you tried, hopefully when you try the new commit it will work. 

While exploring the issue I found some other problems/enhancements #696 and #697

**Comment by charliejhadley** [comment]
I really appreciate how quickly you're working on this! 

I'm still seeing the function being more successful when given tweets later in a thread (tested with https://github.com/ropensci/rtweet/commit/95d2eeef0e1e81b24bb76e658bcd055e77ff9675)

```r
library(rtweet)
time_thread_pos <- function(thread_tweets, position, traverse = "backwards"){
  
  tweet_threading(thread_tweets[position], traverse = traverse)

}

jeffs_thread <- c("1256278643224965120", "1256278643883442176", "1256278644508377088", "1256278645255008256", "1256278645905055745", "1256278646605504512", "1256278647226265600", "1256278647914156033", "1256278648690262018", "1256278649600225280")

purrr::map_chr(c(1:3, 9, 10), ~paste(nrow(time_thread_pos(jeffs_thread, .x)), "tweets found from position", .x)) 

# [1] "1 tweets found from position 1"   "2 tweets found from position 2"   "3 tweets found from position 3"  
# [4] "9 tweets found from position 9"   "10 tweets found from position 10"
```

**Comment by llrs** [comment]
Thanks, some encouragements words help me going on maintaining the package. I was thinking on doing some work on rtweet and having a quick feedback cycle helps me working on it. 

Later as in later on time or as later in the reply chain? The tweet 10 is the first one (the first on time the last on the reply chain), so when doing backwards it can retrieve all the replies to it. But tweet 1 (1256278643224965120)  is the the latest reply (latest on time, first on the reply chain) going backward there can't find any other reply, there is none. That's why increasing the tweet position increases the number of tweets found when going backwards. In practice I don't think this should be modified for users, as the defaults will work well (now!). 

The documentation should explain better what each traverse method means. I'll update it.
