### ISSUE TITLE
retrieve infinite users and retryonratelimit when use search_users don't work

### ISSUE THREAD

**Issue by tonghuixu** [ropensci/rtweet#705]
### Problem

When I use the search_users function, n = Inf and retryoneratelimit = TRUE don't work

### Reproduce the problem

``` r
## 
     user_test <- search_users("#rstats", n =1000, retryonratelimit = TRUE)
      user_test <- search_users("#rstats", n = Inf)
     user_test <- search_users("#rstats", retryonratelimit = TRUE, n = Inf)
```

### rtweet version

``` r
## Warning message:
In search_users_call(q = "#rstats", n = Inf, parse = TRUE, token = NULL,  :
  search only returns up to 1,000 users per unique search. Setting n to 1000...

Error in search_users("#rstats", n = 1000, retryonratelimit = TRUE) : 
  unused argument (retryonratelimit = TRUE)

Error in search_users("#rstats", n = 1000, retryonratelimit = TRUE) : 
  unused argument (retryonratelimit = TRUE)

packageVersion("rtweet")
```

### Session info

``` r
## copy/paste output
sessionInfo()
```

**Comment by tonghuixu** [comment]
Based on this documentation, it seems that n could be set to Inf and retryonratelimit can be used. 
https://docs.ropensci.org/rtweet/reference/search_users.html

**Comment by llrs** [comment]
Could you post the rtweet version you are using? Setting n = Inf option only works on the devel version not on CRAN version.

**Comment by tonghuixu** [comment]
Sure. Please see it below:

> packageVersion("rtweet")
[1] ‘0.7.0’

How to use the devel version?

**Comment by llrs** [comment]
The devel version is not ready for CRAN and all users. If you read the help of search_users (on your terminal `?search_users` it will explain how to use it (and not the online version which is the one for rtweet on github). 
If you still want to use the in development version you can use `remotes::install_github("ropensci/rteweet")`.
