### ISSUE TITLE
Could not find function "ask_pass"

### ISSUE THREAD

**Issue by aterhorst** [ropensci/rtweet#709]
### Problem

rtweet_app() fails. There is no function ask_pass as described in help.

I expected the rtweet authentication to work. It is a lovely package but the authentication documentation is confusing.

``` r
rtweet_app(bearer_token = ask_pass(Sys.getenv("BEARER_TOKEN"))) 
Error in ask_pass(Sys.getenv("BEARER_TOKEN")) : 
  could not find function "ask_pass"


```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
[1] ‘0.7.0.9000’
```

### Session info

``` r
## copy/paste output
sessionInfo()
```

**Comment by llrs** [comment]
Please, could you post the full sessionInfo ?
If you are willing to install the development version of rtweet (your question on https://discuss.ropensci.org/t/rtweet-authorization/2938 which I have just answered, was with rtweet 0.7.0 which is CRAN's version) and here you report a higher version, please install the latest rtweet version 0.7.0.9.026.

**Comment by aterhorst** [comment]
I loaded the wrong dev version.  I used:

```
devtools::install_github("mkearney/rtweet"
```
I have fixed this and loaded:

```
remotes::install_github("rOpenSci/rtweet")
```
All good.
```
R version 4.1.3 (2022-03-10)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.7.0.9026

loaded via a namespace (and not attached):
 [1] prettyunits_1.1.1 fansi_1.0.3       withr_2.5.0       utf8_1.2.2        crayon_1.5.1      rappdirs_0.3.3    R6_2.5.1          jsonlite_1.8.0    lifecycle_1.0.1  
[10] magrittr_2.0.3    pillar_1.7.0      httr_1.4.3        progress_1.2.2    rlang_1.0.2       cli_3.3.0         curl_4.3.2        rstudioapi_0.13   vctrs_0.4.1      
[19] ellipsis_0.3.2    tools_4.1.3       bit64_4.0.5       glue_1.6.2        bit_4.0.4         hms_1.1.1         compiler_4.1.3    pkgconfig_2.0.3   tibble_3.1.7   
```

**Comment by llrs** [comment]
Reopening as I think that this could be prevented and avoid confusions for future users.

**Comment by aterhorst** [comment]
`rtweet_app(bearer_token = askpass::askpass())`. I cannot find a function def for `ask_pass()`. Am I missing something?

**Comment by llrs** [comment]
When I closed the issue at https://github.com/ropensci/rtweet/commit/88756a6da33b68029cf7e77b52bd2f043c669997, I hided `ask_pass` from users so in the latest version you shouldn't find it. However, if you want to read about the function you can find it at the [line 151 of auth.R](https://github.com/ropensci/rtweet/blob/master/R/auth.R#L151) (In the previous versions you could find it on the same file). 

If I were to set `rtweet_app` with a call to `askpass::askpass` this would add a direct dependency so askpass should be either on Imports or on Depends. As it currently is on Suggest the only correct way to use askpass is to use it conditionally (as it is currently done with `ask_pass`).

**Comment by aterhorst** [comment]
The new authentication process is much easier to use. Thanks for explaining things to me. `rtweet` is a great package!
