### ISSUE TITLE
tweets <- search_tweets("#actuallyautistic -filter:quote", n = 1000, include_rts = FALSE) 

### ISSUE THREAD

**Issue by Sue596** [ropensci/rtweet#717]
hi,  I always got the error when I run the code. Could anybody please tell me how to solve it? I am really appreciated for your kindness. Thank you. 

Error: $ operator is invalid for atomic vectors  
Error in tweet(x$quoted_status) : scopes  

code I run. 
tweets <- search_tweets("#autistic -filter:quote", n = 1000, include_rts = FALSE)

**Comment by llrs** [comment]
Hi, thanks for using rtweet and contribute to its improvement. 

In the issue template I ask for the version of rtweet you use. Could you please post it (`packageVersion("rtweet")` ? It will help me to check if it is a bug already fixed or not. 

In addition, if after getting the error you could post the output of `traceback()` that would also help me identify where the error is raised.

**Comment by llrs** [comment]
It seems that is already fixed, closing it now:

``` r
library("rtweet")
tweets <- search_tweets("#autistic -filter:quote", n = 1000, include_rts = FALSE)
packageVersion("rtweet")
#> [1] '0.7.0.9034'
```

<sup>Created on 2022-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Sue596** [comment]
Hi, I am sorry  didnot check the answer timely. 
Thank you so much for your answer. It is really helpful. 
I think you are right. The package I used was not ok. I used the following code to install again. It worked. 
install.packages("rtweet", repos = 'https://ropensci.r-universe.dev')
