### ISSUE TITLE
 Return frequency words are some other language instead of all of English 

### ISSUE THREAD

**Issue by Sue596** [ropensci/rtweet#718]
### Problem
I do not know why the return frequency words are some other language instead of all of english. I have defined lang="en" , Thank you.  Thank you you much. I am really appreciated it. 

### Expected behavior
need to where to find the issue. 

## insert code here
```r
tweets1 <- search_tweets("#autism",
                         lang="en", 
                         n=1000,
                         include_rts = FALSE,
                         retryonratelimit = TRUE)
tweets1 

save(tweets1, file = "D:/Task/tweets2_20220717.Rdata")

load("D:/Task/tweets2_20220717.Rdata")

tweets1$text <- gsub("http.*","",  tweets1$text)
tweets1$text <- gsub("https.*","", tweets1$text)
library(tidytext)
tweets_clean <- unnest_tokens(tweets1, word, text)

data("stop_words")
library(dplyr)
tweets_words <- anti_join(tweets_clean, stop_words, by = "word")

freq_words1 <- tweets_words %>%
  group_by(word) %>%
  summarize(count = n()) %>%
  filter(word != "autism") %>% 
  arrange(desc(count)) %>% 
  top_n(50)

freq_words2 <- tweets_words %>%
  group_by(word) %>%
  summarize(count = n()) %>%
  filter(word != "autism") %>% 
  arrange(desc(count)) %>% 
  top_n(20)
library(ggplot2)
ggplot(freq_words2, aes(y = reorder(word, count), x = count)) +
  geom_col(aes(fill = word), alpha = 0.7) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    title = "Most frequent words included in #autism tweets",
    x = "Word count",
    y = "",
    caption = "Note: Data included 1,000 tweets collected on July 17, 2022 via the public Twitter API"
  )
```

### rtweet version

0.7.0.9037 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/108994254/179548768-cce1146f-6e90-4257-83c9-d230ada69185.png">   
<img width="230" alt="image" src="https://user-images.githubusercontent.com/108994254/179548950-c1642f4c-2f77-4b41-b0b1-6c8aa06b16b1.png">   

freq_words1

**Comment by llrs** [comment]
I think the language tag is automatically defined via ML/AI. 
It could be a wrong label to a tweet or that it mixes several languages and alphabets. 
A way to avoid these other alphabets would be to just keep [:alnum:]; depending on the locale it might filter out those other characters. 

Sorry this is the data that twitter delivers there is nothing rtweet can do to prevent this. 
Please post your questions on https://discuss.ropensci.org.
