### ISSUE TITLE
Error in utils::write.table(x, file_name, row.names = FALSE, na = na,  :    unimplemented type 'list' in 'EncodeElement'

### ISSUE THREAD

**Issue by piervel** [ropensci/rtweet#734]
### Problem

When using `write_as_csv`, I got an error message:

```
Error in utils::write.table(x, file_name, row.names = FALSE, na = na,  : 
  unimplemented type 'list' in 'EncodeElement'
In addition: Warning message:
In flatten(x) : data frame still contains recursive columns!
```

### Reproduce the problem

``` 
tweets <- search_tweets("wind energy", n = 40000, language="en", retryonratelimit=TRUE)
write_as_csv(tweets, file_name = paste0(dir,paste0('/tweets_', Sys.Date(), '.csv')))
```

### rtweet version

``` r
## copy/paste output
1.0.2
```

### Session info

``` r
## copy/paste output
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
```

**Comment by llrs** [comment]
`write_as_csv` is deprecated and only works with the old data of rtweet (version <= 0.7.0).
With the new data you'll need to save if yourself in your preferred format, see the discussion in this other post in [the rOpenSci discuss](https://discuss.ropensci.org/t/rtweet-save-as-csv-failing/3073/2) which might help you too. 
I recommend to [read the post](https://ropensci.org/blog/2022/07/21/rtweet-1-0-0/) describing the changes with the latest rtweet release.
