### ISSUE TITLE
old names in code for post message

### ISSUE THREAD

**Issue by simonheb** [ropensci/rtweet#742]
https://github.com/ropensci/rtweet/blob/14c89649e152f1c1609f9dc3d65234dbf2560d8e/R/post-message.R#L13

didn't follow the development of this code for some weeks, but isn't this supposed to be `id_str` rather than `user_id`?

**Comment by llrs** [comment]
Indeed and was reported in #735  and fixed recently in the devel branch. Sorry for the inconvenience
