### ISSUE TITLE
post_tweet with media and in_reply_to_status_id does not work

### ISSUE THREAD

**Issue by neuwirthe** [ropensci/rtweet#745]
### Problem

Using package version 1.0.2.9009
the following code produces an error with the last command

```
library("rtweet")
auth_as("...")

png("plot_1.png")
plot(1:10)
graphics.off()

post_tweet("hello, 1st tweet")
my_last_tweet <- get_my_timeline()$id_str[1]
post_tweet("2nd tweet without image",
           in_reply_to_status_id=my_last_tweet)
my_last_tweet <- get_my_timeline()$id_str[1]
post_tweet("3rd tweet with image",
           media="plot_1.png",
           in_reply_to_status_id=my_last_tweet)
```

The error message is

```
Error: Media and alt_text must be character vectors.
```

But the media argument is a string and no media_alt_text argument is given.

**Comment by llrs** [comment]
Yes, you need to provide the media_alt_text with the alternative text for the image. This should also happen if you use rtweet 1.0.2.

**Comment by neuwirthe** [comment]
I stumbled because this was not necessary in version 0.7.0.

**Comment by llrs** [comment]
Yes, but if I recall correctly in 0.7.0 there was no possibility to use alt text
