### ISSUE TITLE
V1.1 streaming endpoint deprecated

### ISSUE THREAD

**Issue by alanault** [ropensci/rtweet#749]
It seems that Twitter has recently deprecated the streaming endpoint for API v1.1 and attempts to stream result in a 410 error

Is there a plan to incorporate the v2 streaming endpoint in ```rtweet::stream_tweets```?

```
library(rtweet)
auth_setup_default()
stream_tweets("")

Writing to 'stream_tweets.json'
Error in open.connection(stream, "rb") : HTTP error 410.
```

**Comment by llrs** [comment]
Yes, I was expecting this, as it was announced for a month ago. In the devel branch there is support for the new API v2 endpoint for streaming.

I'm still working on it but I plan to make a new release with some support for it soon (this month hopefully). Currently it stores the very basic information about tweets without expansions and fields or rtweet parsing the file. In future releases I would increase the support for the API v2 to parse it and handle expansions and the fields. If you test it do not hesitate to give feedback in this issue.

**Comment by alanault** [comment]
Great! Will look out for this and start some testing when it's ready

**Comment by llrs** [comment]
It is ready (I will release a new version of rtweet this week).
Please let me know if you find any problem using it.

**Comment by jimsharma206** [comment]
> It is ready (I will release a new version of rtweet this week). Please let me know if you find any problem using it.

Hello! I was wondering if the new version for rtweet was available. I have a bearer token, but I am unable to use the function stream_tweets. I get http error 403. Any help would be gratefully appreciated

**Comment by llrs** [comment]
Yes, it was released just today. Just update the package and it should work

**Comment by jimsharma206** [comment]
How do I enter my bearer token?
![image](https://user-images.githubusercontent.com/118120798/211572616-f694e1cf-8804-4015-8ec7-c221d4a72e3f.png)
