### ISSUE TITLE
The end of support of free access to the Twitter API?

### ISSUE THREAD

**Issue by erdnaxel** [ropensci/rtweet#761]
Twitter posted this today:
![image](https://user-images.githubusercontent.com/63831549/216400140-06823788-7d28-49ff-832a-5d2005f6628a.png)

Does it mean rtweet will no longer work?

**Comment by llrs** [comment]
Hi, thank you for asking. 
I posted my comment in several places: [quoting the tweet](https://twitter.com/Lluis_Revilla/status/1621037116334477312), [in a comment](https://twitter.com/Lluis_Revilla/status/1621170453233426434), and in another [issue](https://github.com/ropensci/rtweet/issues/344#issuecomment-1413624763). 

The package will work if they don't change anything else. What will change is that I will no longer be able to test and develop without paying, and only people or companies that pay for the API will be able to use it. 

I will post more as the events develop, but I will probably write a post in my blog and announce my decision in twitter.

**Comment by llrs** [comment]
There is new information from Twitter in a [new thread](https://twitter.com/TwitterDev/status/1623467615539859456):
[There seems](https://twitter.com/TwitterDev/status/1623467618400374784) to be some kind of free plan, but [premium users might lose access](https://twitter.com/TwitterDev/status/1623467619725774848) (unless they "upgrade" to a new tier/access/?). 

As with the last update a week ago, let's see what happens.

**Comment by erdnaxel** [comment]
thanks for the update!

**Comment by llrs** [comment]
Developer might have received the following email, I only received an email from one of my twitter accounts with developer access (I removed the links which have tracking ids):


> Hello,
> 
> We are excited to share some updates regarding the Twitter API so you can keep building and innovating with us. Twitter offers one of the world’s most powerful data sets, and our recent updates will enable you to continue to tap into all its potential.
> 
> Basic access
> On February 13, we will introduce our new low-cost, basic access that offers a low level of API usage, and full access to Ads API for a $100 monthly fee. This basic access will replace our previous access levels (Essential, Elevated, and Academic Research). We will provide instructions on how to subscribe to the basic access through our website on Monday.
> 
> 
> Limited free access
> As this is extremely important to the developer ecosystem, we will also introduce a new form of free write access to the Twitter API limited to Tweet creation of up to 1,500 Tweets per month for a single authenticated user token, as well as including free access to Login with Twitter. If you are currently on a free tier and you want to take advantage of the new limited free access, no actions are necessary - you will automatically be switched to the new free access on February 13.
> 
> 
> Premium API deprecation
> On February 13, we will also deprecate the Premium API access. If you’re subscribed to Premium, you can apply for Enterprise access here to continue using these endpoints.
> 
> We truly believe that the developer community can continue to create value with our Twitter API. We hope you are excited about this new chapter of the Twitter Developer Platform as we continue to invest in our ecosystem’s success. Please continue to follow @TwitterDev for the latest updates.
> 
> Thank you,
> The Twitter Developer Platform team

It seems that every user of rtweet will need to apply for developer access (the credentials currently shared with rtweet might no longer work). Once authenticated they might be able to post tweets. The authentication mechanism and how they will restrict the access to the API v2 will decide the future of rtweet.

**Comment by under-score** [comment]
```
> setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()
```
maybe the error message should be read "you have been kicked out?"

**Comment by llrs** [comment]
@under-score The `setup_twitter_oauth` function is not from rtweet. Did you meant to comment in a different package? rtweet is working because as explained in this thread there haven't been any changes in the API (yet).

**Comment by under-score** [comment]
sorry, installed the twitter packages long ago, but also the same effect here
```
> auth <- rtweet_app()
> df <- search_tweets("#rstats", token = auth)
Error: Twitter API failed [403]. Check error message at https://developer.twitter.com/en/support/twitter-api/error-troubleshooting 
 * You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve (453)
```

**Comment by llrs** [comment]
@under-score 
1) This means your authentication method used will work with the API v2 (which currently rtweet only supports the streaming endpoints). This is expected, and rtweet works as expected.
2) Please make sure before posting here that it is relevant to the issue.

**Comment by llrs** [comment]
In [the latest update of TwitterDev](https://twitter.com/TwitterDev/status/1625234161010343941), they postpone the changes:

> There has been an immense amount of enthusiasm for the upcoming changes with Twitter API. As part of our efforts to create an optimal experience for the developer community, we will be delaying the launch of our new API platform by a few more days. 
> 
> More information to follow over the coming days. Thank you for your continued interest and patience!

Of interest, it seems, that internally they increased the tweet length to more than 280 characters as that tweet has > 350 characters (and no link). Other accounts, which seem used internally for testing, had previously also tweeted with more than 280.

**Comment by llrs** [comment]
Hi all, I wrote [a post](https://llrs.dev/post/2023/02/16/rtweet-future/). Let me know if you you have comments or other feedback here.

cc: @eliocamp, @ccamara, you were interested in this.

**Comment by llrs** [comment]
Some relevant information from [TwitterSupport](https://twitter.com/TwitterSupport/status/1632792942262747136) confirming that there is few testing before changes affect the platform (this happened before November 2022 too):

> Some parts of Twitter may not be working as expected right now. We made an internal change that had some unintended consequences. We’re working on this now and will share an update when it’s fixed.

The API seems to still work (but not tweetdeck, or links, and some images are not displayed). Posting it here in case anyone is wondering

**Comment by llrs** [comment]
Today [Twitter released more information](https://twitter.com/TwitterDev/status/1641222782594990080) about the planned updates. In addition, they will remove the Standard (v1.1), Essential (v2), Elevated (v2), and Premium access tiers in 30 days. 


[Free](https://developer.twitter.com/en/portal/products/free): Post and delete tweets and look up information from one (user_self()) at most post up to 1500 Tweets per month
[Basic](https://developer.twitter.com/en/portal/products/basic): Retrieve up to 10K Tweets per month, and 50,000 POST/month, 2 app IDs for $100.00 USD/month and use all the other endpoints except the streaming endpoints.
Higher rates: Available through [a form](https://forms.gle/H1eoXw7pZft5ByDT6)
Academic: To be announced

**Comment by llrs** [comment]
In an expected move Twitter removed the access of the default app of rtweet. 
See [this comment in another issue](https://github.com/ropensci/rtweet/issues/756#issuecomment-1497464678). Currently [this is the situation](https://twitter.com/Lluis_Revilla/status/1643373860656500736): default authentication does not work, bearer token do and the default OAuth2 provided work.

**Comment by llrs** [comment]
There is an [update from Twitter](https://twittercommunity.com/t/deprecation-of-legacy-access-tiers-in-the-twitter-api/196162): 

> As [announced previously](https://twitter.com/TwitterDev/status/1649191521323995138), we have deprecated our legacy Twitter API access tiers. Thus, essential and elevated packages are no longer available. Applications and projects have been placed in the appropriate new [Free access tier](https://developer.twitter.com/en/portal/products/free).
> 
> If your app has been suspended as part of this, please sign up for the [Free access tier](https://developer.twitter.com/en/portal/products/free) to have it unsuspended.
> 
> As a reminder, the Free access tier supports:
> 
>   -  [V1.1 Media Endpoints](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/overview)
>   -  [V1.1 OAuth endpoints](https://developer.twitter.com/en/docs/authentication/oauth-1-0a) (Login with Twitter)
>   -  [V2 Manage Tweet endpoints](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/)
>   -  [V2 users/me endpoint](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-me)
> 
> If you want to use other functionality in the Twitter API v2, please consider using the Basic or Pro packages. Learn more about these packages [here](https://developer.twitter.com/en).
> 
> Thank you.

**Comment by sunta3iouxos** [comment]
Sorry for posting here, are all those updates mean that rtweet will not work? I just found this R function, since I wanted to extract scientific topics and links to publications. But, I am not able to use it.
getting an "Error in httr::init_oauth1.0(endpoint, app, permission = permission, is_interactive = is_interactive,  : 
  Unauthorized (HTTP 401)." and though that this is relevant to post Musk tweeter.
  Sorry, if this is off-topic, otherwise I will creat a newer inquire 
Thank you

**Comment by llrs** [comment]
Rtweet continues to work, but it might only work on some endpoints or with limited (free) access. 

As the error message says, you'll need to provide your own credentials. If you have troubles, please ask a question (this is not an issue in the package) in StackOverflow, discuss.ropensci.org or community.rstudio.com with the rtweet tag.

**Comment by llrs** [comment]
I have received a new message:


> As part of our ongoing effort to modernize and transform our API platform, we are deprecating some of our v1.1 endpoints and asking you to migrate to the v2 equivalent (see table below). While we are currently not replacing a few legacy endpoints, these deprecations will allow us to continue building to support the latest X features into our v2 APIs. We will continue deprecating v1.1 endpoints in the future and highly suggest [mapping out](https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map) your existing consumption to prepare for future migrations.
> 
> In addition, we will retire legacy v2 access tiers including Essential and Elevated (for those who still have it) within the next 30 days. To maintain access to our v2 API, please log into your developer account and enroll into [Free, Basic, Pro, or Enterprise](http://developer.x.com). Please reach out to our developer support as needed.
> 
> We’re excited to continue building together on the next generation of X API!
> Thank you,
> X Developer Platform
> 
> 
> 
> API Endpoint | Retirement Date | Replacement
> -- | -- | --
> /1.1/search/tweets.json | September 20th | Recent Search
> /1.X/users/search/ | September 20th | No Replacement
> /1.X/geo/search/ | September 20th | No Replacement
> /1.1/statuses/destroy | November 20th | Manage Tweets
> /1.1/statuses/update | November 20th | Manage Tweets
> /1.1/statuses/show | November 20th | Tweets Lookup
> /1.1/statuses/lookup | November 20th | Tweets Lookup
> /1.1/statuses/retweet | November 20th | Manage Retweets
> /1.1/statuses/unretweet | November 20th | Manage Retweets
> /1.1/statuses/update_with_media | November 20th | No Replacement
> 
> </div>As part of our ongoing effort to modernize and transform our API platform, we are deprecating some of our v1.1 endpoints and asking you to migrate to the v2 equivalent (see table below). While we are currently not replacing a few legacy endpoints, these deprecations will allow us to continue building to support the latest X features into our v2 APIs. We will continue deprecating v1.1 endpoints in the future and highly suggest [mapping out](https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map) your existing consumption to prepare for future migrations.
> 
> In addition, we will retire legacy v2 access tiers including Essential and Elevated (for those who still have it) within the next 30 days. To maintain access to our v2 API, please log into your developer account and enroll into [Free, Basic, Pro, or Enterprise.](http://developer.x.com/) Please reach out to our developer support as needed.
> 
> We’re excited to continue building together on the next generation of X API!
> 
> Thank you,
> 
> X Developer Platform
> API Endpoint 	Retirement Date 	Replacement
> /1.1/search/tweets.json 	September 20th 	[Recent Search](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent)
> /1.X/users/search/ 	September 20th 	No Replacement
> /1.X/geo/search/ 	September 20th 	No Replacement
> /1.1/statuses/destroy 	November 20th 	[Manage Tweets](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/delete-tweets-id)
> /1.1/statuses/update 	November 20th 	[Manage Tweets](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/introduction)
> /1.1/statuses/show 	November 20th 	[Tweets Lookup](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference)
> /1.1/statuses/lookup 	November 20th 	[Tweets Lookup](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference)
> /1.1/statuses/retweet 	November 20th 	[Manage Retweets](https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference)
> /1.1/statuses/unretweet 	November 20th 	[Manage Retweets](https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference)
> /1.1/statuses/update_with_media 	November 20th 	No Replacement

**Comment by llrs** [comment]
This package has been archived; you can request for it to be unarchived if you opt to resume maintenance, for that please contact rOpenSci.
