### ISSUE TITLE
Call for co-maintainer

### ISSUE THREAD

**Issue by llrs** [ropensci/rtweet#763]
I am looking for a co-maintainer to help me:
 - Supporting new endpoints, using httr2, testing an API in CI via httptest2, ...
 - Review changes to avoid new bugs, such as #756.
 - Help with issues and questions that the transition to API v2 and the current uncertainty around Twitter API.

I can help you with all the testing infrastructure (vcr, API credentials), github actions and the process of supporting and developing new functions. 
Of course, I will continue to answer issues and questions too, and you can ask me when in doubt.
For further context I [wrote a post](https://llrs.dev/post/2023/02/16/rtweet-future/).

I will take care of the CRAN submission process :smile:

**Comment by PythonCoderUnicorn** [comment]
as someone who really enjoyed using this package before Musk,  I am interested, but have no experience on package maintenance and/or the specific help wanted points. 

Thanks for working on this package.

**Comment by llrs** [comment]
Thanks! That's Ok, there is no need to put in X hours or do Z tasks. 
There is a lot that can be done without technical experience, for example just testing and reporting if the way the functions work make analysis simple would be helpful.

You can start looking at the [devel branch](https://github.com/ropensci/rtweet/tree/devel) to familiarize yourself with the code. I'll open pull requests for you to have a look (but I'm in the middle of big changes for the API v2 and I don't want to throw you under the bus). If you want, we can talk privately (are you in the rOpenSci slack?) about further steps.

**Comment by llrs** [comment]
@PythonCoderUnicorn Hi Zane. Is there a way to get in touch with you privately to set up a meeting? Could you send me an email (it is in the package description file)?

**Comment by PythonCoderUnicorn** [comment]
I did have initial interest, but considering the chaos happening at Twitter, 

-  I morally can't support twitter nor Musk
- doubt that the platform will last much longer with less staff by the week

I do wish you luck on finding some help, sorry.

**Comment by llrs** [comment]
Understood. Thanks for volunteering, though!

**Comment by howardbaek** [comment]
Are you still looking for a co-maintainer? I'm interested.

**Comment by llrs** [comment]
Hi Howard, the situation is a bit tricky. 

When I posted this I was about to release a new version to CRAN and anticipating more usage and questions. Since the Twitter policy changes I have observed the opposite: less people using rtweet (but this might be a sampling error), and more questions about Twitter policies instead of rtweet. 

The API changes also made harder to test and check different endpoints and extend rtweet. 
However, if you want to work on it please go ahead. Do you have any specific feature you want to include in rtweet? Or said in another way, why do you want to co-maintain the package?

**Comment by howardbaek** [comment]
I have been learning web APIs and using httr/httr2. I read your original post, and was interested in supporting new endpoints, using httr2, testing an API in CI via httptest2.  

I understand what you are saying, and if you don't need another co-maintainer, I'm fine with working on individual features from time to time. I just want to learn about the whole ecosystem of web APIs and thought this package would be a good opportunity.

**Comment by llrs** [comment]
Ok, if you can support new endpoints go ahead, I'm sure users will like them. 

The API v2 uses httr2, so you can start by adding httptest2 for the current endpoints that exists but don't have tests. 
We can start working via pull requests and if things go smoothly I'll give you access to the whole repository.

**Comment by howardbaek** [comment]
Sounds like a plan!
