### ISSUE TITLE
search_tweets fails with error 403

### ISSUE THREAD

**Issue by ronirg** [ropensci/rtweet#773]
Hi
I created a free app in the Twitter developer portal.
When I ran search_tweets got error 403.
It looks like the free account doesn't have permission to search tweets,  only the basic account.
The error mentions elevated access, but it looks like there is no longer elevated access.
Is there an option to search tweets freely?
Following is my code:

# code
bearer_token <- "my_bearer_token"
auth <- rtweet_app(bearer_token)
auth_as(auth)
auth_get()
# search tweets
tweets <- search_tweets(q = "#keyword", n = 100, lang = "en", include_rts = FALSE, type = "recent")

# output
Error: Twitter API failed [403]. Check error message at https://developer.twitter.com/en/support/twitter-api/error-troubleshooting 
 * You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you<U+2019>ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve (453)

### rtweet version
packageVersion("rtweet")
 '1.1.0'
### Session info
sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] C
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_1.1.0

**Comment by llrs** [comment]
Yes, you can't use the search_tweets without elevated access. I think the link to get that access was here in the issue page (but I might be wrong). In any case with the new tiers it is not possible to search for tweets without paying. In that case you should be using `tweet_search_recent` and `tweet_search_all`.

I also recommend to upgrade to version 1.2 from github. It has some updates and bug fixed.

**Comment by llrs** [comment]
the `search_tweets` uses the API v1.1 while the `tweet_search_*` uses the API v2. Only the later is maintained by Twitter.

**Comment by ronirg** [comment]
Thanks.
