### ISSUE TITLE
OAuth 2.0 expected when OAuth 1.0 is also possible (tweet_post)

### ISSUE THREAD

**Issue by pasipasi123** [ropensci/rtweet#774]
I'm running the latest github version and I'm trying to post (bot) tweets via Twitter API v2 on the free plan. 

```
> packageVersion("rtweet")
[1] ‘1.2.0.9003’
```
The problem is that the new `tweet_post()` function expects OAuth 2.0 with PKCE authentication even though the [Twitter documentation](https://developer.twitter.com/en/docs/authentication/guides/v2-authentication-mapping) among other sources indicate that also OAuth 1.0a User Context is possible with `tweet.write`.

I can post tweets by creating a client with my OAuth 2.0 client id and client secret keys and authorizing with `rtweet_oauth2()` etc, but the problem is that the authentication expires after 2 hours (not good for bots).

I _can't_ post tweets by authenticating with my OAuth 1.0 keys (access token and secret) using my own client (api key, api secret) and `rtweet_bot()`:

```
> tweet_post("test")
Error in `tweet_post()`:
! ✖ An OAuth 2.0  is needed for this endpoint.
ℹ Get the authorization via `rtweet_oauth2()`
```
In the `tweet_post()` code PKCE is expected, so the function stops. 
```
token <- check_token_v2(token, "pkce")
```
The lines following the PKCE check seems to also expect an OAuth 2.0 object. 

Since the default rtweet client is no longer authorized, I'm creating my own, but it seems that even the `rtweet_client()` function is based on OAuth 2.0 authentication.

**Comment by llrs** [comment]
Yes, it is possible but not supported in rtweet, new functions of the API v2 only support the bearer token or the OAuth 2.0. I probably should document that better. 

I don't think Twitter will support/maintain OAuth 1.0 access given the size of the letter in the [specific documentation pages](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets). (Note that for OAuth 1.0 you don't need to specify scopes, so the `tweet.write` scope is not needed)
I could look into it and try to support old OAuth 1.0, but I think it is easier for users to get their OAuth 2.0 credentials; some endpoints in the API v2 only work with it so this is also beneficial to them.

**Comment by pasipasi123** [comment]
You might be right. 

What about the `offline.access` scope mentioned [here](https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code)? "Stay connected to your account until you revoke access." Worth looking into (twitter bot perspective)?

**Comment by llrs** [comment]
This is a different question and I am not sure to understand it. Do you mean if rtweet uses it? Yes it uses it by default, the problem with the renewal of the OAuth 2.0 token is from Twitter which changes the default refresh token which caused an error in a package rtweet depends...

This seems fixed in the devel version (see [this issue](https://github.com/r-lib/httr2/issues/186)) I'll  update the code accordingly to make it easier to use the OAuth 2.0.

---

Note to myself, this will require a hard dependency in httr2 > 0.2.3

**Comment by pasipasi123** [comment]
The question is different but the problem at a more basic level is the same: I need to have a more permanent authentication solution for my twitter bot needs. 

It seems that creating simple bots that just post tweets (no interaction) is possible also in the future. Currently creating a new developer account and getting access to the Twitter developer portal and free plan is instant, there's no approval requirement, so getting access to the necessary API keys is very easy, possibly easier than before. All this might still change though. 

Thanks for looking into this.

**Comment by llrs** [comment]
You will need to install httr2 from github (`remotes::install_github("r-lib/httr2")`) but I think this is fixed in the devel branch of rtweet (`remotes::install_github("ropensci/rtweet@devel")`). I also improved the way to refresh the tokens so if you run this from your computer, as opposed to github actions, it will be much easier to have a "permanent" authentication. 
Users shouldn't need to update their code (but I haven't tested it much yet). 

Let me know if it works or not.

**Comment by pasipasi123** [comment]
Thanks.
```
> packageVersion("httr2")
[1] ‘0.2.3.9000’
> packageVersion("rtweet")
[1] ‘1.2.0.9004’
```
```
> auth_get()
<httr2_token>
token_type: bearer
...
```
`httr2` seems to expect a character token.

```
> tweet_post("test")
Error in `check_string()`:
! `token` must be a string
```
```
Backtrace:
    ▆
 1. └─rtweet::tweet_post("test")
 2.   └─rtweet:::endpoint_v2(token, "tweets", rate)
 3.     ├─httr2::req_url_path_append(req_v2(token), path)
 4.     │ └─httr2:::check_request(req)
 5.     │   └─httr2:::is_request(req)
 6.     └─rtweet:::req_v2(token)
 7.       └─rtweet:::req_auth(req_agent, token)
 8.         └─httr2::req_auth_bearer_token(req, token)
 9.           └─httr2:::check_string(token, "`token`")
 ```

**Comment by pasipasi123** [comment]
The master branch has this `req_auth()`
```
req_auth <- function(req, token) {
  if (auth_is_bearer(token)) {
    token <- token$token
  } else if (auth_is_pkce(token)) {
    token <- auth_renew(token)
    token <- token$access_token
  }
  httr2::req_auth_bearer_token(req, token)
}
```
In the devel branch `token <- token$access_token` is missing. I'm guessing it should be there?

**Comment by pasipasi123** [comment]
Hi and thanks again for your work. 

`tweet_post()` is posting tweets now. 

It is diplaying a warning with each post even though it is rewriting the `renewed_token.rds` file (resulting from not finding the auth file in the `auth_path`) each time:
```
Warning message:
Refresh token has changed! Please update stored value
```

I have a slight confusion about the file locations, but it's mostly unrelated and could be a topic for another issue: I've always kept my tokens in my project's root folder but that doesn't seem to be possible. `tweet_post()` is looking for a client using the `rtweet:::client_path` function even though I had already been using `client_as()` in my testing. Same goes for the auth object.

**Comment by llrs** [comment]
I might have forgotten a safeguard to not update the token each time. I'll check and add it back later. I also want to handle silently the warning as I already deal with storing the token. However, according to the information available the token refresh does not work reliably.

The tokens and the clients are stored in two folders (the clients one below the tokens)
It is possible to have the tokens in your project if you set the path as an `option("rtweet:::config_dir" = "~/my_project")`, another option is to directly use the path to the token when loading it `auth_as("~/my_project/my_token.rds")` (I haven't checked if this way the token is resaved to the same location but it should work). 
Clients are handled differently and you shouldn't have them in the project, use `client_save(client)`.
If this doesn't work, please post how you load and save the tokens and clients.

I would also recommend to use `auth_sitrep()` to check what tokens you have in your system.

**Comment by pasipasi123** [comment]
I'll do some further testing, thanks.

Regarding the client: It looks like there is a 1,500 tweet limit per app per month, so one client works for only `1,500 / 30 = 50 per day` (if I understand the limits correctly). My bots usually tweet about once per hour so one app/client is safe for two hourly bots at most but to keep it safe (maybe I want to add daily and weekly tweets), one app/client is good for only one bot.

**Comment by llrs** [comment]
rtweet does not go against the API rules. I won't help to overcome these limitations: each token is associated with a given client.

**Comment by pasipasi123** [comment]
That was not my point. My point is that to overcome limitations, it's probably necessary to have more than one client, ie. one client per project.

**Comment by llrs** [comment]
You already can have more than one client, there is no problem with that. This was precisely why there is a single place to store different tokens and clients. I also use/keep several apps in my computer, each one with their own client.

**Comment by pasipasi123** [comment]
I guess I can adjust my thinking and place all client (and auth) files in the same place. I've just had the habit of keeping project related files with the project. With bots, there's also the deployment to maybe some VPS, but I guess it's just as easy with two file locations as it is with one.

**Comment by llrs** [comment]
There are other options too. You can hire me if you want further help. But as you previously said, this is going off-topic.

I'll try to fix the issue about the warning and renewing the token each time (I'm surprised you didn't find any problems refreshing it)

**Comment by pasipasi123** [comment]
There are problems when refreshing the token after the expiration period. Previously I had tried only renewing before the expiration time. I'm guessing that all scopes can't be refreshed without interaction? 

Setting scopes manually does not work because in the `rtweet_client` code manually entered scopes are erased in the line `scopes <- check_scopes(scopes)` (which returns `TRUE`), so `attr(client, "scopes")` just returns `TRUE`.

With a slight edit to the `rtweet_client` code (comment out the `check_scopes`) I can create a client object with just `tweet.write` and `offline.access` scopes, but `rtweet_oauth2` still returns `Requires confirming permissions to the app (client) every two hours!`. I'm not sure if that means that renewing is not possible.

**Comment by llrs** [comment]
Currently if the automatic renewal doesn't work, that is a problem on Twitter side, the interactive method is used. It doesn't depend on the scopes.
 
I don't understand your second paragraph. What it has to do with refreshing the token?
I think you will need to open a new issue, after you make sure that there is an issue in rtweet. If you want more help I cannot provide it unless you pay for my time.

**Comment by pasipasi123** [comment]
I'm sorry for so uneducated questions and unfocused issue. It shows that OAuth 2.0 is entirely new to me. 

I've now had several successful scheduled hourly bot tweets from one of my bots so it looks like renewal is working after all. I must have made some mistake before when moving the files between two computers that prevented the renewal.
