### ISSUE TITLE
Error OAuth 2.0 post tweet via Free Access.

### ISSUE THREAD

**Issue by upliftingx** [ropensci/rtweet#781]
### Problem
Code produces this error when submitting tweet: 

Error: Twitter API failed [403]. Check error message at https://developer.twitter.com/en/support/twitter-api/error-troubleshooting 
 * You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product (453)

### Expected behavior
I expect the code to post the tweet with the media, the documentation says that OAuth2.0 allows for 1500 tweet creations for free.

### Reproduce the problem
Running the code below will reproduce the issue.

``` r
## insert code here
library(rtweet)
library(magick)

# Setwd can not be using on shinyapps.io.
# Sets the working directory to the same folder as the R script is located in.
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

user <- rtweet_user(client_id = client_id,
              client_secret = client_secret,
              api_key = api_key,
              api_secret = api_secret
)

auth_as(user)

auth_save(user, "oauth2_authentication")

alt_text <- as.character(paste("'text':", "'A picture of a cross.'")
)

img_url = "https://as1.ftcdn.net/v2/jpg/02/51/60/48/1000_F_251604801_9idHZ4dhKWcHtOLqOFatij6J4p1dr7Wr.jpg"

temp_file <- tempfile(fileext = ".jpeg")
download.file(img_url, temp_file)

post_tweet("But seek first the kingdom of God and His righteousness, and all these things shall be added to you. - Matthew 6:33",media = temp_file, media_alt_text = "A Christian cross.")

```

### rtweet version

``` r
## copy/paste output
packageVersion("rtweet")
```
Version: ‘1.2.0.9003’

### Session info

``` r
## copy/paste output
sessionInfo()
```

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magick_2.7.4      rtweet_1.2.0.9003

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10       rstudioapi_0.15.0 raster_3.6-20     magrittr_2.0.3    lattice_0.20-45  
 [6] xtable_1.8-4      R6_2.5.1          rlang_1.1.0       fastmap_1.1.1     httr_1.4.6       
[11] tools_4.2.2       grid_4.2.2        terra_1.7-29      cli_3.6.1         withr_2.5.0      
[16] htmltools_0.5.5   askpass_1.1       ellipsis_0.3.2    openssl_2.1.0     digest_0.6.31    
[21] lifecycle_1.0.3   shiny_1.7.4.1     later_1.3.1       codetools_0.2-18  promises_1.2.0.1 
[26] triebeard_0.4.1   curl_5.0.1        mime_0.12         sp_1.6-1          compiler_4.2.2   
[31] urltools_1.7.3    jsonlite_1.8.7    httpuv_1.6.11

**Comment by llrs** [comment]
To authenticate via OAuth2.0 you need to follow the [authentication vignette](https://docs.ropensci.org/rtweet/articles/auth.html#alternative-authorization-protocol) to setup a client and authenticate via [rtweet_oauth2](https://docs.ropensci.org/rtweet/reference/rtweet_user.html). 

The function `post_tweet` uses the API v1, which is no longer working. In order of post using the API v2 of Twitter you should use the function [`tweet_post`](https://docs.ropensci.org/rtweet/reference/tweet_post.html). That function doesn't allow to post images (yet). 

You might be interested in related issues #778, #774
