### ISSUE TITLE
API v2 raising error on successful response

### ISSUE THREAD

**Issue by MKatz-DHSC** [ropensci/rtweet#789]
### Problem

Package raises an exception even when a response has status 200 if the response body has errors.

This means that an exception is raised when API successfully retrieves requested tweets but is unable to retrieve associated referenced tweets. 

Links to issue #788. This problem is based on a code review as unable to replicate due to  issue #788 

### Expected behavior

Values in response body error are flagged to the user is response status is 200 but do not raise an exception.

### Detail

Issue is caused by `req_is_error` function in file api_v2_utils.R line 102 returning TRUE even with 200 status. 

``` r
has_name_(r, "errors") || httr2::resp_is_error(resp)
```

### Reproduce the problem

``` r
rtweet::user_liked_tweets(
  id = "61183568",
  n = 200,
  expansions = rtweet::set_expansions(
    tweet = "referenced_tweets.id",
    user = NULL,
    list = NULL
  ),
  token = NULL,
  parse = FALSE
)
```

### rtweet version

1.2.1

**Comment by llrs** [comment]
This is a bit tricky, as I assumed there wouldn't be errors if the requests is successful. Could you post the relevant output of this call? You can do this by doing `debugonce(rtweet::req_is_error)` and copy here the `r$errors` data. Thanks

**Comment by MKatz-DHSC** [comment]
Hi Lluís,

Thanks for looking into this and sorry I can't provide more support re funding and time - this package is extremely useful and very much hope it can continue to be developed!

Below is the output you requested:
``` r
r$errors
               value
1 747509161110474752
2 505591864746319872
3 241260646417723392
                                                                                           detail
1                           Could not find tweet with referenced_tweets.id: [747509161110474752].
2 Sorry, you are not authorized to see the Tweet with referenced_tweets.id: [505591864746319872].
3                           Could not find tweet with referenced_tweets.id: [241260646417723392].
                title resource_type            parameter        resource_id
1     Not Found Error         tweet referenced_tweets.id 747509161110474752
2 Authorization Error         tweet referenced_tweets.id 505591864746319872
3     Not Found Error         tweet referenced_tweets.id 241260646417723392
                                                            type  section
1          https://api.twitter.com/2/problems/resource-not-found     <NA>
2 https://api.twitter.com/2/problems/not-authorized-for-resource includes
3          https://api.twitter.com/2/problems/resource-not-found     <NA>
```

**Comment by llrs** [comment]
Thanks for the information. I'll think how to handle this. 
Even little problems like this one, becomes a big problem when I cannot test and check if it is solved correctly or not. 

I'll be very blunt: after this release I'll stop updating the package.  
To you, rtweet is "extremely useful" and you can spend time and money to use it. But currently to me, it is a burden with no personal or professional use, no joy, little recognition and no retribution.

**Comment by MKatz-DHSC** [comment]
I am very sorry that you feel that way, but completely understand. Thanks for all the work that you have done on this package and all the best for the future.

**Comment by llrs** [comment]
I removed the check, but I cannot test if parsing the output will work well. Ideally I would report that there are some errors via a warning.
