### ISSUE TITLE
Remove tryCatch

### ISSUE THREAD

**Issue by hadley** [ropensci/rtweet#88]
e.g. 

```R
  	r <- tryCatch(POST(
            url = url,
            config = token,
            write_disk(file_name, overwrite = TRUE),
            add_headers(`Accept-Encoding` = "deflate, gzip"),
            progress(), timeout(timeout)),
            error = function(e) return(NULL))
```

I'm not sure what you're trying to achieve here, but I think you should be silently swallowing errors and interrupts (i.e. pressing escape).

It's likely that you should also be calling `stop_for_status(r)` to ensure that HTTP errors are surfaced to the user.

**Comment by mkearney** [comment]
This looks like one of my [many] harebrained *solutions* to package dependency issues I didn't understand. The other one I remember involved `httr::content`, which I should also go back and re-incorporate.

**Comment by hadley** [comment]
Now part part of #483
